# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpE2ETestCase,
    E2EAction,
    E2ERequestScenario,
)


class TestReviewFormSubmissionViewE2E(BloomerpE2ETestCase):
    """Tests class `ReviewFormSubmissionView` from `bloomerp/views/forms/review_submission.py`."""

    view_name = 'Review Submission'

    def get_test_scenarios(self) -> list[E2ERequestScenario]:
        # Add only the browser scenarios this view needs.
        return []
