# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpDetailViewTestCase,
    ExpectedResult,
    RequestScenario,
    ModelRequestScenario,
)


class TestDocumentTemplateListDetailView(BloomerpDetailViewTestCase):
    """Tests class `DocumentTemplateListDetailView` from `bloomerp/views/generic/detail/document_templates.py`."""

    view_name = 'document_templates'
    model = None

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
