# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpDetailViewTestCase,
    ExpectedResult,
    RequestScenario,
    ModelRequestScenario,
)


class TestCreateUserView(BloomerpDetailViewTestCase):
    """Tests class `CreateUserView` from `bloomerp/views/generic/detail/create_user_for_object.py`."""

    view_name = 'create_user_for_object'
    model = None

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
