# Generated by manage.py generate_test_cases.
from bloomerp.automation.registry import WORKFLOW_NODE_REGISTRY
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestRenderAutomationDrawerComponent(BloomerpComponentTestCase):
    """Tests function `render_automation_drawer` from `bloomerp/components/automation/drawer.py`."""

    view_name = "components_automation_drawer"

    def get_test_scenarios(self) -> list[RequestScenario]:
        registered_node_ids = [
            definition.id for definition in WORKFLOW_NODE_REGISTRY.values()
        ]

        return [
            RequestScenario(
                name="redirect anonymous users to login",
                expected=ExpectedResult(
                    status_code=302,
                    response_validators=lambda response: response.headers[
                        "Location"
                    ].startswith("/accounts/login/"),
                ),
            ),
            RequestScenario(
                name="render every registered workflow node",
                user=self.admin_user,
                expected=ExpectedResult(
                    response_validators=lambda response: all(
                        f'data-node-subtype-id="{node_id}"'
                        in response.content.decode()
                        for node_id in registered_node_ids
                    ),
                ),
            ),
        ]
