# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpE2ETestCase,
    E2EAction,
    E2ERequestScenario,
)


class TestDownloadSdkviewViewE2E(BloomerpE2ETestCase):
    """Tests class `DownloadSDKView` from `bloomerp/views/sdk/dowload_sdk.py`."""

    view_name = 'download_sdk'

    def get_test_scenarios(self) -> list[E2ERequestScenario]:
        # Add only the browser scenarios this view needs.
        return []
