# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestWorkspaceFiltersLookupOperatorsComponent(BloomerpComponentTestCase):
    """Tests function `workspace_filters_lookup_operators` from `bloomerp/components/workspaces/filters.py`."""

    view_name = 'components_workspaces_filters_lookup_operators'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
