# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestFilterWorkspaceComponent(BloomerpComponentTestCase):
    """Tests function `filter_workspace` from `bloomerp/components/workspaces/filters.py`."""

    view_name = 'components_filter_workspace'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
