# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestShareWorkspaceComponent(BloomerpComponentTestCase):
    """Tests function `share_workspace` from `bloomerp/components/workspaces/share_workspace.py`."""

    view_name = 'components_workspaces_share_workspace'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
