# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestEditWorkspaceComponent(BloomerpComponentTestCase):
    """Tests function `edit_workspace` from `bloomerp/components/workspaces/edit_workspace.py`."""

    view_name = 'components_workspaces_edit_workspace'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
