# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpE2ETestCase,
    E2EAction,
    E2ERequestScenario,
)


class TestObjectTodosViewE2E(BloomerpE2ETestCase):
    """Tests class `ObjectTodosView` from `bloomerp/views/generic/detail/todos.py`."""

    view_name = 'todos'

    def get_test_scenarios(self) -> list[E2ERequestScenario]:
        # Add only the browser scenarios this view needs.
        return []
