# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpE2ETestCase,
    E2EAction,
    E2ERequestScenario,
)


class TestBloomerpCreateViewE2E(BloomerpE2ETestCase):
    """Tests class `BloomerpCreateView` from `bloomerp/views/generic/model/create.py`."""

    view_name = 'add'

    def get_test_scenarios(self) -> list[E2ERequestScenario]:
        # Add only the browser scenarios this view needs.
        return []
