# Generated by manage.py generate_test_cases.
from urllib.parse import parse_qs, urlsplit

from django.contrib.contenttypes.models import ContentType
from django.core.files.uploadedfile import SimpleUploadedFile
from playwright.sync_api import Locator, Request, expect

from bloomerp.models.files.file import File
from bloomerp.models.users.user_list_view_preference import (
    UserListViewPreference,
)
from bloomerp.tests.base import (
    BloomerpE2ETestCase,
    E2EAction,
    E2ERequestScenario,
)
from bloomerp.tests.base.e2e_test_case import E2EValidator


class TestBloomerpFileListViewE2E(BloomerpE2ETestCase):
    """Tests class `BloomerpFileListView` from `bloomerp/views/generic/model/file_list.py`."""
    create_foreign_models = True
    view_name = "app"

    def folder_row(self, name: str) -> Locator:
        """Return the file-browser row for one exactly named folder."""
        return self.page.locator(
            '[bloomerp-component="file-browser"] [data-item-type="folder"]'
        ).filter(has=self.page.get_by_text(name, exact=True))

    def click_folder(
        self,
        name: str,
        validators: E2EValidator | list[E2EValidator] | None = None,
    ) -> E2EAction:
        """Return an action that opens a folder and awaits its refreshed view."""

        def execute() -> None:
            folder_row = self.folder_row(name)
            folder_id = folder_row.get_attribute("data-folder-id")
            self.assertIsNotNone(folder_id)
            folder_row.click()
            expect(
                self.page.locator('[bloomerp-component="file-browser"]')
            ).to_have_attribute("data-current-folder-id", folder_id)
            self.assertEqual(
                parse_qs(urlsplit(self.page.url).query).get("folder_id"),
                [folder_id],
            )
            data_url = self.page.locator(
                '[bloomerp-component="dataview-container"]'
            ).get_attribute("data-url")
            self.assertIsNotNone(data_url)
            self.assertEqual(
                parse_qs(urlsplit(data_url).query).get("folder_id"),
                [folder_id],
            )

        return E2EAction(
            execute=execute,
            validators=validators,
            name=f"Open folder {name!r}",
        )

    def upload_file_to_current_folder(self) -> E2EAction:
        """Upload through the toolbar and keep the active folder as target."""

        def execute() -> None:
            upload_input = self.page.locator("[data-file-browser-upload-input]")
            with self.page.expect_response(
                lambda response: response.request.method == "POST"
                and "/components/files/upload/" in response.url
            ) as response_info:
                upload_input.set_input_files(
                    {
                        "name": "toolbar-upload.txt",
                        "mimeType": "text/plain",
                        "buffer": b"Uploaded from the File Browser toolbar",
                    }
                )

            self.assertTrue(response_info.value.ok)
            expect(self.page.get_by_text("toolbar-upload.txt", exact=True)).to_be_visible()
            uploaded_file = File.objects.get(name="toolbar-upload.txt")
            self.assertEqual(uploaded_file.folder_id, self.customer_folder.id)

        return E2EAction(
            execute=execute,
            name="Upload a file into the current folder",
        )

    def create_sample_files(self) -> None:
        """Create an object with two files and its automatic folder hierarchy."""
        planet = self.PlanetModel.objects.create(
            name="Earth"
        )

        country = self.CountryModel.objects.create(
            name="Belgium",
            planet=planet
        )

        self.sample_customer = self.CustomerModel.objects.create(
            first_name="John",
            last_name="Doe",
            age=30,
        )

        self.sample_files = File.upload_files_to_object(
            self.sample_customer,
            [
                SimpleUploadedFile(
                    "sample.pdf",
                    b"%PDF-1.4\n",
                    content_type="application/pdf",
                ),
                SimpleUploadedFile(
                    "sample.txt",
                    b"Sample text",
                    content_type="text/plain",
                ),
            ],
        )

        File.upload_files_to_object(
            country,
            [
                SimpleUploadedFile(
                    "sample.txt",
                    b"Sample text",
                    content_type="text/plain",
                )
            ]
        )

        self.customer_folder = self.sample_files[0].folder
        self.customers_folder = self.customer_folder.parent
        self.folder_request_ids: list[str] = []
        self.page.on("request", self.record_folder_request)
        self.file_browser_preference = UserListViewPreference.objects.create(
            user=self.admin_user,
            content_type=ContentType.objects.get_for_model(File),
            selected=True,
            view_type="file_browser",
        )

    def cleanup_sample_files(self) -> None:
        """Remove uploaded test files from storage after the scenario."""
        self.page.remove_listener("request", self.record_folder_request)
        for file in getattr(self, "sample_files", []):
            file.delete()
        for file in File.objects.filter(name="toolbar-upload.txt"):
            file.delete()
        preference = getattr(self, "file_browser_preference", None)
        if preference is not None:
            preference.delete()
        customer = getattr(self, "sample_customer", None)
        if customer is not None:
            customer.delete()

    def contains_folder(self, names: list[str]) -> E2EValidator:
        """Return an assertion that every named folder is currently visible."""

        def validator() -> None:
            for name in names:
                expect(self.folder_row(name)).to_be_visible()

        return validator

    def record_folder_request(self, request: Request) -> None:
        """Record each file-browser XHR folder target."""
        if request.resource_type not in {"xhr", "fetch"}:
            return
        folder_ids = parse_qs(urlsplit(request.url).query).get("folder_id")
        if folder_ids:
            self.folder_request_ids.extend(folder_ids)

    def is_in_customers_folder(self) -> E2EValidator:
        """Assert the final request and rendered folder are the model folder."""

        def validator() -> None:
            expected_folder_id = str(self.customers_folder.pk)
            file_browser = self.page.locator(
                '[bloomerp-component="file-browser"]'
            )
            expect(file_browser).to_be_visible()
            self.assertTrue(self.folder_request_ids)
            self.assertEqual(
                self.folder_request_ids[-1],
                expected_folder_id,
                f"folder requests: {self.folder_request_ids}; page URL: {self.page.url}",
            )
            expect(file_browser).to_have_attribute(
                "data-current-folder-id",
                expected_folder_id,
            )

        return validator

    def get_test_scenarios(self) -> list[E2ERequestScenario]:
        # Add only the browser scenarios this view needs.
        return [
            E2ERequestScenario(
                name="Back refresh preserves previous folder structure",
                user=self.admin_user,
                url="/files",
                actions=[
                    self.click_folder("Miscellaneous"),
                    self.click_folder("customers"),
                    self.click_folder("John Doe"),
                    self.back_refresh(
                        validators=[
                            self.is_in_customers_folder(),
                            self.contains_folder(["John Doe"]),
                        ]
                    ),
                ],
                prepare=self.create_sample_files,
                cleanup=self.cleanup_sample_files,
            ),
            E2ERequestScenario(
                name="Toolbar upload targets the current folder",
                user=self.admin_user,
                url="/files",
                actions=[
                    self.click_folder("Miscellaneous"),
                    self.click_folder("customers"),
                    self.click_folder("John Doe"),
                    self.upload_file_to_current_folder(),
                ],
                prepare=self.create_sample_files,
                cleanup=self.cleanup_sample_files,
            ),
        ]
