# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpE2ETestCase,
    E2EAction,
    E2ERequestScenario,
)


class TestBloomerpBulkUploadViewE2E(BloomerpE2ETestCase):
    """Tests class `BloomerpBulkUploadView` from `bloomerp/views/generic/model/bulk_upload.py`."""

    view_name = 'bulk_upload'

    def get_test_scenarios(self) -> list[E2ERequestScenario]:
        # Add only the browser scenarios this view needs.
        return []
