# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpE2ETestCase,
    E2EAction,
    E2ERequestScenario,
)


class TestUserAdminPasswordResetViewE2E(BloomerpE2ETestCase):
    """Tests class `UserAdminPasswordResetView` from `bloomerp/views/users/admin_reset_password.py`."""

    view_name = 'admin_reset_password_for_user'

    def get_test_scenarios(self) -> list[E2ERequestScenario]:
        # Add only the browser scenarios this view needs.
        return []
