# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpE2ETestCase,
    E2EAction,
    E2ERequestScenario,
)


class TestUpdateTileViewE2E(BloomerpE2ETestCase):
    """Tests class `UpdateTileView` from `bloomerp/views/workspaces/update_tile.py`."""

    view_name = 'Update Tile'

    def get_test_scenarios(self) -> list[E2ERequestScenario]:
        # Add only the browser scenarios this view needs.
        return []
