# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpE2ETestCase,
    E2EAction,
    E2ERequestScenario,
)
from bloomerp.tests.e2e.mixins.filters_e2e_mixin import FilterE2EMixin


class TestBloomerpHomeViewE2E(BloomerpE2ETestCase, FilterE2EMixin):
    """Tests class `BloomerpHomeView` from `bloomerp/views/workspaces/home.py`."""

    def get_test_scenarios(self) -> list[E2ERequestScenario]:
        # Add only the browser scenarios this view needs.
        
        field = ""
        
        return [
            E2ERequestScenario(
                name="User can click and filter tiles",
                user=self.admin_user,
                actions=[
                    self.click_filter,
                    self.select_filter_field(
                        field=field,
                        level=0       
                    ),
                    self.select_filter_lookup(
                        lookup_id="equals",
                        level=0
                    ),
                    self.set_filter_value(
                        value="David",
                        level=0
                    ),
                    self.apply_filters(
                        validators=...
                    )   
                ]
            ),
        ]
