# Generated by manage.py generate_test_cases.
import json

from django.contrib.auth.models import Permission

from bloomerp.tests.base import (
    BloomerpAPIViewTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestExecuteSqlView(BloomerpAPIViewTestCase):
    """Tests class `ExecuteSqlView` from `bloomerp/views/api/sql/execute.py`."""

    view_name = 'api_sql_execute'

    def get_test_scenarios(self) -> list[RequestScenario]:
        table = self.CustomerModel._meta.db_table
        return [
            RequestScenario(
                name="Permitted user can execute a paginated read-only query",
                description=(
                    "UC: A permitted user executes a safe SELECT query.\n"
                    "Expected Result: The API returns typed rows, columns, and pagination metadata."
                ),
                method="POST",
                user=self.admin_user,
                content_type="application/json",
                data=json.dumps(
                    {
                        "query": f"SELECT first_name FROM {table} ORDER BY first_name",
                        "page_size": 3,
                    }
                ),
                expected=ExpectedResult(response_validators=self.query_result_is_paginated),
            ),
            RequestScenario(
                name="SQL execution requires permission",
                description=(
                    "UC: An authenticated user without SQL execution permission posts a query.\n"
                    "Expected Result: The API denies the request before executing SQL."
                ),
                method="POST",
                user=self.normal_user,
                content_type="application/json",
                data=json.dumps({"query": f"SELECT first_name FROM {table}"}),
                expected=ExpectedResult(
                    status_code=403,
                    response_validators=self.json_exact(
                        {"error": f"You do not have access to table: {table}"}
                    ),
                ),
            ),
            RequestScenario(
                name="SQL execution rejects write statements",
                description=(
                    "UC: A permitted user posts a DELETE statement.\n"
                    "Expected Result: The read-only safety check rejects it."
                ),
                method="POST",
                user=self.normal_user,
                content_type="application/json",
                data=json.dumps({"query": f"DELETE FROM {table}"}),
                prepare=self.grant_sql_permission,
                expected=ExpectedResult(
                    status_code=400,
                    response_validators=lambda response: (
                        "Only safe read-only SELECT/WITH queries are allowed"
                        in response.json().get("error", "")
                    ),
                ),
            ),
            RequestScenario(
                name="SQL execution rejects GET",
                description=(
                    "UC: A permitted user calls the execution endpoint with GET.\n"
                    "Expected Result: Only POST is allowed."
                ),
                method="GET",
                user=self.normal_user,
                prepare=self.grant_sql_permission,
                expected=ExpectedResult(status_code=405),
            ),
        ]

    def grant_sql_permission(self, _scenario):
        permission = Permission.objects.get(codename="execute_sql_query")
        self.normal_user.user_permissions.add(permission)

    @staticmethod
    def query_result_is_paginated(response):
        payload = response.json()
        return (
            payload.get("columns") == ["first_name"]
            and payload.get("page_rows_count") == 3
            and payload.get("row_count") == 10
            and payload.get("page") == 1
            and payload.get("page_size") == 3
            and payload.get("rows", [None])[0] == {"first_name": "Alice"}
            and "icon" not in payload["output_fields"]["fields"][0]
        )
