# Generated by manage.py generate_test_cases.
from bloomerp.models.users.user import User
from django.urls import reverse
from bloomerp.tests.base import (
    BloomerpModelViewTestCase,
    ExpectedResult,
    RequestScenario,
    ModelRequestScenario,
)


class TestBloomerpProfileView(BloomerpModelViewTestCase):
    """Tests class `BloomerpProfileView` from `bloomerp/views/users/profile.py`."""

    view_name = 'my_profile_overview'
    model = User

    def get_test_scenarios(self) -> list[RequestScenario]:
        """Keep scenario generation empty for this focused profile test."""
        # Add only the route scenarios this callable needs.
        return []

    def test_profile_layout_renders_and_updates_only_profile_fields(self) -> None:
        """Render editable ApplicationFields and save only the user's profile."""
        self.client.force_login(self.normal_user)
        url = reverse("users_my_profile_overview")
        original_staff_status = self.normal_user.is_staff

        response = self.client.get(url)
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'name="first_name"')
        self.assertContains(response, 'name="last_name"')
        self.assertContains(response, 'name="date_view_preference"')
        self.assertContains(response, 'name="datetime_view_preference"')
        self.assertNotContains(response, 'name="is_staff"')

        response = self.client.post(url, {
            "first_name": "Ada",
            "last_name": "Lovelace",
            "date_view_preference": "Y-m-d",
            "datetime_view_preference": "Y-m-d H:i",
            "is_staff": "false" if original_staff_status else "on",
        })
        self.assertEqual(response.status_code, 302)
        self.normal_user.refresh_from_db()
        self.assertEqual(self.normal_user.first_name, "Ada")
        self.assertEqual(self.normal_user.last_name, "Lovelace")
        self.assertEqual(self.normal_user.date_view_preference, "Y-m-d")
        self.assertEqual(self.normal_user.datetime_view_preference, "Y-m-d H:i")
        self.assertEqual(self.normal_user.is_staff, original_staff_status)

        response = self.client.post(url, {
            "first_name": "Ada",
            "last_name": "Lovelace",
            "date_view_preference": "invalid-format",
            "datetime_view_preference": "Y-m-d H:i",
        })
        self.assertEqual(response.status_code, 200)
        self.assertIn("date_view_preference", response.context["form"].errors)
