# Generated by manage.py generate_test_cases.
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from django.core.files.base import ContentFile

from bloomerp.models.files.file import (
    BulkUploadFileMetadata,
    DocumentTemplateFileMetadata,
    File,
    FileMetadata,
)
from bloomerp.models.files.file_folder import FileFolder
from bloomerp.modules.misc import MiscModule
from bloomerp.services.file_services import (
    ensure_folder_hierarchy_for_object,
    get_model_folder_scope_key,
    get_module_folder_scope_key,
    get_object_folder_scope_key,
)
from bloomerp.tests.base import (
    BaseBloomerpTestCaseWithModels,
    BloomerpModelTestCase,
    ExpectedModelException,
    ModelScenario,
)


class TestFileModel(BloomerpModelTestCase, BaseBloomerpTestCaseWithModels):
    model = File

    def get_test_scenarios(self) -> list[ModelScenario[File]]:
        """Cover file folder lifecycle and typed metadata persistence."""
        return [
            ModelScenario(
                name="Typed document provenance is saved as JSON",
                create_operation=self.create_document_file,
                create_validators=self.document_metadata_is_valid,
            ),
            ModelScenario(
                name="Legacy bulk draft metadata normalizes on save",
                create_operation=self.create_legacy_bulk_file,
                create_validators=self.bulk_metadata_is_valid,
            ),
            ModelScenario(
                name="Unknown metadata keys are rejected",
                create_operation=self.create_invalid_metadata_file,
                expected_exceptions=[
                    ExpectedModelException(phase="create", exception=ValidationError)
                ],
            ),
            ModelScenario(
                name="File without an object creates no folder hierarchy",
                description=(
                    "UC: A user uploads a file without attaching it to an object.\n"
                    "Expected Result: No automatic file folders are created."
                ),
                create_operation=lambda: self.create_file(),
                create_validators=lambda _file: not FileFolder.objects.exists(),
            ),
            ModelScenario(
                name="File attached to an object creates protected hierarchy",
                description=(
                    "UC: A file is attached to a model object.\n"
                    "Expected Result: Protected object, model, and module folders are created."
                ),
                create_operation=self.create_attached_file,
                create_validators=self.protected_hierarchy_exists,
            ),
            ModelScenario(
                name="Generated model folder identity ignores display name",
                description=(
                    "UC: A model folder already exists under an older translated display name.\n"
                    "Expected Result: Hierarchy synchronization reuses it instead of creating a duplicate."
                ),
                create_operation=self.synchronize_existing_model_folder,
                create_validators=self.existing_model_folder_was_reused,
            ),
            ModelScenario(
                name="Renamed object keeps its generated folder",
                description=(
                    "UC: An object's display name changes after its folder exists.\n"
                    "Expected Result: The same folder is renamed instead of duplicated."
                ),
                create_operation=self.synchronize_renamed_object_folder,
                create_validators=self.renamed_object_folder_was_reused,
            ),
        ]

    def create_file(self, *, obj=None):
        return File.objects.create(
            name="test_file.txt",
            file=ContentFile(b"Test content", name="test_file.txt"),
            content_type=ContentType.objects.get_for_model(obj) if obj else None,
            object_id=obj.pk if obj else None,
            created_by=self.admin_user,
            updated_by=self.admin_user,
        )

    def create_attached_file(self):
        self.customer = self.CustomerModel.objects.first()
        return self.create_file(obj=self.customer)

    def protected_hierarchy_exists(self, _file):
        content_type = ContentType.objects.get_for_model(self.customer)
        object_folder = FileFolder.objects.filter(
            kind=FileFolder.Kind.OBJECT,
            scope_key=get_object_folder_scope_key(content_type, self.customer.pk),
        ).first()
        model_folder = FileFolder.objects.filter(
            kind=FileFolder.Kind.MODEL,
            scope_key=get_model_folder_scope_key(content_type),
        ).first()
        module_folder = FileFolder.objects.filter(
            kind=FileFolder.Kind.MODULE,
            scope_key=get_module_folder_scope_key(MiscModule(), content_type),
        ).first()
        return (
            object_folder is not None
            and object_folder.object_id == str(self.customer.pk)
            and model_folder is not None
            and module_folder is not None
            and all(
                folder.protected
                for folder in [object_folder, model_folder, module_folder]
            )
        )

    def synchronize_existing_model_folder(self):
        self.customer = self.CustomerModel.objects.first()
        self.customer_content_type = ContentType.objects.get_for_model(self.customer)
        self.existing_folder = FileFolder.objects.create(
            name="Previously translated customers",
            kind=FileFolder.Kind.MODEL,
            scope_key=get_model_folder_scope_key(self.customer_content_type),
            content_type=self.customer_content_type,
            protected=True,
        )
        ensure_folder_hierarchy_for_object(self.customer)
        return self.existing_folder

    def existing_model_folder_was_reused(self, existing_folder):
        model_folders = FileFolder.objects.filter(
            kind=FileFolder.Kind.MODEL,
            scope_key=get_model_folder_scope_key(self.customer_content_type),
        )
        model_folder = model_folders.get()
        return (
            model_folders.count() == 1
            and model_folder == existing_folder
            and model_folder.name == self.CustomerModel._meta.verbose_name_plural
            and model_folder.parent.kind == FileFolder.Kind.MODULE
        )

    def synchronize_renamed_object_folder(self):
        self.customer = self.CustomerModel.objects.first()
        self.customer_content_type = ContentType.objects.get_for_model(self.customer)
        object_folder = ensure_folder_hierarchy_for_object(self.customer)
        self.original_object_folder_id = object_folder.pk
        self.customer.first_name = "Renamed"
        self.customer.last_name = "Customer"
        self.customer.save()
        return ensure_folder_hierarchy_for_object(self.customer)

    def renamed_object_folder_was_reused(self, object_folder):
        scope_key = get_object_folder_scope_key(
            self.customer_content_type,
            self.customer.pk,
        )
        return (
            object_folder.pk == self.original_object_folder_id
            and object_folder.name == "Renamed Customer"
            and FileFolder.objects.filter(scope_key=scope_key).count() == 1
        )

    def create_document_file(self) -> File:
        """Save a generated file with typed document-template provenance."""
        from uuid import UUID

        return File.objects.create(
            file=ContentFile(b"pdf", name="report.pdf"),
            meta=FileMetadata(
                document_template=DocumentTemplateFileMetadata(
                    id=UUID("12345678-1234-5678-1234-567812345678"), name="Report"
                ),
            ),
        )

    def document_metadata_is_valid(self, file: File) -> bool:
        """Check nested provenance survives a fresh database read."""
        file.refresh_from_db()
        return (
            file.metadata.document_template.name == "Report"
            and "document_template_id" not in file.meta
        )

    def create_legacy_bulk_file(self) -> File:
        """Save a historical bulk-upload JSON payload through the new validation path."""
        return File.objects.create(
            file=ContentFile(b"csv", name="import.csv"),
            meta={
                "bulk_upload_draft": True,
                "content_type_id": 1,
                "model_label": "bloomerp.customer",
                "original_filename": "import.csv",
                "upload_type": "bulk_upload",
            },
        )

    def bulk_metadata_is_valid(self, file: File) -> bool:
        """Check typed bulk metadata replaces the flat draft keys."""
        file.refresh_from_db()
        return (
            isinstance(file.metadata.bulk_upload, BulkUploadFileMetadata)
            and file.metadata.bulk_upload.original_filename == "import.csv"
            and "bulk_upload_draft" not in file.meta
        )

    def create_invalid_metadata_file(self) -> File:
        """Attempt to persist unsupported metadata without saving uploaded bytes."""
        return File.objects.create(
            file=ContentFile(b"invalid", name="invalid.txt"), meta={"unknown": True}
        )

    def test_metadata_migration_round_trip(self) -> None:
        """
        Use case: Existing files contain flat document and bulk-upload provenance.
        Expected result: Migration is idempotent and reversal restores the original JSON.
        """
        from importlib import import_module
        from types import SimpleNamespace

        from django.apps import apps
        from django.db import connection

        # 1. Seed historical JSON without running the current save normalizer.
        document = self.create_file()
        draft = self.create_file()
        document_meta = {
            "document_template_id": "12345678-1234-5678-1234-567812345678",
            "document_template_name": "Report",
        }
        bulk_meta = {
            "bulk_upload_draft": True,
            "content_type_id": 1,
            "model_label": "bloomerp.customer",
            "original_filename": "import.csv",
            "upload_type": "bulk_upload",
        }
        File.objects.filter(pk=document.pk).update(meta=document_meta)
        File.objects.filter(pk=draft.pk).update(meta=bulk_meta)
        migration = import_module("bloomerp.migrations.0077_file_field_references")
        editor = SimpleNamespace(connection=connection)

        # 2. Run forward twice and verify nested metadata remains valid.
        migration.migrate_metadata(apps, editor)
        migration.migrate_metadata(apps, editor)
        document.refresh_from_db()
        draft.refresh_from_db()
        self.assertEqual(document.metadata.document_template.name, "Report")
        self.assertEqual(draft.metadata.bulk_upload.original_filename, "import.csv")

        # 3. Reverse and verify both historical payloads are restored.
        migration.restore_metadata(apps, editor)
        document.refresh_from_db()
        draft.refresh_from_db()
        self.assertEqual(document.meta, document_meta)
        self.assertEqual(draft.meta, bulk_meta)
