# Generated by manage.py generate_test_cases.
from django.contrib.contenttypes.models import ContentType
from django.core.files.base import ContentFile

from bloomerp.models.files.file import File
from bloomerp.models.files.file_folder import FileFolder
from bloomerp.modules.misc import MiscModule
from bloomerp.services.file_services import ensure_folder_hierarchy_for_object
from bloomerp.tests.base import (
    BaseBloomerpTestCaseWithModels,
    BloomerpModelTestCase,
    ModelScenario,
    ExpectedModelException,
)


class TestFileModel(BloomerpModelTestCase, BaseBloomerpTestCaseWithModels):
    model = File

    def get_test_scenarios(self) -> list[ModelScenario[File]]:
        return [
            ModelScenario(
                name="File without an object creates no folder hierarchy",
                description=(
                    "UC: A user uploads a file without attaching it to an object.\n"
                    "Expected Result: No automatic file folders are created."
                ),
                create_operation=lambda: self.create_file(),
                create_validators=lambda _file: not FileFolder.objects.exists(),
            ),
            ModelScenario(
                name="File attached to an object creates protected hierarchy",
                description=(
                    "UC: A file is attached to a model object.\n"
                    "Expected Result: Protected object, model, and module folders are created."
                ),
                create_operation=self.create_attached_file,
                create_validators=self.protected_hierarchy_exists,
            ),
            ModelScenario(
                name="Generated model folder identity ignores display name",
                description=(
                    "UC: A model folder already exists under an older translated display name.\n"
                    "Expected Result: Hierarchy synchronization reuses it instead of creating a duplicate."
                ),
                create_operation=self.synchronize_existing_model_folder,
                create_validators=self.existing_model_folder_was_reused,
            ),
        ]

    def create_file(self, *, obj=None):
        return File.objects.create(
            name="test_file.txt",
            file=ContentFile(b"Test content", name="test_file.txt"),
            content_type=ContentType.objects.get_for_model(obj) if obj else None,
            object_id=obj.pk if obj else None,
            created_by=self.admin_user,
            updated_by=self.admin_user,
        )

    def create_attached_file(self):
        self.customer = self.CustomerModel.objects.first()
        return self.create_file(obj=self.customer)

    def protected_hierarchy_exists(self, _file):
        content_type = ContentType.objects.get_for_model(self.customer)
        object_folder = FileFolder.objects.filter(
            content_type=content_type,
            object_id=str(self.customer.pk),
        ).first()
        model_folder = FileFolder.objects.filter(
            content_type=content_type,
            object_id__isnull=True,
        ).first()
        module_folder = FileFolder.objects.filter(
            name=MiscModule().name,
            content_type__isnull=True,
            object_id__isnull=True,
        ).first()
        return (
            object_folder is not None
            and object_folder.object_id == str(self.customer.pk)
            and model_folder is not None
            and module_folder is not None
            and all(folder.protected for folder in [object_folder, model_folder, module_folder])
        )

    def synchronize_existing_model_folder(self):
        self.customer = self.CustomerModel.objects.first()
        self.customer_content_type = ContentType.objects.get_for_model(self.customer)
        self.existing_folder = FileFolder.objects.create(
            name="Previously translated customers",
            content_type=self.customer_content_type,
            protected=True,
        )
        ensure_folder_hierarchy_for_object(self.customer)
        return self.existing_folder

    def existing_model_folder_was_reused(self, existing_folder):
        model_folders = FileFolder.objects.filter(
            content_type=self.customer_content_type,
            object_id__isnull=True,
        )
        return model_folders.count() == 1 and model_folders.get() == existing_folder
