# Generated by manage.py generate_test_cases.
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError

from bloomerp.models.files.file import File
from bloomerp.models.files.file_folder import FileFolder
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ExpectedModelException,
    ModelScenario,
)


class TestFileFolderModel(BloomerpModelTestCase):
    model = FileFolder

    def get_test_scenarios(self) -> list[ModelScenario[FileFolder]]:
        return [
            ModelScenario(
                name="Manual folder has no system identity",
                create_args={"name": "Contracts"},
                create_validators=lambda folder: (
                    folder.kind == FileFolder.Kind.MANUAL
                    and folder.scope_key is None
                ),
            ),
            ModelScenario(
                name="System folder requires a scope key",
                create_args={
                    "name": "Customers",
                    "kind": FileFolder.Kind.MODEL,
                },
                expected_exceptions=[
                    ExpectedModelException(
                        phase="create",
                        exception=ValidationError,
                    )
                ],
            ),
            ModelScenario(
                name="Manual folder rejects a scope key",
                create_args={
                    "name": "Contracts",
                    "scope_key": "manual:contracts",
                },
                expected_exceptions=[
                    ExpectedModelException(
                        phase="create",
                        exception=ValidationError,
                    )
                ],
            ),
            ModelScenario(
                name="System folder scope key is unique",
                preparation=lambda: FileFolder.objects.create(
                    name="Customers",
                    kind=FileFolder.Kind.MODEL,
                    scope_key="model:tests.customer",
                ),
                create_args={
                    "name": "Other customers",
                    "kind": FileFolder.Kind.MODEL,
                    "scope_key": "model:tests.customer",
                },
                expected_exceptions=[
                    ExpectedModelException(
                        phase="create",
                        exception=ValidationError,
                    )
                ],
            ),
            ModelScenario(
                name="System folder identity is immutable",
                create_args={
                    "name": "Customers",
                    "kind": FileFolder.Kind.MODEL,
                    "scope_key": "model:tests.customer",
                },
                post_create=lambda folder: setattr(
                    folder,
                    "scope_key",
                    "model:tests.renamed_customer",
                ),
                update_args={},
                expected_exceptions=[
                    ExpectedModelException(
                        phase="update",
                        exception=ValidationError,
                    )
                ],
            ),
            ModelScenario(
                name="File folder requires a content type when it has an object ID",
                create_args={"name": "Object folder", "object_id": "1"},
                expected_exceptions=[
                    ExpectedModelException(
                        phase="create",
                        exception=ValidationError,
                    )
                ],
            ),
            ModelScenario(
                name="Child file folder inherits its parent's content type",
                preparation=lambda: setattr(
                    self,
                    "parent_folder",
                    FileFolder.objects.create(
                        name="Parent Folder",
                        content_type=ContentType.objects.get_for_model(File),
                        object_id="parent-object",
                    ),
                ),
                create_args=lambda: {
                    "name": "Child Folder",
                    "parent": self.parent_folder,
                    "content_type": ContentType.objects.get_for_model(FileFolder),
                    "object_id": self.parent_folder.object_id,
                },
                expected_exceptions=[
                    ExpectedModelException(
                        phase="create",
                        exception=ValidationError,
                    )
                ],
            ),
            ModelScenario(
                name="Child file folder inherits its parent's object ID",
                preparation=lambda: setattr(
                    self,
                    "parent_folder",
                    FileFolder.objects.create(
                        name="Parent Folder",
                        content_type=ContentType.objects.get_for_model(File),
                        object_id="parent-object",
                    ),
                ),
                create_args=lambda: {
                    "name": "Child Folder",
                    "parent": self.parent_folder,
                    "content_type": self.parent_folder.content_type,
                    "object_id": "different-object",
                },
                expected_exceptions=[
                    ExpectedModelException(
                        phase="create",
                        exception=ValidationError,
                    )
                ],
            ),
            ModelScenario(
                name="Child file folder accepts inherited object identity",
                preparation=lambda: setattr(
                    self,
                    "parent_folder",
                    FileFolder.objects.create(
                        name="Parent Folder",
                        content_type=ContentType.objects.get_for_model(File),
                        object_id="parent-object",
                    ),
                ),
                create_args=lambda: {
                    "name": "Child Folder",
                    "parent": self.parent_folder,
                    "content_type": self.parent_folder.content_type,
                    "object_id": self.parent_folder.object_id,
                },
                create_validators=lambda folder: (
                    folder.parent_id == self.parent_folder.pk
                    and folder.content_type_id == self.parent_folder.content_type_id
                    and folder.object_id == self.parent_folder.object_id
                ),
            ),
        ]
