# Generated by manage.py generate_test_cases.
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError

from bloomerp.models.files.file import File
from bloomerp.models.files.file_folder import FileFolder
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ExpectedModelException,
    ModelScenario,
)


class TestFileFolderModel(BloomerpModelTestCase):
    model = FileFolder

    def get_test_scenarios(self) -> list[ModelScenario[FileFolder]]:
        return [
            ModelScenario(
                name="File folder requires a content type when it has an object ID",
                create_args={"name": "Object folder", "object_id": "1"},
                expected_exceptions=[
                    ExpectedModelException(
                        phase="create",
                        exception=ValidationError,
                    )
                ],
            ),
            ModelScenario(
                name="Child file folder inherits its parent's content type",
                preparation=lambda: setattr(
                    self,
                    "parent_folder",
                    FileFolder.objects.create(
                        name="Parent Folder",
                        content_type=ContentType.objects.get_for_model(File),
                        object_id="parent-object",
                    ),
                ),
                create_args=lambda: {
                    "name": "Child Folder",
                    "parent": self.parent_folder,
                    "content_type": ContentType.objects.get_for_model(FileFolder),
                    "object_id": self.parent_folder.object_id,
                },
                expected_exceptions=[
                    ExpectedModelException(
                        phase="create",
                        exception=ValidationError,
                    )
                ],
            ),
            ModelScenario(
                name="Child file folder inherits its parent's object ID",
                preparation=lambda: setattr(
                    self,
                    "parent_folder",
                    FileFolder.objects.create(
                        name="Parent Folder",
                        content_type=ContentType.objects.get_for_model(File),
                        object_id="parent-object",
                    ),
                ),
                create_args=lambda: {
                    "name": "Child Folder",
                    "parent": self.parent_folder,
                    "content_type": self.parent_folder.content_type,
                    "object_id": "different-object",
                },
                expected_exceptions=[
                    ExpectedModelException(
                        phase="create",
                        exception=ValidationError,
                    )
                ],
            ),
            ModelScenario(
                name="Child file folder accepts inherited object identity",
                preparation=lambda: setattr(
                    self,
                    "parent_folder",
                    FileFolder.objects.create(
                        name="Parent Folder",
                        content_type=ContentType.objects.get_for_model(File),
                        object_id="parent-object",
                    ),
                ),
                create_args=lambda: {
                    "name": "Child Folder",
                    "parent": self.parent_folder,
                    "content_type": self.parent_folder.content_type,
                    "object_id": self.parent_folder.object_id,
                },
                create_validators=lambda folder: (
                    folder.parent_id == self.parent_folder.pk
                    and folder.content_type_id == self.parent_folder.content_type_id
                    and folder.object_id == self.parent_folder.object_id
                ),
            ),
        ]
