# Generated by manage.py generate_test_cases.
from bloomerp.models.communication.inbox.user_inbox_preference import UserInboxPreference
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
    ExpectedModelException,
)


class TestUserInboxPreferenceModel(BloomerpModelTestCase):
    model = UserInboxPreference

    def get_test_scenarios(self) -> list[ModelScenario[UserInboxPreference]]:
        # Add only the scenarios this class needs.
        return []
