# Generated by manage.py generate_test_cases.
from bloomerp.models.communication.inbox.inbox_item import InboxItem
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
)


class TestInboxItemModel(BloomerpModelTestCase):
    model = InboxItem

    def get_test_scenarios(self) -> list[ModelScenario[InboxItem]]:
        # Add only the scenarios this class needs.
        return []
