# Generated by manage.py generate_test_cases.
from bloomerp.models.communication.inbox.inbox_folder import InboxFolder
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
    ExpectedModelException,
)


class TestInboxFolderModel(BloomerpModelTestCase):
    model = InboxFolder

    def get_test_scenarios(self) -> list[ModelScenario[InboxFolder]]:
        # Add only the scenarios this class needs.
        return []
