# Generated by manage.py generate_test_cases.
from bloomerp.model_fields.status_field import StatusField
from bloomerp.tests.base import (
    BloomerpModelFieldTestCase,
    ModelFieldScenario,
)


class TestStatusField(BloomerpModelFieldTestCase):
    field_class = StatusField

    def get_test_scenarios(self) -> list[ModelFieldScenario[StatusField]]:
        # Add only the scenarios this class needs.
        return []
