# Generated by manage.py generate_test_cases.
from bloomerp.model_fields.code_field import CodeField
from bloomerp.tests.base import (
    BloomerpModelFieldTestCase,
    ModelFieldScenario,
)


class TestCodeField(BloomerpModelFieldTestCase):
    field_class = CodeField

    def get_test_scenarios(self) -> list[ModelFieldScenario[CodeField]]:
        # Add only the scenarios this class needs.
        return []
