# Generated by manage.py generate_test_cases.
from bloomerp.model_fields.file_field import BloomerpFileField
from bloomerp.tests.base import (
    BloomerpModelFieldTestCase,
    ModelFieldScenario,
)


class TestBloomerpFileField(BloomerpModelFieldTestCase):
    field_class = BloomerpFileField

    def get_test_scenarios(self) -> list[ModelFieldScenario[BloomerpFileField]]:
        # Add only the scenarios this class needs.
        return []
