# Generated by manage.py generate_test_cases.
from bloomerp.model_fields.week_field import WeekField
from bloomerp.tests.base import (
    BloomerpModelFieldTestCase,
    ModelFieldScenario,
    ExpectedModelFieldException,
)


class TestWeekField(BloomerpModelFieldTestCase):
    field_class = WeekField

    def get_test_scenarios(self) -> list[ModelFieldScenario[WeekField]]:
        # Add only the scenarios this class needs.
        return [
            ModelFieldScenario(
                name="Week is stored as string",
            )
        ]
