# Generated by manage.py generate_test_cases.
from bloomerp.model_fields.user_field import UserField
from bloomerp.tests.base import (
    BloomerpModelFieldTestCase,
    ModelFieldScenario,
)


class TestUserField(BloomerpModelFieldTestCase):
    field_class = UserField

    def get_test_scenarios(self) -> list[ModelFieldScenario[UserField]]:
        # Add only the scenarios this class needs.
        return []
