# Generated by manage.py generate_test_cases.
from django.db import models

from bloomerp.model_fields.file_field import BloomerpFileField
from bloomerp.tests.base import (
    BloomerpModelFieldTestCase,
    ModelFieldScenario,
)
from bloomerp.widgets.file_field_widget import BloomerpFileFieldWidget


class TestBloomerpFileField(BloomerpModelFieldTestCase[BloomerpFileField]):
    field_class = BloomerpFileField

    def get_test_scenarios(self) -> list[ModelFieldScenario[BloomerpFileField]]:
        return [
            ModelFieldScenario(
                name="uses file relation defaults",
                construct_validators=[
                    lambda field: field.allowed_extensions == "__all__",
                    lambda field: field.null,
                    lambda field: field.blank,
                    lambda field: field.remote_field.on_delete is models.SET_NULL,
                    lambda field: isinstance(
                        field.formfield().widget,
                        BloomerpFileFieldWidget,
                    ),
                ],
                deconstruct_validators=lambda deconstruction: (
                    deconstruction[1]
                    == "bloomerp.model_fields.file_field.BloomerpFileField"
                    and deconstruction[3]["null"] is True
                    and deconstruction[3]["blank"] is True
                    and deconstruction[3]["on_delete"] is models.SET_NULL
                ),
                get_prep_value=17,
                get_prep_value_validators=lambda value: value == 17,
            ),
            ModelFieldScenario(
                name="keeps configured file extensions",
                constructor_kwargs={"allowed_extensions": [".pdf", ".docx"]},
                construct_validators=lambda field: field.allowed_extensions
                == [".pdf", ".docx"],
            ),
        ]
