# Generated by manage.py generate_test_cases.
from bloomerp.model_fields.address_field import AddressField
from bloomerp.tests.base import BloomerpModelFieldTestCase, ModelFieldScenario


class TestAddressField(BloomerpModelFieldTestCase[AddressField]):
    field_class = AddressField

    def get_test_scenarios(self) -> list[ModelFieldScenario[AddressField]]:
        return [
            ModelFieldScenario(
                name="normalizes structured address values",
                to_python_value={
                    "street_1": "  Main street 1  ",
                    "street_2": "",
                    "postal_code": " 1000 ",
                    "city": " Brussels ",
                    "state": "",
                    "country": "be",
                },
                to_python_validators=[
                    lambda value: value["street_1"] == "Main street 1",
                    lambda value: value["postal_code"] == "1000",
                    lambda value: value["country"] == "BE",
                ],
            ),
            ModelFieldScenario(
                name="prepares a normalized address mapping",
                get_prep_value={
                    "street_1": "Main street 1",
                    "street_2": "",
                    "postal_code": "1000",
                    "city": "Brussels",
                    "state": "",
                    "country": "BE",
                },
                get_prep_value_validators=lambda value: value == {
                    "street_1": "Main street 1",
                    "street_2": "",
                    "postal_code": "1000",
                    "city": "Brussels",
                    "state": "",
                    "country": "BE",
                },
            ),
            ModelFieldScenario(
                name="cleans multipart form values",
                form_clean_value=[
                    "Main street 1",
                    "",
                    "1000",
                    "Brussels",
                    "",
                    "BE",
                ],
                form_clean_validators=lambda value: value == {
                    "street_1": "Main street 1",
                    "street_2": "",
                    "postal_code": "1000",
                    "city": "Brussels",
                    "state": "",
                    "country": "BE",
                },
            ),
        ]
