# Generated by manage.py generate_test_cases.
from bloomerp.models.users.user_detail_view_tabs_preference import UserDetailViewTabsPreference
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
    ExpectedModelException,
)


class TestUserDetailViewTabsPreferenceModel(BloomerpModelTestCase):
    model = UserDetailViewTabsPreference

    def get_test_scenarios(self) -> list[ModelScenario[UserDetailViewTabsPreference]]:
        # Add only the scenarios this class needs.
        return []
