# Generated by manage.py generate_test_cases.
from django.contrib.contenttypes.models import ContentType

from bloomerp.models.project_management.todo import Todo
from bloomerp.models.users.user_detail_view_tabs_preference import UserDetailViewTabsPreference
from bloomerp.services.preference_services import PreferenceManager
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
)
from bloomerp.tests.utils.users import create_admin


class TestUserDetailViewTabsPreferenceModel(BloomerpModelTestCase):
    model = UserDetailViewTabsPreference

    def setUp(self):
        super().setUp()
        self.user = create_admin()
        self.content_type = ContentType.objects.get_for_model(Todo)

    def get_test_scenarios(self) -> list[ModelScenario[UserDetailViewTabsPreference]]:
        return [
            ModelScenario(
                name="Existing detail tabs preference remains selectable",
                description=(
                    "UC: A user opens a detail page with an existing tabs preference.\n"
                    "Expected Result: The preference manager returns that selection "
                    "without requiring an object-layout repair hook."
                ),
                create_operation=self.get_existing_selection,
                create_validators=lambda preference: (
                    preference.user == self.user
                    and preference.content_type == self.content_type
                    and preference.selected
                ),
            )
        ]

    def get_existing_selection(self) -> UserDetailViewTabsPreference:
        expected = UserDetailViewTabsPreference.objects.create(
            user=self.user,
            content_type=self.content_type,
            selected=True,
        )
        selected = PreferenceManager(self.user).get_or_create_selected(
            UserDetailViewTabsPreference,
            scope={"content_type_id": self.content_type.pk},
        )
        self.assertEqual(selected, expected)
        return selected
