# Generated by manage.py generate_test_cases.
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import override

from bloomerp.models.project_management.todo import Todo
from bloomerp.models.users.user_detail_view_tabs_preference import (
    UserDetailViewTabItem,
    UserDetailViewTabsPreference,
)
from bloomerp.services.preference_services import PreferenceManager
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
)
from bloomerp.tests.utils.users import create_admin


class TestUserDetailViewTabsPreferenceModel(BloomerpModelTestCase):
    model = UserDetailViewTabsPreference

    def setUp(self):
        super().setUp()
        self.user = create_admin()
        self.content_type = ContentType.objects.get_for_model(Todo)

    def get_test_scenarios(self) -> list[ModelScenario[UserDetailViewTabsPreference]]:
        """Describe preference selection and locale-aware generated tab rendering."""
        return [
            ModelScenario(
                name="Existing detail tabs preference remains selectable",
                description=(
                    "UC: A user opens a detail page with an existing tabs preference.\n"
                    "Expected Result: The preference manager returns that selection "
                    "without requiring an object-layout repair hook."
                ),
                create_operation=self.get_existing_selection,
                create_validators=lambda preference: (
                    preference.user == self.user
                    and preference.content_type == self.content_type
                    and preference.selected
                ),
            ),
            ModelScenario(
                name="Generated overview names translate without changing custom names",
                create_operation=self.create_english_tabs,
                create_validators=self.check_localized_tabs,
            ),
        ]

    def create_english_tabs(self) -> UserDetailViewTabsPreference:
        """Create persisted English default tabs and a customer-authored folder."""
        preference = UserDetailViewTabsPreference.objects.create(
            user=self.user, content_type=self.content_type, name="Default"
        )
        overview = next(
            option for option in preference.get_detail_route_options(Todo)
            if option["priority"] == 0
        )
        UserDetailViewTabItem.objects.create(
            preference=preference, name="Overview", url=overview["url"], position=0
        )
        UserDetailViewTabItem.objects.create(
            preference=preference, name="Customer Overview", position=1
        )
        return preference

    def check_localized_tabs(self, preference: UserDetailViewTabsPreference) -> bool:
        """Check both locales and confirm localization never rewrites stored labels."""
        for language, label in [("nl", "Overzicht"), ("fr", "Vue d’ensemble")]:
            with override(language):
                items = preference.build_rendered_items(object_pk="example", request_path="/")
                self.assertEqual(items[0]["name"], label)
                self.assertEqual(items[1]["name"], "Customer Overview")
        self.assertEqual(preference.items.get(position=0).name, "Overview")
        return True

    def get_existing_selection(self) -> UserDetailViewTabsPreference:
        expected = UserDetailViewTabsPreference.objects.create(
            user=self.user,
            content_type=self.content_type,
            selected=True,
        )
        selected = PreferenceManager(self.user).get_or_create_selected(
            UserDetailViewTabsPreference,
            scope={"content_type_id": self.content_type.pk},
        )
        self.assertEqual(selected, expected)
        return selected
