# Generated by manage.py generate_test_cases.
from bloomerp.models.users.user import User
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
    ExpectedModelException,
)


class TestUserModel(BloomerpModelTestCase):
    model = User

    def get_test_scenarios(self) -> list[ModelScenario[User]]:
        # Add only the scenarios this class needs.
        return []
