# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestSelectInboxFolderComponent(BloomerpComponentTestCase):
    """Tests function `select_inbox_folder` from `bloomerp/components/communication/select_inbox_folder.py`."""

    view_name = 'components_select_inbox_folder'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
