# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestAddInboxFolderComponent(BloomerpComponentTestCase):
    """Tests class `AddInboxFolder` from `bloomerp/components/communication/add_inbox_folder.py`."""

    view_name = 'components_add_inbox_folder'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
