# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestPreviewFileComponent(BloomerpComponentTestCase):
    """Tests function `preview_file` from `bloomerp/components/files/items/preview.py`."""

    view_name = 'components_preview_file'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
