# Generated by manage.py generate_test_cases.
from django.contrib.contenttypes.models import ContentType

from bloomerp.automation.flows.object_if_condition import ObjectIfConditionExecutor
from bloomerp.automation.results import RouteResult
from bloomerp.models import ApplicationField
from bloomerp.models.project_management.todo import Todo
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowNodeScenario,
)


class TestObjectIfConditionNode(BloomerpWorkflowNodeTestCase):
    node_id = 'OBJECT_IF_CONDITION'
    executor_class = ObjectIfConditionExecutor

    def test_condition_ports_allow_fanout(self):
        ports = {port.id: port for port in self.executor_class.get_output_ports()}

        self.assertIsNone(ports["true"].max_connections)
        self.assertIsNone(ports["false"].max_connections)

    def get_test_scenarios(self) -> list[WorkflowNodeScenario]:
        todo = Todo.objects.create(title="Condition subject")
        content_type = ContentType.objects.get_for_model(Todo)
        title_field = ApplicationField.objects.get(
            content_type=content_type,
            field="title",
        )
        input_data = {"id": str(todo.pk), "title": todo.title}

        return [
            WorkflowNodeScenario(
                name="matching object continues through the true port",
                parameters={
                    "content_type_id": content_type.pk,
                    "field": title_field.pk,
                    "lookup": "equals",
                    "value": todo.title,
                },
                trigger_data=input_data,
                expected_output=RouteResult(port_id="true", output=input_data),
            ),
            WorkflowNodeScenario(
                name="non-matching object continues through the false port",
                parameters={
                    "content_type_id": content_type.pk,
                    "field": title_field.pk,
                    "lookup": "equals",
                    "value": "A different title",
                },
                trigger_data=input_data,
                expected_output=RouteResult(port_id="false", output=input_data),
            ),
        ]
