# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.enrich import EnrichExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowNodeScenario,
)


class TestEnrichDataNode(BloomerpWorkflowNodeTestCase):
    node_id = 'ENRICH_DATA'
    executor_class = EnrichExecutor

    def get_simulations(self) -> list[WorkflowNodeScenario]:
        return [
            WorkflowNodeScenario(
                name="Node adds configured fields to input",
                parameters={"data": {"full_name": "John Doe"}},
                trigger_data={"first_name": "John", "last_name": "Doe"},
                expected_output={
                    "first_name": "John",
                    "last_name": "Doe",
                    "full_name": "John Doe",
                },
            ),
            WorkflowNodeScenario(
                name="Node overwrites overlapping input fields",
                parameters={
                    "data": {"first_name": "Jane", "full_name": "Jane Doe"},
                },
                trigger_data={"first_name": "John", "last_name": "Doe"},
                expected_output={
                    "first_name": "Jane",
                    "last_name": "Doe",
                    "full_name": "Jane Doe",
                },
            ),
        ]
