# Generated by manage.py generate_test_cases.
from bloomerp.automation.flows.if_condition import IfConditionExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowNodeSimulation,
)


class TestIfConditionNode(BloomerpWorkflowNodeTestCase):
    node_id = 'IF_CONDITION'
    executor_class = IfConditionExecutor

    def test_condition_ports_allow_fanout(self):
        ports = {port.id: port for port in self.executor_class.get_output_ports()}

        self.assertIsNone(ports["true"].max_connections)
        self.assertIsNone(ports["false"].max_connections)

    def get_simulations(self) -> list[WorkflowNodeSimulation]:
        return []
