# Generated by manage.py generate_test_cases.
from bloomerp.automation.flows.filter_objects import FilterObjectsExecutor
from bloomerp.automation.results import StopBranchResult
from bloomerp.automation.schema import (
    WorkflowIOFlowKind,
    WorkflowIOSchema,
    WorkflowValueField,
)
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowNodeSimulation,
)


class TestFilterObjectsNode(BloomerpWorkflowNodeTestCase):
    node_id = 'FILTER_OBJECTS'
    executor_class = FilterObjectsExecutor

    def get_simulations(self) -> list[WorkflowNodeSimulation]:
        return [
            WorkflowNodeSimulation(
                name="empty result continues by default",
                parameters={
                    "field": "status",
                    "operator": "exact",
                    "value": "active",
                },
                trigger_data=[{"status": "inactive"}],
                expected_output=[],
                input_schema=WorkflowIOSchema(
                    value_type="list",
                    label="Records",
                    fields=[
                        WorkflowValueField("input.0.status", "Status", "string")
                    ],
                ),
                expected_output_schema=WorkflowIOSchema(
                    value_type="list",
                    flow_kind=WorkflowIOFlowKind.NORMAL,
                    label="Filtered Records",
                    description=(
                        "The subset of upstream objects that matched the filter."
                    ),
                    fields=[
                        WorkflowValueField("input.0.status", "Status", "string")
                    ],
                ),
            ),
            WorkflowNodeSimulation(
                name="empty result continues when enabled",
                parameters={
                    "field": "status",
                    "operator": "exact",
                    "value": "active",
                    "continue_on_empty": True,
                },
                trigger_data=[{"status": "inactive"}],
                expected_output=[],
            ),
            WorkflowNodeSimulation(
                name="empty result stops branch when disabled",
                parameters={
                    "field": "status",
                    "operator": "exact",
                    "value": "active",
                    "continue_on_empty": False,
                },
                trigger_data=[{"status": "inactive"}],
                expected_output=StopBranchResult(
                    reason="No objects matched the filter"
                ),
                input_schema=WorkflowIOSchema(
                    value_type="list",
                    label="Records",
                    fields=[
                        WorkflowValueField("input.0.status", "Status", "string")
                    ],
                ),
                expected_output_schema=WorkflowIOSchema(
                    value_type="list",
                    flow_kind=WorkflowIOFlowKind.CONDITION_GATE,
                    label="Filtered Records",
                    description=(
                        "The subset of upstream objects that matched the filter."
                    ),
                    fields=[
                        WorkflowValueField("input.0.status", "Status", "string")
                    ],
                ),
            ),
            WorkflowNodeSimulation(
                name="non-empty result continues when enabled",
                parameters={
                    "field": "status",
                    "operator": "exact",
                    "value": "active",
                    "continue_on_empty": True,
                },
                trigger_data=[
                    {"id": 1, "status": "active"},
                    {"id": 2, "status": "inactive"},
                ],
                expected_output=[{"id": 1, "status": "active"}],
            ),
            WorkflowNodeSimulation(
                name="non-empty result continues when empty handling is disabled",
                parameters={
                    "field": "status",
                    "operator": "exact",
                    "value": "active",
                    "continue_on_empty": False,
                },
                trigger_data=[
                    {"id": 1, "status": "active"},
                    {"id": 2, "status": "inactive"},
                ],
                expected_output=[{"id": 1, "status": "active"}],
            ),
        ]
