# Generated by manage.py generate_test_cases.
from bloomerp.models.document_templates.document_template_styling import DocumentTemplateStyling
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
    ExpectedModelException,
)


class TestDocumentTemplateStylingModel(BloomerpModelTestCase):
    model = DocumentTemplateStyling

    def get_test_scenarios(self) -> list[ModelScenario[DocumentTemplateStyling]]:
        # Add only the scenarios this class needs.
        return []
