# Generated by manage.py generate_test_cases.
from bloomerp.models.forms.form import Form
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
    ExpectedModelException,
)


class TestFormModel(BloomerpModelTestCase):
    model = Form

    def get_test_scenarios(self) -> list[ModelScenario[Form]]:
        # Add only the scenarios this class needs.
        return []
