# Generated by manage.py generate_test_cases.
from bloomerp.models.forms.form_submission import FormSubmission
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
)


class TestFormSubmissionModel(BloomerpModelTestCase):
    model = FormSubmission

    def get_test_scenarios(self) -> list[ModelScenario[FormSubmission]]:
        # Add only the scenarios this class needs.
        return []
