from typing import Literal, Optional
from bloomerp.config.definition import BloomerpConfig
from bloomerp.models.base_bloomerp_model import FieldLayout
from bloomerp.field_types import Lookup
from pydantic import BaseModel, Field
from django.conf import settings

class ApiFilterRule(BaseModel):
    field: str
    operator: str = Lookup.EQUALS.value.id
    value: str | int | float | bool | None = None

    def get_lookup_operator(self) -> str:
        operator_value = str(self.operator or "").strip()
        for lookup in Lookup:
            if operator_value == lookup.value.id:
                return lookup.value.django_representation or operator_value
        return operator_value


class PublicAccessRule(BaseModel):
    actions: list[Literal["list", "read"]] = Field(
        default_factory=lambda: ["list", "read"]
    )
    fields: list[str] | Literal["__all__"] = "__all__"
    filters: list[ApiFilterRule] = Field(default_factory=list)

class UserAccessRule(BaseModel):
    """A user access rule defines in which cases users can access an object via the api. The through field serves as the entry point for the user access definition. Note that user access rules only apply to the auto generated API's.

    For example, we might want to give API access to a `Project` model so that users can create particular and manage particular projects of their own, whilst the integrity of other people's projects stay the same. That would look something like this:
    ```python
    rule = UserAccessRule(
        through_field="owner",
        field_actions={
            "name" : ["view", "change", "add"],
            "type: ["view", "change", "add"],
            "datetime_created" : ["view"],
            "datetime_updated" : ["view"],
        },
        row_actions=["view", "add", "change", "delete"]
    )
    ```
    In above case, the user is able to create, add, change, delete, and view objects (as defined in the row actions) with the condition that project.owner == user

    In the case that we want to give user access to objects with a deeper link to a user, that would look something like this (assume the model `ProjectTask`). 
    ```python
    rule = UserAccessRule(
        through_field="project.owner",
        field_actions={
            "name" : ["view", "change", "add"],
            "content: ["view", "change", "add"],
            "datetime_created" : ["view"],
            "datetime_updated" : ["view"],
        },
        row_actions=["view", "add", "change", "delete"]
    )
    ```
    In the below case, the user is only able to create, view, add, and change objects (as defined in the row actions) with the condition of project_task.project.owner == user

    """
    through_field: str
    field_actions:dict[str|Literal['__all__'], list[Literal["view", "change", "add", "delete"]] | Literal['__all__']]
    row_actions:list[Literal["view", "change", "add", "delete"]]
    filters:list[ApiFilterRule] = Field(default_factory=list)


class ApiSettings(BaseModel):
    """
    Configures how Bloomerp API's are set up.

    Settings are:
        - enable_auto_generation: defines whether API endpoints are autogenerated for this model. Defaults to False
        - public_access: defines read/list exceptions for public API access
        - user_access: defines exceptions for public API access
    """

    enable_auto_generation: bool = False
    public_access: list[PublicAccessRule] = Field(default_factory=list)
    user_access:list[UserAccessRule] = Field(default_factory=list)

    def get_public_access_rules(self, action: str) -> list[PublicAccessRule]:
        normalized_action = str(action or "").strip().lower()
        return [
            rule
            for rule in self.public_access
            if normalized_action in rule.actions
        ]

    def get_user_access_rules(self, action: str) -> list[UserAccessRule]:
        normalized_action = str(action or "").strip().lower()
        return [
            rule
            for rule in self.user_access
            if normalized_action in rule.row_actions
        ]

    def has_public_access(self) -> bool:
        return len(self.public_access) > 0

    def has_user_access(self) -> bool:
        return len(self.user_access) > 0


class BloomerpModelConfig(BaseModel):
    """
    Used to define certain bloomerp related meta data on a model. 

    Settings are:
        - modules: a list of modules to which this model belongs.
        - layout: a layout object defining how the default CRUD layout for users is.

    Usage
    ```python
    from bloomerp.models.definition import BloomerpModelConfig

    class Lorum(BloomerpModel):
        bloomerp_config = BloomerpModelConfig(
            ...
        )
    ``` 
    """

    modules: Optional[list[str]] = None

    layout: Optional[FieldLayout] = None

    allow_string_search: bool = True

    is_internal: bool = False

    api_settings: Optional[ApiSettings] = None

    def get_public_access_rules(self, action: str) -> list[PublicAccessRule]:
        if self.api_settings is None:
            return []
        return self.api_settings.get_public_access_rules(action)

    def has_public_access(self) -> bool:
        if self.api_settings is None:
            return False
        return self.api_settings.has_public_access()

    def get_user_access_rules(self, action: str) -> list[UserAccessRule]:
        if self.api_settings is None:
            return []
        return self.api_settings.get_user_access_rules(action)

    def has_user_access(self) -> bool:
        if self.api_settings is None:
            return False
        return self.api_settings.has_user_access()

    def should_enable_api_auto_generation(self) -> bool:
        bloomerp_config : BloomerpConfig = getattr(settings, "BLOOMERP_CONFIG")

        if self.api_settings is None:
            # In this case, use the global setting to determine whether to auto generate API endpoints
            return bloomerp_config.auto_generate_api_endpoints
        
        return self.api_settings.enable_auto_generation
