# Generated by manage.py generate_test_cases.
"""Verify bulk upload sources use private file nodes with cached metadata."""

from django.core.files.uploadedfile import SimpleUploadedFile

from bloomerp.files.access import FileAccessManager
from bloomerp.models import FileNode, FileReference
from bloomerp.services.bulk_services import BulkCrudService
from bloomerp.tests.base import (
    BloomerpModelViewTestCase,
    ExpectedResult,
    ModelRequestScenario,
    RequestScenario,
)


class TestBloomerpBulkUploadView(BloomerpModelViewTestCase):
    """Exercise the upload wizard's storage boundary through generated scenarios."""

    view_name = "bulk_upload"
    model = None
    auto_create_customers = False

    def get_test_scenarios(self) -> list[RequestScenario]:
        """Create queryable import nodes without making temporary bytes public."""
        service = BulkCrudService(model=self.CustomerModel, user=self.admin_user)
        other_user = BulkCrudService(model=self.CustomerModel, user=self.normal_user)
        return [
            ModelRequestScenario(
                name="CSV upload stores a private node and remains readable by the import service",
                model=self.CustomerModel,
                user=self.admin_user,
                method="POST",
                data={
                    "bulk_upload_file": SimpleUploadedFile(
                        "customers.csv", b"first_name,last_name,age\nAlice,Example,35\n"
                    )
                },
                expected=ExpectedResult(
                    status_code=200,
                    response_validators=[
                        lambda response: FileNode.objects.filter(
                            kind="FILE",
                            meta__bulk_upload__model_label=self.CustomerModel._meta.label_lower,
                            meta__size=42,
                        ).exists(),
                        lambda response: not FileReference.objects.exists(),
                        lambda response: (
                            not FileAccessManager(self.admin_user).can_read_file_node(
                                FileNode.objects.get()
                            )
                        ),
                        lambda response: (
                            len(service.load_dataframe(FileNode.objects.get().pk)) == 1
                        ),
                        lambda response: (
                            other_user.get_draft_file(FileNode.objects.get().pk) is None
                        ),
                        lambda response: (
                            not FileAccessManager(self.normal_user).can_read_file_node(
                                FileNode.objects.get()
                            )
                        ),
                    ],
                ),
            ),
            ModelRequestScenario(
                name="Unauthorized import creates no file node",
                model=self.CustomerModel,
                user=self.normal_user,
                method="POST",
                data={
                    "bulk_upload_file": SimpleUploadedFile(
                        "customers.csv", b"first_name,last_name,age\nAlice,Example,35\n"
                    )
                },
                expected=ExpectedResult(
                    status_code=403,
                    response_validators=lambda response: not FileNode.objects.exists(),
                ),
            ),
        ]
