# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpModelViewTestCase,
    ExpectedResult,
    RequestScenario,
    ModelRequestScenario,
)


class TestBloomerpListView(BloomerpModelViewTestCase):
    """Tests class `BloomerpListView` from `bloomerp/views/generic/model/list.py`."""

    view_name = 'model'
    model = None

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
