# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpModelViewTestCase,
    ExpectedResult,
    RequestScenario,
    ModelRequestScenario,
)


class TestBloomerpCreateView(BloomerpModelViewTestCase):
    """Tests class `BloomerpCreateView` from `bloomerp/views/generic/model/create.py`."""

    view_name = 'add'
    model = None

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
