# Generated by manage.py generate_test_cases.
from bloomerp.models.access_control.policy import Policy
from bloomerp.tests.base import (
    BloomerpModelViewTestCase,
    ExpectedResult,
    RequestScenario,
    ModelRequestScenario,
)


class TestCreatePolicyView(BloomerpModelViewTestCase):
    """Tests class `CreatePolicyView` from `bloomerp/views/access_control/create_policy.py`."""

    view_name = 'add'
    model = Policy

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
