# Generated by manage.py generate_test_cases.
from django.core.exceptions import ValidationError

from bloomerp.communication.emails.email_providers import EmailProvider
from bloomerp.models.communication.email_account import EmailAccount
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
    ExpectedModelException,
)


class TestEmailAccountModel(BloomerpModelTestCase):
    model = EmailAccount

    def get_test_scenarios(self) -> list[ModelScenario[EmailAccount]]:
        """Verify provider validation and persistence of optional Sent-copy saving."""
        return [
            ModelScenario(
                name="Sent-copy saving defaults off and can be enabled",
                create_args={
                    "email_address": "sent-copy@example.com",
                    "imap_host": "imap.example.com",
                    "imap_port": 993,
                    "smtp_host": "smtp.example.com",
                    "smtp_port": 587,
                },
                create_validators=self.sent_copy_is_disabled,
                update_args={"save_sent_emails": True},
                update_validators=self.sent_copy_is_enabled,
            ),
            ModelScenario(
                name="Email account validates provider-required fields",
                description=(
                    "UC: An IMAP account omits its server configuration.\n"
                    "Expected Result: Model validation identifies the required IMAP host."
                ),
                create_operation=self.validate_incomplete_imap_account,
                expected_exceptions=[
                    ExpectedModelException(
                        phase="create",
                        exception=ValidationError,
                        message_regex="imap_host",
                    )
                ],
            )
        ]

    @staticmethod
    def validate_incomplete_imap_account():
        account = EmailAccount(
            provider=EmailProvider.IMAP.value.key,
            name="Incomplete inbox",
            email_address="incomplete@example.com",
        )
        account.full_clean()
        return account

    @staticmethod
    def sent_copy_is_disabled(account: EmailAccount) -> bool:
        """Check that existing and new accounts do not save extra Sent copies by default."""
        return account.save_sent_emails is False

    @staticmethod
    def sent_copy_is_enabled(account: EmailAccount) -> bool:
        """Check that opting into Sent-copy saving persists on the account."""
        return account.save_sent_emails is True
