# Generated by manage.py generate_test_cases.
from bloomerp.models.communication.comment import Comment
from django.test import SimpleTestCase
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
    ExpectedModelException,
)


class TestCommentModel(BloomerpModelTestCase):
    model = Comment

    def get_test_scenarios(self) -> list[ModelScenario[Comment]]:
        # Add only the scenarios this class needs.
        return []


class TestCommentLabel(SimpleTestCase):
    """Keep rich-text comment labels readable in relation fields."""

    def test_label_omits_markup_and_limits_length(self) -> None:
        """A comment's label contains its short text rather than its HTML body."""
        comment = Comment(content='<p class="text-md">' + 'Hello world ' * 20 + '</p>')

        label = str(comment)

        self.assertTrue(label.startswith("Hello world"))
        self.assertLessEqual(len(label), 80)
        self.assertNotIn("<p", label)
