# Generated by manage.py generate_test_cases.
from django.core.exceptions import ValidationError

from bloomerp.communication.emails.email_providers import EmailProvider
from bloomerp.models.communication.email_account import EmailAccount
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
    ExpectedModelException,
)


class TestEmailAccountModel(BloomerpModelTestCase):
    model = EmailAccount

    def get_test_scenarios(self) -> list[ModelScenario[EmailAccount]]:
        return [
            ModelScenario(
                name="Email account validates provider-required fields",
                description=(
                    "UC: An IMAP account omits its server configuration.\n"
                    "Expected Result: Model validation identifies the required IMAP host."
                ),
                create_operation=self.validate_incomplete_imap_account,
                expected_exceptions=[
                    ExpectedModelException(
                        phase="create",
                        exception=ValidationError,
                        message_regex="imap_host",
                    )
                ],
            )
        ]

    @staticmethod
    def validate_incomplete_imap_account():
        account = EmailAccount(
            provider=EmailProvider.IMAP.value.key,
            name="Incomplete inbox",
            email_address="incomplete@example.com",
        )
        account.full_clean()
        return account
