# Generated by manage.py generate_test_cases.
from bloomerp.models.communication.email_account import EmailAccount
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
    ExpectedModelException,
)


class TestEmailAccountModel(BloomerpModelTestCase):
    model = EmailAccount

    def get_test_scenarios(self) -> list[ModelScenario[EmailAccount]]:
        # Add only the scenarios this class needs.
        return []
