# Generated by manage.py generate_test_cases.
from bloomerp.models.access_control.field_policy import FieldPolicy
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
)


class TestFieldPolicyModel(BloomerpModelTestCase):
    model = FieldPolicy

    def get_test_scenarios(self) -> list[ModelScenario[FieldPolicy]]:
        # Add only the scenarios this class needs.
        return []
