# Generated by manage.py generate_test_cases.
from bloomerp.models.access_control.row_policy_rule import RowPolicyRulePermission
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
)


class TestRowPolicyRulePermissionModel(BloomerpModelTestCase):
    model = RowPolicyRulePermission

    def get_test_scenarios(self) -> list[ModelScenario[RowPolicyRulePermission]]:
        # Add only the scenarios this class needs.
        return []
