# Generated by manage.py generate_test_cases.
"""Verify content-type discovery with declarative MCP request scenarios."""

from typing import Any

from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponse

from bloomerp.oauth import oauth_enabled
from bloomerp.tests.base import (
    BloomerpMcpViewTestCase,
    ExpectedResult,
    McpRequestScenario,
)


class TestGetContentTypeView(BloomerpMcpViewTestCase):
    """Resolve model labels and report invalid or unavailable content types."""

    view_name = "get_content_type"

    def get_test_scenarios(self) -> list[McpRequestScenario]:
        """Exercise the content-type tool against real database metadata."""
        content_type = ContentType.objects.get_for_model(ContentType)
        expected: dict[str, Any] = {
            "id": content_type.pk,
            "app_label": "contenttypes",
            "model": "contenttype",
        }
        scenarios = [
            McpRequestScenario(
                name=f"Resolves {label}",
                user=self.normal_user,
                arguments={"model_label": label},
                expected=ExpectedResult(
                    response_validators=self.mcp_structured_content_equals(expected),
                ),
            )
            for label in ("contenttypes.ContentType", "CONTENTTYPES.CONTENTTYPE")
        ]
        for arguments in (
            {},
            {"model_label": "ContentType"},
            {"resource": "contenttypes.ContentType"},
            {"model_label": "missing.Model"},
            {"model_label": "contenttypes.Missing"},
        ):
            scenarios.append(
                McpRequestScenario(
                    name=f"Rejects invalid model identity {arguments}",
                    user=self.normal_user,
                    arguments=arguments,
                    expected=ExpectedResult(response_validators=self.mcp_is_error()),
                )
            )
        scenarios.extend(
            [
                McpRequestScenario(
                    name="Rejects anonymous content-type lookup",
                    arguments={"model_label": "contenttypes.ContentType"},
                    expected=ExpectedResult(
                        status_code=200 if oauth_enabled() else 401,
                        response_validators=self.mcp_is_error()
                        if oauth_enabled()
                        else None,
                    ),
                ),
                McpRequestScenario(
                    name="Reports missing content type without creating one",
                    user=self.normal_user,
                    arguments={"model_label": "contenttypes.ContentType"},
                    prepare=self.remove_content_type,
                    expected=ExpectedResult(
                        response_validators=[
                            self.mcp_is_error(),
                            self.missing_content_type_is_reported,
                        ]
                    ),
                ),
            ]
        )
        return scenarios

    def remove_content_type(self, scenario: McpRequestScenario) -> None:
        """Remove the metadata record inside the scenario's rollback boundary."""
        ContentType.objects.clear_cache()
        ContentType.objects.filter(
            app_label="contenttypes", model="contenttype"
        ).delete()

    def missing_content_type_is_reported(self, response: HttpResponse) -> bool:
        """Check the public error and confirm lookup did not recreate the record."""
        return (
            "Content type not found" in response.json()["result"]["content"][0]["text"]
            and not ContentType.objects.filter(
                app_label="contenttypes",
                model="contenttype",
            ).exists()
        )
