# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestLookupsComponent(BloomerpComponentTestCase):
    """Tests function `lookups` from `bloomerp/components/filters/lookups.py`."""

    view_name = 'components_filters_lookups'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
