# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestDeleteComponent(BloomerpComponentTestCase):
    """Tests function `delete` from `bloomerp/components/filters/delete.py`."""

    view_name = 'components_delete'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
