# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestSaveComponent(BloomerpComponentTestCase):
    """Tests function `save` from `bloomerp/components/filters/save.py`."""

    view_name = 'components_filters_save'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return [
            RequestScenario(
                name="User can save filter on workspace",
                
            ),
            RequestScenario(
                name="User can save a specific filter on a dataview"
            ),
            RequestScenario(
                name=""
            )
        ]
