# Generated by manage.py generate_test_cases.
from bloomerp.models.forms.form_submission import FormSubmission
from bloomerp.tests.base import (
    BloomerpDetailViewTestCase,
    ExpectedResult,
    RequestScenario,
    ModelRequestScenario,
)


class TestReviewFormSubmissionView(BloomerpDetailViewTestCase):
    """Tests class `ReviewFormSubmissionView` from `bloomerp/views/forms/review_submission.py`."""

    view_name = 'Review Submission'
    model = FormSubmission

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
