# Generated by manage.py generate_test_cases.
from bloomerp.models.forms.form import Form
from bloomerp.services.sectioned_layout_services import create_default_layout
from bloomerp.tests.base import (
    BloomerpDetailViewTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestSubmitFormView(BloomerpDetailViewTestCase):
    """Tests class `SubmitFormView` from `bloomerp/views/forms/submit.py`."""

    view_name = 'submit'
    model = Form

    def create_test_object(self) -> Form:
        """Create a form with a distinct description and success message."""
        return Form.objects.create(
            name="Customer intake",
            description="Complete this customer form.",
            success_text="<p>Thank you for submitting your details.</p>",
            content_type=self.get_content_type_for_model(self.CustomerModel),
            layout=create_default_layout(self.CustomerModel).model_dump(),
            requires_review=False,
        )

    def get_test_scenarios(self) -> list[RequestScenario]:
        """Verify that a valid POST shows the success text instead of the description."""
        return [
            RequestScenario(
                name="Successful submission shows configured success text",
                method="POST",
                data={"first_name": "Ada", "last_name": "Lovelace", "age": 36},
                expected=ExpectedResult(
                    response_validators=[
                        self.contains_text("<p>Thank you for submitting your details.</p>"),
                        self.does_not_contain_text("Complete this customer form."),
                    ],
                ),
            ),
        ]
