# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpE2ETestCase,
    E2EAction,
    E2ERequestScenario,
)


class TestCreateWorkflowViewE2E(BloomerpE2ETestCase):
    """Tests class `CreateWorkflowView` from `bloomerp/views/workflows/builder.py`."""

    view_name = 'builder'

    def get_test_scenarios(self) -> list[E2ERequestScenario]:
        # Add only the browser scenarios this view needs.
        return []
