# Generated by Django 5.1.1 on 2025-09-08 11:22

import bloomerp_modules.validators.date_validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank account',
                'verbose_name_plural': 'Bank accounts',
                'db_table': 'finance_treasury_bank_account',
                'db_table_comment': 'Stores bank account information',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('first_name', models.CharField(help_text='First name of the employee', max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text='Last name of the employee', max_length=100, null=True, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, help_text='Middle name of the employee', max_length=100, null=True, verbose_name='Middle Name')),
                ('date_of_birth', models.DateField(blank=True, help_text=None, null=True, validators=[bloomerp_modules.validators.date_validators.is_before_today], verbose_name='Date of birth')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'hrm_employees_employee',
                'db_table_comment': 'Employee record',
            },
        ),
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('start_date', models.DateField(blank=True, help_text='Start date of the contract.', null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, help_text='End date of the contract.', null=True, verbose_name='End date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Link to employee', on_delete=django.db.models.deletion.CASCADE, to='bloomerp_modules.employee', verbose_name='employee')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee contract',
                'verbose_name_plural': 'Employee contracts',
                'db_table': 'hrm_employees_employee_contract',
                'db_table_comment': 'Stores contract information for employees',
            },
        ),
    ]
