# Generated by Django 5.1.1 on 2026-05-12 16:21

import bloomerp.model_fields.phone_number_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "bloomerp_modules",
            "0002_alter_account_created_by_alter_account_updated_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=bloomerp.model_fields.phone_number_field.PhoneNumberField(
                blank=True,
                help_text=None,
                max_length=30,
                null=True,
                verbose_name="Phone",
            ),
        ),
    ]
