# Generated by Django 5.1.1 on 2026-05-18 17:40

import bloomerp.model_fields.address_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp_modules", "0003_alter_lead_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="address",
            field=bloomerp.model_fields.address_field.AddressField(
                blank=True, help_text=None, null=True, verbose_name="Address"
            ),
        ),
    ]
