# Generated by Django 5.1.1 on 2026-05-27 19:14

import bloomerp.model_fields.week_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp_modules", "0004_contact_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="initiation_week",
            field=bloomerp.model_fields.week_field.WeekField(
                default="2026-W12",
                help_text="Week in which employee has initiation",
                max_length=8,
                verbose_name="Initiation week",
            ),
            preserve_default=False,
        ),
    ]
