# Generated by Django 5.1.1 on 2026-09-20 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp_modules', '0010_contact_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinvoiceline',
            name='product_code',
        ),
        migrations.AddField(
            model_name='customerinvoiceline',
            name='product',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloomerp_modules.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('task', 'Task')], help_text=None, max_length=255, verbose_name='Activity Type'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('screening', 'Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='received', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave')], default='present', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit', 'Credit')], help_text=None, max_length=255, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='source',
            field=models.CharField(blank=True, choices=[('referral', 'Referral'), ('job_board', 'Job Board'), ('website', 'Website'), ('agency', 'Agency'), ('other', 'Other')], help_text=None, max_length=255, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('screening', 'Screening'), ('interviewing', 'Interviewing'), ('offered', 'Offered'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='new', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='costrate',
            name='rate_type',
            field=models.CharField(choices=[('labor', 'Labor'), ('machine', 'Machine'), ('overhead', 'Overhead')], help_text=None, max_length=255, verbose_name='Rate Type'),
        ),
        migrations.AlterField(
            model_name='crmaccount',
            name='account_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('prospect', 'Prospect'), ('partner', 'Partner'), ('vendor', 'Vendor')], help_text='Classification of the account relationship', max_length=255, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='crmaccount',
            name='rating',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], help_text=None, max_length=255, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('INACTIVE', 'Inactive')], help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='customerinvoiceline',
            name='description',
            field=models.CharField(blank=True, help_text=None, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='payment_method',
            field=models.CharField(choices=[('ACH', 'ACH'), ('WIRE', 'Wire'), ('CARD', 'Card'), ('CHECK', 'Check')], help_text=None, max_length=255, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contractor', 'Contractor'), ('intern', 'Intern')], help_text='Type of employment', max_length=255, null=True, verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('leave', 'On Leave'), ('terminated', 'Terminated')], default='active', help_text='Current employment status', max_length=255, verbose_name='Employment Status'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('fixed_term', 'Fixed Term'), ('contractor', 'Contractor'), ('intern', 'Intern')], help_text=None, max_length=255, null=True, verbose_name='Contract Type'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('scrapped', 'Scrapped')], default='active', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='gltransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer'), ('REVALUATION', 'Revaluation')], default='DEBIT', help_text=None, max_length=255, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='not_started', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='hiringdecision',
            name='decision',
            field=models.CharField(blank=True, choices=[('hire', 'Hire'), ('reject', 'Reject'), ('hold', 'Hold')], help_text=None, max_length=255, null=True, verbose_name='Decision'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(blank=True, choices=[('phone', 'Phone'), ('video', 'Video'), ('onsite', 'On-site')], help_text=None, max_length=255, null=True, verbose_name='Interview Type'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('hire', 'Hire'), ('hold', 'Hold'), ('no_hire', 'No Hire')], help_text=None, max_length=255, null=True, verbose_name='Recommendation'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('on_hold', 'On Hold'), ('closed', 'Closed')], default='draft', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('phone', 'Phone'), ('referral', 'Referral'), ('event', 'Event'), ('partner', 'Partner')], help_text=None, max_length=255, verbose_name='Lead Source'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text=None, max_length=255, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('converted', 'Converted')], help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='requested', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='category',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('sick', 'Sick'), ('other', 'Other')], help_text=None, max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('input', 'Input'), ('output', 'Output'), ('scrap', 'Scrap'), ('production', 'Production')], help_text=None, max_length=255, verbose_name='Location Type'),
        ),
        migrations.AlterField(
            model_name='maintenanceplan',
            name='frequency_type',
            field=models.CharField(choices=[('time_based', 'Time Based'), ('meter_based', 'Meter Based')], help_text=None, max_length=255, verbose_name='Frequency Type'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', help_text=None, max_length=255, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='maintenanceworkorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('released', 'Released'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', help_text=None, max_length=255, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('released', 'Released'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='manufacturingordercomponent',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('partially_issued', 'Partially Issued'), ('fully_issued', 'Fully Issued')], default='planned', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='manufacturingorderoperation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='masterproductionschedule',
            name='source',
            field=models.CharField(choices=[('forecast', 'Forecast'), ('sales_orders', 'Sales Orders'), ('manual', 'Manual')], help_text=None, max_length=255, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='mrprun',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='nonconformancereport',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_analysis', 'In Analysis'), ('closed', 'Closed')], default='open', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='offboardingprocess',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='draft', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='offerapproval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='onboardingprocess',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='onboardingtaskassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='pending', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='source',
            field=models.CharField(choices=[('lead', 'Lead'), ('referral', 'Referral'), ('upsell', 'Upsell'), ('renewal', 'Renewal')], help_text=None, max_length=255, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost')], help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='performancecycle',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('closed', 'Closed')], default='planned', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('completed', 'Completed')], default='draft', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(blank=True, choices=[('employee', 'Employee'), ('candidate', 'Candidate'), ('contractor', 'Contractor'), ('alumni', 'Alumni')], help_text=None, max_length=255, null=True, verbose_name='Person Type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='plannedorder',
            name='order_type',
            field=models.CharField(choices=[('manufacturing', 'Manufacturing'), ('purchase', 'Purchase')], help_text=None, max_length=255, verbose_name='Order Type'),
        ),
        migrations.AlterField(
            model_name='plannedorder',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('converted', 'Converted'), ('cancelled', 'Cancelled')], default='planned', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tracking_method',
            field=models.CharField(choices=[('none', 'None'), ('lot', 'Lot'), ('serial', 'Serial')], default='none', help_text=None, max_length=255, verbose_name='Tracking Method'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('manufactured', 'Manufactured'), ('purchased', 'Purchased'), ('service', 'Service')], help_text=None, max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='productioncost',
            name='valuation_method',
            field=models.CharField(choices=[('standard', 'Standard'), ('actual', 'Actual'), ('average', 'Average')], help_text=None, max_length=255, verbose_name='Valuation Method'),
        ),
        migrations.AlterField(
            model_name='productionmove',
            name='move_type',
            field=models.CharField(choices=[('component_issue', 'Component Issue'), ('finished_good_receipt', 'Finished Good Receipt'), ('scrap', 'Scrap')], help_text=None, max_length=255, verbose_name='Move Type'),
        ),
        migrations.AlterField(
            model_name='productiontimeentry',
            name='time_type',
            field=models.CharField(choices=[('setup', 'Setup'), ('run', 'Run'), ('cleanup', 'Cleanup'), ('downtime', 'Downtime')], help_text=None, max_length=255, verbose_name='Time Type'),
        ),
        migrations.AlterField(
            model_name='qualitycontrolplanline',
            name='test_type',
            field=models.CharField(choices=[('attribute', 'Attribute'), ('measurement', 'Measurement')], help_text=None, max_length=255, verbose_name='Test Type'),
        ),
        migrations.AlterField(
            model_name='qualityinspection',
            name='reference_type',
            field=models.CharField(choices=[('manufacturing_order', 'Manufacturing Order'), ('goods_receipt', 'Goods Receipt')], help_text=None, max_length=255, verbose_name='Reference Type'),
        ),
        migrations.AlterField(
            model_name='qualityinspection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='qualityinspectionresult',
            name='result',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], help_text=None, max_length=255, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='qualityinspectionresult',
            name='test_type',
            field=models.CharField(choices=[('attribute', 'Attribute'), ('measurement', 'Measurement')], help_text=None, max_length=255, verbose_name='Test Type'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('system', 'System'), ('ai', 'AI')], help_text=None, max_length=255, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('INACTIVE', 'Inactive')], help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='payment_method',
            field=models.CharField(choices=[('ACH', 'ACH'), ('WIRE', 'Wire'), ('CARD', 'Card'), ('CHECK', 'Check')], help_text=None, max_length=255, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PAID', 'Paid'), ('VOIDED', 'Voided')], help_text=None, max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='work_center_type',
            field=models.CharField(choices=[('machine', 'Machine'), ('labor', 'Labor'), ('cell', 'Cell')], help_text=None, max_length=255, verbose_name='Work Center Type'),
        ),
    ]
