# Generated by manage.py generate_test_cases.
from bloomerp.form_fields.icon_field import IconFormField
from bloomerp.tests.base import BloomerpFormFieldTestCase


class TestIconFormField(BloomerpFormFieldTestCase):
    field_class = IconFormField


    