# Generated by manage.py generate_test_cases.
from bloomerp.form_fields.icon_field import IconFormField
from bloomerp.tests.base import (
    BloomerpFormFieldTestCase,
    FormFieldScenario,
    ExpectedFormFieldException,
)


class TestIconFormField(BloomerpFormFieldTestCase):
    field_class = IconFormField

    def get_test_scenarios(self) -> list[FormFieldScenario[IconFormField]]:
        # Add only the scenarios this class needs.
        return []
