# Generated by manage.py generate_test_cases.
from bloomerp.form_fields.address_field import AddressFormField
from bloomerp.tests.base import (
    BloomerpFormFieldTestCase,
    FormFieldScenario,
    ExpectedFormFieldException,
)


class TestAddressFormField(BloomerpFormFieldTestCase):
    field_class = AddressFormField

    def get_test_scenarios(self) -> list[FormFieldScenario[AddressFormField]]:
        # Add only the scenarios this class needs.
        return []
