# Generated by manage.py generate_test_cases.
from bloomerp.form_fields.files_relation_field import FilesRelationField
from bloomerp.tests.base import (
    BloomerpFormFieldTestCase,
    FormFieldScenario,
)


class TestFilesRelationFieldFormField(BloomerpFormFieldTestCase):
    field_class = FilesRelationField

    def get_test_scenarios(self) -> list[FormFieldScenario[FilesRelationField]]:
        # Add only the scenarios this class needs.
        return []
