# Generated by manage.py generate_test_cases.
from bloomerp.form_fields.ordered_multiple_choice_field import OrderedMultipleChoiceField
from bloomerp.tests.base import (
    BloomerpFormFieldTestCase,
    FormFieldScenario,
)


class TestOrderedMultipleChoiceFieldFormField(BloomerpFormFieldTestCase):
    field_class = OrderedMultipleChoiceField

    def get_test_scenarios(self) -> list[FormFieldScenario[OrderedMultipleChoiceField]]:
        # Add only the scenarios this class needs.
        return []
