# Generated by manage.py generate_test_cases.
from bloomerp.form_fields.phone_number_field import PhoneNumberFormField
from bloomerp.tests.base import (
    BloomerpFormFieldTestCase,
    FormFieldScenario,
    ExpectedFormFieldException,
)


class TestPhoneNumberFormField(BloomerpFormFieldTestCase):
    field_class = PhoneNumberFormField

    def get_test_scenarios(self) -> list[FormFieldScenario[PhoneNumberFormField]]:
        # Add only the scenarios this class needs.
        return []
