# Generated by manage.py generate_test_cases.
from django.core.exceptions import ValidationError

from bloomerp.models.project_management.initiative import Initiative, InitiativeStatus
from bloomerp.models.project_management.todo import Todo, TodoStatus
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ExpectedModelException,
    ModelScenario,
)


class TestInitiativeModel(BloomerpModelTestCase):
    model = Initiative

    def create_todos(
        self,
        initiative: Initiative,
        *,
        assigned: list[tuple[str, str]],
        unrelated: list[tuple[str, str]] | None = None,
    ) -> None:
        for title, status in assigned:
            Todo.objects.create(
                title=title,
                initiative=initiative,
                status=status,
            )
        for title, status in unrelated or []:
            Todo.objects.create(title=title, status=status)

    def validate_cached_todo_properties(self, initiative: Initiative) -> bool:
        with self.assertNumQueries(1):
            todo_count = initiative.todo_count
            completion_percentage = initiative.completion_percentage
            has_started = initiative.has_started

        return (
            todo_count == 2
            and completion_percentage == "50%"
            and has_started
        )

    def create_descendant_cycle(self, initiative: Initiative) -> None:
        child = Initiative.objects.create(name="Build portal", parent=initiative)
        descendant = Initiative.objects.create(name="Design portal", parent=child)
        initiative.parent = descendant

    def get_test_scenarios(self) -> list[ModelScenario[Initiative]]:
        return [
            ModelScenario(
                name="Initiative counts only assigned to-dos",
                create_args={"name": "Launch customer portal"},
                post_create=lambda initiative: self.create_todos(
                    initiative,
                    assigned=[("Design flow", TodoStatus.BACKLOG), ("Build flow", TodoStatus.BACKLOG)],
                    unrelated=[("Unrelated work", TodoStatus.BACKLOG)],
                ),
                create_validators=lambda initiative: initiative.todo_count == 2,
            ),
            ModelScenario(
                name="Initiative calculates completion from assigned to-dos",
                create_args={"name": "Launch customer portal"},
                post_create=lambda initiative: self.create_todos(
                    initiative,
                    assigned=[
                        ("Done", TodoStatus.COMPLETED),
                        ("Duplicate", TodoStatus.DUPLICATE),
                        ("Cancelled", TodoStatus.CANCELLED),
                        ("In progress", TodoStatus.IN_PROGRESS),
                        ("Backlog", TodoStatus.BACKLOG),
                    ],
                    unrelated=[("Unrelated", TodoStatus.COMPLETED)],
                ),
                create_validators=lambda initiative: (
                    initiative.completion_percentage == "60%"
                ),
            ),
            ModelScenario(
                name="Initiative without to-dos has not started",
                create_args={"name": "Launch customer portal"},
                create_validators=[
                    lambda initiative: initiative.completion_percentage == "0%",
                    lambda initiative: not initiative.has_started,
                ],
            ),
            ModelScenario(
                name="Initiative starts when an assigned to-do is active",
                create_args={"name": "Launch customer portal"},
                post_create=lambda initiative: self.create_todos(
                    initiative,
                    assigned=[
                        ("Backlog", TodoStatus.BACKLOG),
                        ("Review", TodoStatus.IN_REVIEW),
                    ],
                ),
                create_validators=lambda initiative: initiative.has_started,
            ),
            ModelScenario(
                name="Initiative computed properties share cached status counts",
                create_args={"name": "Launch customer portal"},
                post_create=lambda initiative: self.create_todos(
                    initiative,
                    assigned=[
                        ("Done", TodoStatus.COMPLETED),
                        ("Review", TodoStatus.IN_REVIEW),
                    ],
                ),
                create_validators=self.validate_cached_todo_properties,
            ),
            ModelScenario(
                name="Completed initiative automatically records completion time",
                create_args={
                    "name": "Launch customer portal",
                    "status": InitiativeStatus.COMPLETED,
                },
                create_validators=lambda initiative: (
                    initiative.completed_at is not None
                ),
            ),
            ModelScenario(
                name="Reopened initiative clears its completion time",
                create_args={
                    "name": "Launch customer portal",
                    "status": InitiativeStatus.COMPLETED,
                },
                create_validators=lambda initiative: (
                    initiative.completed_at is not None
                ),
                update_args={"status": InitiativeStatus.IN_PROGRESS},
                update_validators=lambda initiative: initiative.completed_at is None,
            ),
            ModelScenario(
                name="Initiative rejects itself as parent",
                create_args={"name": "Launch customer portal"},
                post_create=lambda initiative: setattr(
                    initiative,
                    "parent",
                    initiative,
                ),
                update_args={},
                expected_exceptions=[
                    ExpectedModelException(
                        phase="update",
                        exception=ValidationError,
                    )
                ],
            ),
            ModelScenario(
                name="Initiative rejects a descendant as parent",
                create_args={"name": "Launch customer portal"},
                post_create=self.create_descendant_cycle,
                update_args={},
                expected_exceptions=[
                    ExpectedModelException(
                        phase="update",
                        exception=ValidationError,
                    )
                ],
            ),
        ]
