# Generated by manage.py generate_test_cases.
from bloomerp.models.project_management.todo_label import TodoLabel
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
    ExpectedModelException,
)


class TestTodoLabelModel(BloomerpModelTestCase):
    model = TodoLabel

    def get_test_scenarios(self) -> list[ModelScenario[TodoLabel]]:
        # Add only the scenarios this class needs.
        return []
