# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestCreateObjectComponentViewComponent(BloomerpComponentTestCase):
    """Tests class `CreateObjectComponentView` from `bloomerp/components/objects/crud/create_update.py`."""

    view_name = 'components_create_object'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
