# Generated by manage.py generate_test_cases.
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponse

from bloomerp.models.application_field import ApplicationField
from bloomerp.models.project_management.todo_label import TodoLabel
from bloomerp.models.users.user_object_layout_preference import UserObjectLayoutPreference
from bloomerp.services.preference_services import PreferenceManager
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestCreateObjectComponentViewComponent(BloomerpComponentTestCase):
    """Tests class `CreateObjectComponentView` from `bloomerp/components/objects/crud/create_update.py`."""

    view_name = 'components_create_object'

    def get_test_scenarios(self) -> list[RequestScenario]:
        """Verify modal targets and rendering with stale saved layout entries."""
        kwargs = {"content_type_id": ContentType.objects.get_for_model(TodoLabel).pk}
        customer_kwargs = {"content_type_id": ContentType.objects.get_for_model(self.CustomerModel).pk}
        validators = [
            self.contains_text('hx-target="closest [data-modal-body]"'),
            self.contains_text('name="foreign_field_widget_id" value="widget-parent"'),
            self.does_not_contain_text('#create-object-modal-body'),
        ]
        return [
            RequestScenario(
                name="Modal form targets its owning body",
                user=self.admin_user,
                view_kwargs=kwargs,
                headers={"hx-request": "true"},
                query_params={"foreign_field_widget_id": "widget-parent"},
                expected=ExpectedResult(response_validators=validators),
            ),
            RequestScenario(
                name="Validation response preserves target and originating widget",
                method="POST",
                user=self.admin_user,
                view_kwargs=kwargs,
                headers={"hx-request": "true"},
                data={"name": "", "foreign_field_widget_id": "widget-parent"},
                expected=ExpectedResult(response_validators=[
                    *validators, self.contains_text('This field is required.'),
                ]),
            ),
            RequestScenario(
                name="Stale and wrong-model layout fields do not break modal creation",
                user=self.admin_user,
                view_kwargs=customer_kwargs,
                headers={"hx-request": "true"},
                prepare=self.prepare_stale_layout,
                expected=ExpectedResult(response_validators=[
                    self.contains_text('name="first_name"'),
                    self.contains_text('Retained Field'),
                    self.contains_text('Custom section'),
                    self.layout_remains_saved,
                ]),
            ),
            RequestScenario(
                name="Invalid submission re-renders a layout containing stale fields",
                method="POST",
                user=self.admin_user,
                view_kwargs=customer_kwargs,
                headers={"hx-request": "true"},
                data={"first_name": "", "foreign_field_widget_id": "widget-parent"},
                prepare=self.prepare_stale_layout,
                expected=ExpectedResult(response_validators=[
                    *validators,
                    self.contains_text('This field is required.'),
                    self.layout_remains_saved,
                ]),
            ),
            RequestScenario(
                name="Fully stale layout falls back to usable default fields",
                user=self.admin_user,
                view_kwargs=customer_kwargs,
                headers={"hx-request": "true"},
                prepare=self.prepare_fully_stale_layout,
                expected=ExpectedResult(response_validators=[
                    self.contains_text('name="first_name"'),
                    self.contains_text('name="last_name"'),
                    self.contains_text('name="age"'),
                    self.layout_remains_saved,
                ]),
            ),
        ]

    def prepare_stale_layout(self, _scenario: RequestScenario) -> None:
        """Mix a customized Customer field with missing and foreign-model field IDs."""
        content_type = ContentType.objects.get_for_model(self.CustomerModel)
        field = ApplicationField.objects.get(content_type=content_type, field="first_name")
        other_field = ApplicationField.objects.get(
            content_type=ContentType.objects.get_for_model(TodoLabel), field="name",
        )
        self.layout_preference = PreferenceManager(self.admin_user).get_or_create_selected(
            UserObjectLayoutPreference, scope={"content_type_id": content_type.pk},
        )
        self.saved_layout = {"rows": [{
            "title": "Custom section",
            "columns": 3,
            "items": [
                {"id": str(field.pk), "colspan": 2, "config": {"label": "Retained field"}},
                {"id": "2147483647"},
                {"id": other_field.pk},
            ],
        }]}
        self.layout_preference.layout = self.saved_layout
        self.layout_preference.save(update_fields=["layout"])

    def prepare_fully_stale_layout(self, scenario: RequestScenario) -> None:
        """Leave a nonempty saved layout whose field IDs no longer resolve."""
        self.prepare_stale_layout(scenario)
        self.saved_layout["rows"][0]["items"] = [{"id": "2147483647"}]
        self.layout_preference.layout = self.saved_layout
        self.layout_preference.save(update_fields=["layout"])

    def layout_remains_saved(self, _response: HttpResponse) -> bool:
        """Ensure render-time recovery never overwrites the user's saved layout."""
        self.layout_preference.refresh_from_db()
        return self.layout_preference.layout == self.saved_layout
