# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpE2ETestCase,
    E2EAction,
    E2ERequestScenario,
)


class TestDocumentTemplateBuilderEditViewE2E(BloomerpE2ETestCase):
    """Tests class `DocumentTemplateBuilderEditView` from `bloomerp/views/document_templates/document_template_builder_view.py`."""

    view_name = 'builder'

    def get_test_scenarios(self) -> list[E2ERequestScenario]:
        # Add only the browser scenarios this view needs.
        return []
