# Generated by manage.py generate_test_cases.
from django.urls import reverse
from playwright.sync_api import Response, expect

from bloomerp.models.document_templates.document_template import DocumentTemplate
from bloomerp.tests.base import BloomerpE2ETestCase, E2EAction, E2ERequestScenario


class TestDocumentTemplateBuilderEditViewE2E(BloomerpE2ETestCase):
    """Keep builder appearance separate from document content and custom CSS."""

    view_name = "builder"

    def prepare_dark_theme(self) -> None:
        """Select dark mode in this scenario's isolated browser context."""
        self.context.add_init_script(
            "localStorage.setItem('bloomerp_theme_preference', 'dark')"
        )

    def prepare_light_theme(self) -> None:
        """Select light mode in this scenario's isolated browser context."""
        self.context.add_init_script(
            "localStorage.setItem('bloomerp_theme_preference', 'light')"
        )

    def assert_dark_editor(self) -> None:
        """Check real computed editor contrast and input-matching frame borders."""
        frame = self.page.locator("#page-container")
        expect(frame).to_have_attribute("data-document-styling", "false")
        expect(frame).to_have_css("background-color", "rgb(39, 39, 42)")
        expect(frame).to_have_css("border-top-color", "rgb(82, 82, 91)")
        expect(frame).to_have_css("border-top-width", "1px")
        expect(self.page.locator("[contenteditable] p").first).to_have_css(
            "color", "rgb(244, 244, 245)"
        )

    def assert_light_editor(self) -> None:
        """Keep the original white page and unstyled black document text."""
        expect(self.page.locator("#page-container")).to_have_css(
            "background-color", "rgb(255, 255, 255)"
        )
        expect(self.page.locator("[contenteditable] p").first).to_have_css(
            "color", "rgb(0, 0, 0)"
        )

    def assert_custom_document(self) -> None:
        """Respect foreground-only custom CSS without changing its paper baseline."""
        frame = self.page.locator("#page-container")
        expect(frame).to_have_attribute("data-document-styling", "true")
        expect(frame).to_have_css("background-color", "rgb(255, 255, 255)")
        expect(self.page.locator("[contenteditable] p").first).to_have_css(
            "color", "rgb(17, 34, 51)"
        )

    def save_without_theme_markup(self) -> None:
        """Save through the builder and ensure appearance stays outside its payload."""
        def is_builder_save(response: Response) -> bool:
            """Match only the current builder's save response."""
            return (
                response.request.method == "POST"
                and response.url.split("?")[0] == self.page.url.split("?")[0]
            )

        with self.page.expect_response(is_builder_save):
            self.page.get_by_role("button", name="Save", exact=True).click()
        self.document.refresh_from_db()
        self.assertIn("Readable document", self.document.template)
        self.assertNotIn("document-template-builder-page", self.document.template)
        self.assertNotIn("document-styling", self.document.template)
        self.assertEqual(self.document.custom_styling, "")
        self.page.reload()
        self.assert_dark_editor()

    def get_test_scenarios(self) -> list[E2ERequestScenario]:
        """Exercise dark/light editing and custom CSS with disposable test records."""
        self.document = DocumentTemplate.objects.create(
            name="Theme regression", template="<p>Readable document</p>"
        )
        custom = DocumentTemplate.objects.create(
            name="Custom theme regression",
            template="<p>Custom document</p>",
            custom_styling="body { color: #112233; }",
        )
        return [
            E2ERequestScenario(
                name="Dark editor remains readable across save and reload",
                user=self.admin_user,
                prepare=self.prepare_dark_theme,
                url=reverse("document_templates_detail_builder", kwargs={"pk": self.document.pk}),
                actions=[
                    E2EAction(self.assert_dark_editor, name="Check dark paper and border"),
                    E2EAction(self.save_without_theme_markup, name="Save and reload"),
                ],
            ),
            E2ERequestScenario(
                name="Light editor keeps white paper",
                user=self.admin_user,
                prepare=self.prepare_light_theme,
                url=reverse("document_templates_detail_builder", kwargs={"pk": self.document.pk}),
                actions=[E2EAction(self.assert_light_editor, name="Check light paper")],
            ),
            E2ERequestScenario(
                name="Custom document CSS retains paper in dark mode",
                user=self.admin_user,
                prepare=self.prepare_dark_theme,
                url=reverse("document_templates_detail_builder", kwargs={"pk": custom.pk}),
                actions=[E2EAction(self.assert_custom_document, name="Check custom CSS")],
            ),
        ]
