# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestSaveLayoutObjectComponent(BloomerpComponentTestCase):
    """Tests function `save_layout_object` from `bloomerp/components/layout/save_layout_object.py`."""

    view_name = 'components_save_layout_object'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
