# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestAvailableLayoutItemsComponent(BloomerpComponentTestCase):
    """Tests function `available_layout_items` from `bloomerp/components/layout/available_layout_items.py`."""

    view_name = 'components_available_layout_items'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
