# Generated by Django 5.1.1 on 2025-07-20 12:41

import bloomerp.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0073_aiconversation_args_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlqueryfilter',
            name='column',
        ),
        migrations.RemoveField(
            model_name='sqlqueryfilter',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='sqlqueryfilter',
            name='filter_operation',
        ),
        migrations.AddField(
            model_name='sqlqueryfilter',
            name='filter_type',
            field=models.CharField(choices=[('absolute', 'Absolute'), ('integer', 'Integer'), ('float', 'Float'), ('date', 'Date'), ('boolean', 'Boolean'), ('string', 'String'), ('select', 'Select'), ('model_select', 'Model Select')], default='absolute', max_length=255),
        ),
        migrations.AddField(
            model_name='sqlqueryfilter',
            name='query',
            field=bloomerp.models.fields.CodeField(default=django.utils.timezone.now, help_text='SQL Query to execute', language='sql'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='free_variables',
            field=models.ManyToManyField(help_text='A free variable is a variable that is not from a model, and can be inserted in the template at creation time.', to='bloomerp.documenttemplatefreevariable'),
        ),
        migrations.AlterField(
            model_name='filefolder',
            name='content_types',
            field=models.ManyToManyField(help_text='Restrict folders to certain models.', to='contenttypes.contenttype', verbose_name='Models'),
        ),
        migrations.AlterField(
            model_name='filefolder',
            name='files',
            field=models.ManyToManyField(related_name='folders', to='bloomerp.file'),
        ),
        migrations.AlterField(
            model_name='sqlqueryfilter',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
