# Generated by Django 5.1.1 on 2026-01-26 22:26

import bloomerp.model_fields.code_field
import bloomerp.model_fields.text_editor_field
import bloomerp.model_fields.user_field
import bloomerp.models.files.file
import bloomerp.models.mixins
import bloomerp.models.users.user_list_view_preference
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'bloomerp_todo_label',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('file_view_preference', models.CharField(choices=[('card', 'Card View'), ('list', 'List View')], default='card', max_length=20)),
                ('date_view_preference', models.CharField(choices=[('d-m-Y', 'Day-Month-Year (15-08-2000)'), ('m-d-Y', 'Month-Day-Year (08-15-2000)'), ('Y-m-d', 'Year-Month-Day (2000-08-15)')], default='d-m-Y', help_text='The date format to be used in the application', max_length=20)),
                ('datetime_view_preference', models.CharField(choices=[('d-m-Y H:i', 'Day-Month-Year Hour:Minute (15-08-2000 12:30)'), ('m-d-Y H:i', 'Month-Day-Year Hour:Minute (08-15-2000 12:30)'), ('Y-m-d H:i', 'Year-Month-Day Hour:Minute (2000-08-15 12:30)')], default='d-m-Y H:i', help_text='The datetime format to be used in the application', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
                'default_permissions': ('add', 'change', 'delete', 'view', 'bulk_change', 'bulk_delete', 'bulk_add', 'export'),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='AI Conversation', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_history', models.JSONField(blank=True, null=True)),
                ('conversation_type', models.CharField(choices=[('sql', 'SQL'), ('document_template', 'Document Template Generator'), ('tiny_mce_content', 'TinyMCE Content Generator'), ('bloom_ai', 'Bloom AI'), ('code', 'Code Generator'), ('object_bloom_ai', 'Object Bloom AI')], default='bloom_ai', max_length=20)),
                ('auto_named', models.BooleanField(default=False, help_text='Whether the conversation has been auto-named')),
                ('args', models.JSONField(blank=True, help_text='Extra arguments for the conversation', null=True)),
                ('created_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI conversation',
                'verbose_name_plural': 'AI conversations',
                'db_table': 'bloomerp_ai_conversation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApplicationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(help_text='The name of the field.', max_length=100)),
                ('field_type', models.CharField(choices=[('Property', 'Property'), ('AutoField', 'Auto Field'), ('BigAutoField', 'Big Auto Field'), ('SmallAutoField', 'Small Auto Field'), ('CharField', 'Char Field'), ('TextField', 'Text Field'), ('EmailField', 'Email Field'), ('URLField', 'URL Field'), ('SlugField', 'Slug Field'), ('IntegerField', 'Integer Field'), ('FloatField', 'Float Field'), ('DecimalField', 'Decimal Field'), ('PositiveIntegerField', 'Positive Integer Field'), ('PositiveSmallIntegerField', 'Positive Small Integer Field'), ('BigIntegerField', 'Big Integer Field'), ('SmallIntegerField', 'Small Integer Field'), ('BooleanField', 'Boolean Field'), ('NullBooleanField', 'Null Boolean Field'), ('DateField', 'Date Field'), ('DateTimeField', 'DateTime Field'), ('TimeField', 'Time Field'), ('DurationField', 'Duration Field'), ('FileField', 'File Field'), ('ImageField', 'Image Field'), ('ForeignKey', 'Foreign Key'), ('OneToOneField', 'One To One Field'), ('ManyToManyField', 'Many To Many Field'), ('OneToManyField', 'One To Many Field'), ('UserField', 'User Field'), ('UUIDField', 'UUID Field'), ('BinaryField', 'Binary Field'), ('IPAddressField', 'IP Address Field'), ('GenericIPAddressField', 'Generic IP Address Field'), ('JSONField', 'JSON Field'), ('ArrayField', 'Array Field'), ('HStoreField', 'HStore Field'), ('GenericRelation', 'Generic Relation'), ('GenericForeignKey', 'Generic Foreign Key'), ('StatusField', 'Status Field'), ('BloomerpFileField', 'Bloomerp File Field')], help_text='The type of the field.', max_length=100)),
                ('meta', models.JSONField(blank=True, help_text='Additional metadata about the field.', null=True)),
                ('db_table', models.CharField(blank=True, help_text='The database table this field belongs to.', max_length=100, null=True)),
                ('db_field_type', models.CharField(blank=True, max_length=100, null=True)),
                ('db_column', models.CharField(blank=True, max_length=100, null=True)),
                ('content_type', models.ForeignKey(help_text='The content type (model) this field belongs to.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('related_model', models.ForeignKey(blank=True, help_text='Related model for ForeignKey, OneToOneField, ManyToManyField', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_models', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'bloomerp_application_field',
                'abstract': False,
                'managed': True,
                'default_permissions': ('add', 'change', 'delete', 'view', 'bulk_change', 'bulk_delete', 'bulk_add', 'export'),
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bloomerp_bookmark',
                'abstract': False,
                'managed': True,
                'default_permissions': ('add', 'change', 'delete', 'view', 'bulk_change', 'bulk_delete', 'bulk_add', 'export'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('object_id', models.CharField(max_length=36)),
                ('content', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bloomerp_comment',
                'abstract': False,
                'managed': True,
                'default_permissions': ('add', 'change', 'delete', 'view', 'bulk_change', 'bulk_delete', 'bulk_add', 'export'),
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplateFreeVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The name of the variable.', max_length=100)),
                ('help_text', models.CharField(blank=True, help_text='Help text for the variable that will be shown upon creation.', max_length=100, null=True)),
                ('variable_type', models.CharField(choices=[('date', 'Date'), ('boolean', 'Boolean'), ('text', 'Text'), ('list', 'List'), ('integer', 'Integer'), ('float', 'Decimal'), ('model', 'Model')], help_text='The type of the variable.', max_length=10)),
                ('options', models.TextField(blank=True, null=True)),
                ('required', models.BooleanField(default=False, help_text='Signifies whether the variable is required or not.')),
                ('created_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bloomerp_document_template_free_variable',
                'abstract': False,
                'managed': True,
                'default_permissions': ('add', 'change', 'delete', 'view', 'bulk_change', 'bulk_delete', 'bulk_add', 'export'),
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplateHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the template header.', max_length=100)),
                ('header', models.ImageField(help_text='Image of the header.', upload_to='document_templates/headers')),
                ('margin_top', models.FloatField(default=0.5, help_text='Top margin of the header in inches.')),
                ('margin_bottom', models.FloatField(default=0.0, help_text='Bottom margin of the header in inches.')),
                ('margin_left', models.FloatField(default=1.0, help_text='Left margin of the header in inches.')),
                ('margin_right', models.FloatField(default=1.0, help_text='Right margin of the header in inches.')),
                ('height', models.FloatField(default=1.0, help_text='Height of the header in inches.')),
                ('created_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bloomerp_document_template_header',
                'abstract': False,
                'managed': True,
                'default_permissions': ('add', 'change', 'delete', 'view', 'bulk_change', 'bulk_delete', 'bulk_add', 'export'),
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplateStyling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the document template styling.', max_length=100)),
                ('styling', bloomerp.model_fields.code_field.CodeField(default='', language='css')),
                ('created_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bloomerp_document_template_styling',
                'abstract': False,
                'managed': True,
                'default_permissions': ('add', 'change', 'delete', 'view', 'bulk_change', 'bulk_delete', 'bulk_add', 'export'),
            },
        ),
        migrations.CreateModel(
            name='FieldPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the field-level access control policy.', max_length=255)),
                ('rule', models.JSONField(help_text='A JSON representation of the field-level access control rules.')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Access Control Field Policy',
                'verbose_name_plural': 'Access Control Field Policies',
                'db_table': 'bloomerp_access_control_field_policy',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=bloomerp.models.files.file.File.upload_to)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=36, null=True)),
                ('persisted', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bloomerp_file',
                'abstract': False,
                'managed': True,
                'default_permissions': ('add', 'change', 'delete', 'view', 'bulk_change', 'bulk_delete', 'bulk_add', 'export'),
            },
        ),
        migrations.CreateModel(
            name='FileFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('content_types', models.ManyToManyField(help_text='Restrict folders to certain models.', to='contenttypes.contenttype', verbose_name='Models')),
                ('created_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(related_name='folders', to='bloomerp.file')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloomerp.filefolder')),
                ('updated_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bloomerp_file_folder',
                'abstract': False,
                'managed': True,
                'default_permissions': ('add', 'change', 'delete', 'view', 'bulk_change', 'bulk_delete', 'bulk_add', 'export'),
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the document template.', max_length=100)),
                ('template', bloomerp.model_fields.text_editor_field.TextEditorField(default='Hello world', help_text='Content of the template, including the variables.')),
                ('footer', models.TextField(blank=True, help_text='Footer content of the document template.', null=True)),
                ('page_orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', help_text='Orientation of the document template.', max_length=10)),
                ('page_size', models.CharField(choices=[('A4', 'A4'), ('letter', 'Letter'), ('A3', 'A3')], default='A4', help_text='Size of the document template.', max_length=10)),
                ('page_margin', models.FloatField(default=1.0, help_text='Margin of the document template in inches.')),
                ('include_page_numbers', models.BooleanField(default=True, help_text='Signifies whether the page numbers are included or not.')),
                ('created_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('model_variable', models.ForeignKey(blank=True, help_text='Model variable of the document template. Can be used to parse objects from the model into the template.', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('updated_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('free_variables', models.ManyToManyField(help_text='A free variable is a variable that is not from a model, and can be inserted in the template at creation time.', to='bloomerp.documenttemplatefreevariable')),
                ('template_header', models.ForeignKey(blank=True, help_text='Header of the document template.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloomerp.documenttemplateheader')),
                ('styling', models.ForeignKey(blank=True, help_text='Styling of the document template.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloomerp.documenttemplatestyling')),
                ('save_to_folder', models.ForeignKey(blank=True, help_text='Signifies to which folder a file generated from the template needs to be saved upon creation.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloomerp.filefolder')),
            ],
            options={
                'db_table': 'bloomerp_document_template',
                'abstract': False,
                'managed': True,
                'default_permissions': ('add', 'change', 'delete', 'view', 'bulk_change', 'bulk_delete', 'bulk_add', 'export'),
            },
        ),
        migrations.CreateModel(
            name='RowPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='The name of the row-level access control policy.', max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Access Control Row Policy',
                'verbose_name_plural': 'Access Control Row Policies',
                'db_table': 'bloomerp_access_control_row_policy',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The name of the access control policy.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A description of the access control policy.')),
                ('created_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('field_policy', models.ForeignKey(help_text='The field-level policy associated with this access control policy.', on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='bloomerp.fieldpolicy')),
                ('global_permissions', models.ManyToManyField(blank=True, help_text='Global permissions applied by this policy.', related_name='access_control_policies', to='auth.permission')),
                ('groups', models.ManyToManyField(blank=True, help_text='Groups assigned to this access control policy.', related_name='access_control_policies', to='auth.group')),
                ('updated_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, help_text='Users assigned to this access control policy.', related_name='access_control_policies', to=settings.AUTH_USER_MODEL)),
                ('row_policy', models.ForeignKey(help_text='The row-level policy associated with this access control policy.', on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='bloomerp.rowpolicy')),
            ],
            options={
                'verbose_name': 'Access Control Policy',
                'verbose_name_plural': 'Access Control Policies',
                'db_table': 'bloomerp_access_control_policy',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RowPolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.JSONField(help_text='A JSON representation of the row-level access control rule.')),
                ('permissions', models.ManyToManyField(related_name='row_policy_rules', to='auth.permission')),
                ('row_policy', models.ForeignKey(help_text='The row-level access control policy this rule belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='bloomerp.rowpolicy')),
            ],
            options={
                'verbose_name': 'Access Control Row Policy Rule',
                'verbose_name_plural': 'Access Control Row Policy Rules',
                'db_table': 'bloomerp_access_control_row_policy_rule',
            },
        ),
        migrations.CreateModel(
            name='SqlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('name', models.CharField(max_length=255)),
                ('query', bloomerp.model_fields.code_field.CodeField(help_text='SQL Query to execute', language='sql')),
                ('created_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SQL Query',
                'verbose_name_plural': 'SQL Queries',
                'db_table': 'sql_query',
                'permissions': [('execute_sql_query', 'Can execute SQL queries')],
                'abstract': False,
                'managed': True,
                'default_permissions': ('add', 'change', 'delete', 'view', 'bulk_change', 'bulk_delete', 'bulk_add', 'export'),
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('required_by', models.DateField(blank=True, help_text='The date by which the todo is required', null=True)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='The priority of the todo', max_length=20)),
                ('effort', models.IntegerField(blank=True, choices=[(1, 'XS'), (2, 'S'), (4, 'M'), (8, 'L'), (16, 'XL')], default=4, help_text='The effort required for the todo', null=True)),
                ('title', models.CharField(help_text='The name of the todo', max_length=255)),
                ('content', bloomerp.model_fields.text_editor_field.TextEditorField(blank=True, null=True)),
                ('datetime_completed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('duplicate', 'Duplicate')], default='backlog', max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=36, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, help_text='The user who requested the todo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_todos', to=settings.AUTH_USER_MODEL)),
                ('updated_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(blank=True, help_text='Labels assigned to the todo', to='bloomerp.todolabel')),
            ],
            options={
                'db_table': 'bloomerp_todo',
                'abstract': False,
                'managed': True,
                'default_permissions': ('add', 'change', 'delete', 'view', 'bulk_change', 'bulk_delete', 'bulk_add', 'export'),
            },
        ),
        migrations.CreateModel(
            name='UserDetailViewPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_layout', models.JSONField(default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_view_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bloomerp_user_detail_view_preference',
                'abstract': False,
                'managed': True,
                'default_permissions': ('add', 'change', 'delete', 'view', 'bulk_change', 'bulk_delete', 'bulk_add', 'export'),
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('name', models.CharField(help_text='Name of the widget', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the widget', null=True)),
                ('widget_type', models.CharField(choices=[('chart', 'CHART'), ('table', 'TABLE'), ('kpi', 'KPI'), ('link', 'LINK')], help_text='Type of widget', max_length=30)),
                ('schema', models.JSONField()),
                ('created_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('query', models.ForeignKey(help_text='SQL query that represents the entry point for the widget', on_delete=django.db.models.deletion.CASCADE, to='bloomerp.sqlquery')),
                ('updated_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bloomerp_widget',
                'abstract': False,
                'managed': True,
                'default_permissions': ('add', 'change', 'delete', 'view', 'bulk_change', 'bulk_delete', 'bulk_add', 'export'),
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_module_id', models.CharField(max_length=255)),
                ('module_id', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bloomerp_workspace',
                'abstract': False,
                'managed': True,
                'default_permissions': ('add', 'change', 'delete', 'view', 'bulk_change', 'bulk_delete', 'bulk_add', 'export'),
            },
        ),
        migrations.CreateModel(
            name='WidgetOnWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloomerp.widget')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloomerp.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='UserListViewPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_size', models.PositiveIntegerField(choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100')], default=25)),
                ('page_type', models.CharField(choices=[('pagination', 'Pagination'), ('infinite_scroll', 'Infinite Scroll')], default='pagination', max_length=20)),
                ('view_type', models.CharField(choices=[('table', 'Table'), ('kanban', 'Kanban'), ('calendar', 'Calendar'), ('gant', 'Gant'), ('pivot_table', 'Pivot')], default='table', max_length=50)),
                ('split_view_enabled', models.BooleanField(default=False)),
                ('calendar_view_mode', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], default='week', max_length=20)),
                ('display_fields', models.JSONField(default=bloomerp.models.users.user_list_view_preference.get_default_display_fields)),
                ('calendar_end_field', models.ForeignKey(blank=True, help_text='Optional end date field for calendar events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_end_preferences', to='bloomerp.applicationfield')),
                ('calendar_start_field', models.ForeignKey(blank=True, help_text='Start date field for calendar events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_start_preferences', to='bloomerp.applicationfield')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('kanban_group_by_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_preferences', to='bloomerp.applicationfield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_view_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bloomerp_user_list_view_pref',
                'unique_together': {('user', 'content_type')},
            },
        ),
    ]
