# Generated by Codex on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workspace",
            name="unique_default_workspace_per_user_module_context",
        ),
        migrations.RemoveField(
            model_name="workspace",
            name="sub_module_id",
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.UniqueConstraint(
                fields=("user", "module_id"),
                condition=models.Q(("is_default", True)),
                name="unique_default_workspace_per_user_module_context",
            ),
        ),
    ]
