# Generated by Django 5.1.1 on 2026-01-27 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bloomerp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rowpolicyrule",
            name="permissions",
        ),

        migrations.CreateModel(
            name='RowPolicyRulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('row_policy_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloomerp.rowpolicyrule')),
            ],
            options={
                'db_table': 'bloomerp_row_policy_rule_permission',
                'managed': True,
            },
        ),
        
        migrations.AddField(
            model_name="rowpolicyrule",
            name="permissions",
            field=models.ManyToManyField(
                to="auth.permission",
                through="bloomerp.RowPolicyRulePermission",
                related_name="row_policy_rules",
            ),
        ),
    ]
