# Generated by Django 5.1.1 on 2026-01-28 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0002_rowpolicyrulepermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationfield',
            options={'managed': True},
        ),
    ]
