# Generated by Django 5.1.1 on 2026-05-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0003_alter_aiconversation_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercreateviewpreference",
            name="name",
            field=models.CharField(
                default="Default",
                help_text="Optional name for this layout preference, for user reference",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="userdetailviewpreference",
            name="name",
            field=models.CharField(
                default="Default",
                help_text="Optional name for this layout preference, for user reference",
                max_length=255,
            ),
        ),
    ]
