# Generated by Django 5.1.1 on 2026-02-01 00:11

import bloomerp.model_fields.user_field
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0004_alter_applicationfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlistviewpreference',
            name='view_type',
            field=models.CharField(choices=[('table', 'Table'), ('kanban', 'Kanban'), ('card', 'Card'), ('calendar', 'Calendar'), ('gant', 'Gant'), ('pivot_table', 'Pivot')], default='table', max_length=50),
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The name of the workflow.', max_length=255)),
                ('created_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'db_table': 'bloomerp_workflow',
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('TRIGGER', 'Trigger'), ('ACTION', 'Action'), ('FLOW', 'Flow')], help_text='The type of the workflow node.', max_length=32)),
                ('config', models.JSONField(default=dict, help_text='The configuration for the workflow node.')),
                ('pos_x', models.IntegerField(help_text='The X position of the node in the workflow editor.')),
                ('pos_y', models.IntegerField(help_text='The Y position of the node in the workflow editor.')),
                ('created_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='bloomerp.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Node',
                'verbose_name_plural': 'Workflow Nodes',
                'db_table': 'bloomerp_workflow_node',
            },
        ),
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_node', models.ForeignKey(help_text='The node where this edge starts.', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='bloomerp.workflownode')),
                ('to_node', models.ForeignKey(help_text='The node where this edge ends.', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='bloomerp.workflownode')),
            ],
            options={
                'verbose_name': 'Workflow Edge',
                'verbose_name_plural': 'Workflow Edges',
                'db_table': 'bloomerp_workflow_edge',
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('created_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(help_text='The workflow associated with this run.', on_delete=django.db.models.deletion.CASCADE, to='bloomerp.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Run',
                'verbose_name_plural': 'Workflow Runs',
                'db_table': 'bloomerp_workflow_run',
            },
        ),
    ]
