# Generated by Django 5.1.1 on 2026-05-05 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0004_usercreateviewpreference_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userlistviewpreference",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="usercreateviewpreference",
            name="selected",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this preference is currently selected for the user. Only one preference per user and content type can be selected at a time.",
            ),
        ),
        migrations.AddField(
            model_name="userdetailviewpreference",
            name="selected",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this preference is currently selected for the user. Only one preference per user and content type can be selected at a time.",
            ),
        ),
        migrations.AddField(
            model_name="userlistviewpreference",
            name="name",
            field=models.CharField(
                default="Default",
                help_text="Optional name for this layout preference, for user reference",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="userlistviewpreference",
            name="selected",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this preference is currently selected for the user. Only one preference per user and content type can be selected at a time.",
            ),
        ),
        migrations.AlterField(
            model_name="usercreateviewpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userdetailviewpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userlistviewpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="usercreateviewpreference",
            constraint=models.UniqueConstraint(
                condition=django.db.models.Q(selected=True),
                fields=("user", "content_type"),
                name="unique_selected_create_view_preference",
            ),
        ),
        migrations.AddConstraint(
            model_name="userdetailviewpreference",
            constraint=models.UniqueConstraint(
                condition=django.db.models.Q(selected=True),
                fields=("user", "content_type"),
                name="unique_selected_detail_view_preference",
            ),
        ),
        migrations.AddConstraint(
            model_name="userlistviewpreference",
            constraint=models.UniqueConstraint(
                condition=django.db.models.Q(selected=True),
                fields=("user", "content_type"),
                name="unique_selected_list_view_preference",
            ),
        ),
    ]
