# Generated by Django 5.1.1 on 2026-02-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0005_alter_userlistviewpreference_view_type_workflow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='pos_x',
            field=models.IntegerField(default=0, help_text='The X position of the node in the workflow editor.'),
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='pos_y',
            field=models.IntegerField(default=0, help_text='The Y position of the node in the workflow editor.'),
        ),
    ]
