# Generated by Django 5.1.1 on 2026-05-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0005_alter_userlistviewpreference_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documenttemplate",
            name="free_variables",
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="page_size",
            field=models.CharField(
                choices=[("A4", "A4"), ("Letter", "Letter"), ("A3", "A3")],
                default="A4",
                help_text="Size of the document template.",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="DocumentTemplateFreeVariable",
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="free_variables",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
