# Generated by Codex on 2026-05-11

from django.db import migrations, models


def copy_model_variable_to_content_types(apps, schema_editor):
    DocumentTemplate = apps.get_model("bloomerp", "DocumentTemplate")
    db_alias = schema_editor.connection.alias

    for template in DocumentTemplate.objects.using(db_alias).exclude(model_variable_id__isnull=True):
        template.content_types.add(template.model_variable_id)


def copy_content_types_to_model_variable(apps, schema_editor):
    DocumentTemplate = apps.get_model("bloomerp", "DocumentTemplate")
    db_alias = schema_editor.connection.alias

    for template in DocumentTemplate.objects.using(db_alias).all():
        first_content_type = template.content_types.order_by("app_label", "model").first()
        if first_content_type is not None:
            template.model_variable_id = first_content_type.pk
            template.save(update_fields=["model_variable"])


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0006_remove_documenttemplate_free_variables_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttemplate",
            name="content_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Root object types that can be used as variables in the document template.",
                related_name="document_templates",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.RunPython(copy_model_variable_to_content_types, copy_content_types_to_model_variable),
        migrations.RemoveField(
            model_name="documenttemplate",
            name="model_variable",
        ),
    ]
