# Generated by Django 5.1.1 on 2026-05-12 16:21

import bloomerp.model_fields.text_editor_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0007_documenttemplate_content_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("Property", "Property"),
                    ("AutoField", "Auto Field"),
                    ("BigAutoField", "Big Auto Field"),
                    ("SmallAutoField", "Small Auto Field"),
                    ("CharField", "Char Field"),
                    ("ChoiceField", "Choice Field"),
                    ("TextField", "Text Field"),
                    ("EmailField", "Email Field"),
                    ("URLField", "URL Field"),
                    ("PhoneNumberField", "Phone Number Field"),
                    ("SlugField", "Slug Field"),
                    ("IntegerField", "Integer Field"),
                    ("FloatField", "Float Field"),
                    ("DecimalField", "Decimal Field"),
                    ("PositiveIntegerField", "Positive Integer Field"),
                    ("PositiveSmallIntegerField", "Positive Small Integer Field"),
                    ("BigIntegerField", "Big Integer Field"),
                    ("SmallIntegerField", "Small Integer Field"),
                    ("BooleanField", "Boolean Field"),
                    ("NullBooleanField", "Null Boolean Field"),
                    ("DateField", "Date Field"),
                    ("DateTimeField", "DateTime Field"),
                    ("TimeField", "Time Field"),
                    ("DurationField", "Duration Field"),
                    ("FileField", "File Field"),
                    ("ImageField", "Image Field"),
                    ("ForeignKey", "Foreign Key"),
                    ("OneToOneField", "One To One Field"),
                    ("ManyToManyField", "Many To Many Field"),
                    ("OneToManyField", "One To Many Field"),
                    ("UserField", "User Field"),
                    ("UUIDField", "UUID Field"),
                    ("BinaryField", "Binary Field"),
                    ("IPAddressField", "IP Address Field"),
                    ("GenericIPAddressField", "Generic IP Address Field"),
                    ("JSONField", "JSON Field"),
                    ("ArrayField", "Array Field"),
                    ("HStoreField", "HStore Field"),
                    ("GenericRelation", "Generic Relation"),
                    ("GenericForeignKey", "Generic Foreign Key"),
                    ("StatusField", "Status Field"),
                    ("IconField", "Icon Field"),
                    ("BloomerpFileField", "Bloomerp File Field"),
                ],
                help_text="The type of the field.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="template",
            field=bloomerp.model_fields.text_editor_field.TextEditorField(
                blank=True,
                default="Hello world",
                help_text="Content of the template, including the variables.",
            ),
        ),
    ]
