# Generated by Django 5.1.1 on 2026-02-13

import bloomerp.models.users.user_detail_view_preference
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0007_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailviewpreference',
            name='tab_state',
            field=models.JSONField(default=bloomerp.models.users.user_detail_view_preference.get_default_tab_state),
        ),
    ]
