# Generated by Django 5.1.1 on 2026-02-25 14:09

import bloomerp.model_fields.user_field
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0008_userdetailviewpreference_tab_state"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WidgetOnWorkspace",
            new_name="TileOnWorkspace",
        ),
        migrations.RemoveField(
            model_name="tileonworkspace",
            name="widget",
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="applicationfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("Property", "Property"),
                    ("AutoField", "Auto Field"),
                    ("BigAutoField", "Big Auto Field"),
                    ("SmallAutoField", "Small Auto Field"),
                    ("CharField", "Char Field"),
                    ("ChoiceField", "Choice Field"),
                    ("TextField", "Text Field"),
                    ("EmailField", "Email Field"),
                    ("URLField", "URL Field"),
                    ("SlugField", "Slug Field"),
                    ("IntegerField", "Integer Field"),
                    ("FloatField", "Float Field"),
                    ("DecimalField", "Decimal Field"),
                    ("PositiveIntegerField", "Positive Integer Field"),
                    ("PositiveSmallIntegerField", "Positive Small Integer Field"),
                    ("BigIntegerField", "Big Integer Field"),
                    ("SmallIntegerField", "Small Integer Field"),
                    ("BooleanField", "Boolean Field"),
                    ("NullBooleanField", "Null Boolean Field"),
                    ("DateField", "Date Field"),
                    ("DateTimeField", "DateTime Field"),
                    ("TimeField", "Time Field"),
                    ("DurationField", "Duration Field"),
                    ("FileField", "File Field"),
                    ("ImageField", "Image Field"),
                    ("ForeignKey", "Foreign Key"),
                    ("OneToOneField", "One To One Field"),
                    ("ManyToManyField", "Many To Many Field"),
                    ("OneToManyField", "One To Many Field"),
                    ("UserField", "User Field"),
                    ("UUIDField", "UUID Field"),
                    ("BinaryField", "Binary Field"),
                    ("IPAddressField", "IP Address Field"),
                    ("GenericIPAddressField", "Generic IP Address Field"),
                    ("JSONField", "JSON Field"),
                    ("ArrayField", "Array Field"),
                    ("HStoreField", "HStore Field"),
                    ("GenericRelation", "Generic Relation"),
                    ("GenericForeignKey", "Generic Foreign Key"),
                    ("StatusField", "Status Field"),
                    ("IconField", "Icon Field"),
                    ("BloomerpFileField", "Bloomerp File Field"),
                ],
                help_text="The type of the field.",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Tile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the widget", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the widget", null=True
                    ),
                ),
                ("schema", models.JSONField()),
                (
                    "created_by",
                    bloomerp.model_fields.user_field.UserField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "query",
                    models.ForeignKey(
                        help_text="SQL query that represents the entry point for the widget",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bloomerp.sqlquery",
                    ),
                ),
                (
                    "updated_by",
                    bloomerp.model_fields.user_field.UserField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bloomerp_tile",
                "abstract": False,
                "managed": True,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "bulk_change",
                    "bulk_delete",
                    "bulk_add",
                    "export",
                ),
            },
        ),
        migrations.AddField(
            model_name="tileonworkspace",
            name="tile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="bloomerp.tile",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Widget",
        ),
    ]
