# Generated by Django 5.1.1 on 2026-05-13 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0008_alter_applicationfield_field_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttemplate",
            name="styling",
            field=models.ForeignKey(
                blank=True,
                help_text="Signifies the styling to be applied to the document template",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bloomerp.documenttemplatestyling",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="datetime_completed",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="The date and time when the todo was completed",
                null=True,
            ),
        ),
    ]
