# Generated by Django 5.1.1 on 2026-03-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0010_workspace_layout"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tile",
            name="query",
        ),
        migrations.AlterField(
            model_name="workspace",
            name="module_id",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="sub_module_id",
            field=models.CharField(default="", max_length=255),
        ),
    ]
