# Generated by Django 5.1.1 on 2026-05-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0010_alter_applicationfield_field_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activitylog",
            old_name="user",
            new_name="actor",
        ),
        migrations.AddField(
            model_name="activitylog",
            name="is_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="source",
            field=models.CharField(default="DETAIL", max_length=12),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CHANGE", "Change"),
                    ("CREATE", "Create"),
                    ("DELETE", "Delete"),
                ],
                default="CHANGE",
                max_length=12,
            ),
        ),
    ]
