# Generated by Django 5.1.1 on 2026-05-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0011_rename_user_activitylog_actor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CHANGE", "Change"),
                    ("CREATE", "Create"),
                    ("DELETE", "Delete"),
                ],
                default="CHANGE",
                max_length=12,
            ),
        ),
    ]
