# Generated by Django 5.1.1 on 2026-04-05 08:13

import django.db.models.deletion
from django.db import migrations, models


def forwards_copy_folder_relationships(apps, schema_editor):
    File = apps.get_model("bloomerp", "File")
    FileFolder = apps.get_model("bloomerp", "FileFolder")

    through_model = FileFolder._meta.get_field("files").remote_field.through
    folder_content_type_through = FileFolder._meta.get_field("content_types").remote_field.through

    first_folder_by_file_id = {}
    for row in through_model.objects.order_by("file_id", "filefolder_id").values("file_id", "filefolder_id"):
        first_folder_by_file_id.setdefault(row["file_id"], row["filefolder_id"])

    for file_id, folder_id in first_folder_by_file_id.items():
        File.objects.filter(pk=file_id).update(folder_id=folder_id)

    folder_content_types = {}
    for row in folder_content_type_through.objects.order_by("filefolder_id", "contenttype_id").values(
        "filefolder_id",
        "contenttype_id",
    ):
        folder_content_types.setdefault(row["filefolder_id"], []).append(row["contenttype_id"])

    for folder_id, content_type_ids in folder_content_types.items():
        if len(content_type_ids) == 1:
            FileFolder.objects.filter(pk=folder_id).update(content_type_id=content_type_ids[0])


def backwards_copy_folder_relationships(apps, schema_editor):
    File = apps.get_model("bloomerp", "File")
    FileFolder = apps.get_model("bloomerp", "FileFolder")

    through_model = FileFolder._meta.get_field("files").remote_field.through
    folder_content_type_through = FileFolder._meta.get_field("content_types").remote_field.through

    for file in File.objects.exclude(folder_id__isnull=True).values("id", "folder_id"):
        through_model.objects.get_or_create(file_id=file["id"], filefolder_id=file["folder_id"])

    for folder in FileFolder.objects.exclude(content_type_id__isnull=True).values("id", "content_type_id"):
        folder_content_type_through.objects.get_or_create(
            filefolder_id=folder["id"],
            contenttype_id=folder["content_type_id"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0012_usercreateviewpreference"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files",
                to="bloomerp.filefolder",
            ),
        ),
        migrations.AddField(
            model_name="filefolder",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="filefolder",
            name="object_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.RunPython(
            forwards_copy_folder_relationships,
            backwards_copy_folder_relationships,
        ),
        migrations.RemoveField(
            model_name="filefolder",
            name="content_types",
        ),
        migrations.RemoveField(
            model_name="filefolder",
            name="files",
        ),
    ]
