# Generated by Django 5.1.1 on 2026-04-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0013_remove_filefolder_content_types_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filefolder",
            name="protected",
            field=models.BooleanField(
                default=False,
                help_text="Protected folders cannot be edited or deleted through the UI. This is useful for folders that are automatically created for objects, such as the module-level folders created for files.",
            ),
        ),
    ]
