# Generated by Django 5.1.1 on 2026-04-07 14:02

import bloomerp.model_fields.icon_field
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0014_filefolder_protected"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sidebar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        default="Default",
                        help_text="Name of the sidebar configuration.",
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bloomerp_sidebar",
            },
        ),
        migrations.CreateModel(
            name="SidebarItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the sidebar item.", max_length=255
                    ),
                ),
                (
                    "icon",
                    bloomerp.model_fields.icon_field.IconField(
                        help_text="Icon for the particular sidebar item.",
                        max_length=100,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="URL that the sidebar item points to.",
                        null=True,
                    ),
                ),
                ("is_folder", models.BooleanField(default=False)),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Position of the sidebar item among its siblings. Lower numbers appear first.",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="bloomerp.sidebaritem",
                    ),
                ),
                (
                    "sidebar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="bloomerp.sidebar",
                    ),
                ),
            ],
            options={
                "db_table": "bloomerp_sidebar_item",
            },
        ),
    ]
