# Generated by Django 5.1.1 on 2026-04-07 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0015_sidebar_sidebaritem"),
    ]

    operations = [
        migrations.AddField(
            model_name="sidebaritem",
            name="color",
            field=models.CharField(
                default="#E69B55",
                help_text="Hex color code for the sidebar item (e.g. #FF5733).",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="sidebar",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sidebars",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
