# Generated by Django 5.1.1 on 2026-04-10 17:20

import bloomerp.models.workspaces.tile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0017_alter_sidebaritem_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="type",
            field=models.CharField(
                choices=bloomerp.models.workspaces.tile.get_tile_type_choices,
                default="ANALYTICS_TILE",
                help_text="The type of tile",
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sidebaritem",
            name="color",
            field=models.CharField(
                default="#bfdbfe",
                help_text="Hex color code for the sidebar item (e.g. #FF5733).",
                max_length=7,
            ),
        ),
    ]
