# Generated by Django 5.1.1 on 2026-06-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0017_alter_workspace_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="form",
            name="initial_payload",
            field=models.JSONField(
                blank=True, default=dict, help_text="Initial payload for the form"
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="max_submissions",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum number of submissions possible for the form",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="name",
            field=models.CharField(
                default="Untitled form",
                help_text="The name of the form",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="requires_review",
            field=models.BooleanField(
                default=True,
                help_text="Whether the form submission needs to be reviewed before it is persisted.",
            ),
        ),
    ]
