# Generated by Django 5.1.1 on 2026-04-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0018_tile_type_alter_sidebaritem_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="auto_generated",
            field=models.BooleanField(default=False),
        ),
    ]
