# Generated by Django 5.1.1 on 2026-06-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0019_formsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="closes_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time after which the form will no longer accept submissions.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="max_submissions_per_ip",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum number of submissions per IP address",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="opens_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time from which the form will accept submissions.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="requires_authentication",
            field=models.BooleanField(
                default=False,
                help_text="Whether the form requires an authenticated user in order to be accessible.",
            ),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
