# Generated by Django 5.1.1 on 2026-04-11 10:13

import bloomerp.model_fields.icon_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0019_tile_auto_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="icon",
            field=bloomerp.model_fields.icon_field.IconField(
                default="fa fa-chart-simple", max_length=100
            ),
        ),
    ]
