# Generated by Django 5.1.1 on 2026-04-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0020_tile_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="is_default",
            field=models.BooleanField(
                default=False, help_text="Whether it is a default workspace"
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="name",
            field=models.CharField(default="Default", max_length=255),
        ),
    ]
