# Generated by Django 5.1.1 on 2026-04-12 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0021_workspace_is_default_workspace_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="shared_with",
            field=models.ManyToManyField(
                related_name="shared_workspaces", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
