# Generated by Django 5.1.1 on 2026-06-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0021_add_files_relation_field_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="run_asynchronously",
            field=models.BooleanField(
                default=False, help_text="Whether runs asynchronously"
            ),
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="persisted",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Whether the form was persisted",
            ),
        ),
    ]
