# Generated by Django 5.1.1 on 2026-06-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0021_add_files_relation_field_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlistviewpreference",
            name="options",
            field=models.JSONField(default=dict),
        ),
    ]
