# Generated by Django 5.1.1 on 2026-06-09 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0022_workflow_run_asynchronously_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowrun",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="workflowrun",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="workflow",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Whether the workflow is active or not"
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="enable_logging",
            field=models.BooleanField(
                default=False,
                help_text="Whether to enable logging for this workflow. Disabling logging may improve performance but will result in no detailed execution history being stored.",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowRunStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="The sequence number of this step within the workflow run."
                    ),
                ),
                (
                    "action_id",
                    models.CharField(
                        help_text="The identifier of the action being executed in this step.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "Completed"), ("FAILED", "Failed")],
                        default="COMPLETED",
                        help_text="The status of this workflow run step.",
                        max_length=20,
                    ),
                ),
                (
                    "workflow_run",
                    models.ForeignKey(
                        help_text="The workflow run that this step belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="bloomerp.workflowrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Run Step",
                "verbose_name_plural": "Workflow Run Steps",
                "db_table": "bloomerp_workflow_run_step",
            },
        ),
    ]
