# Generated by Django 5.1.1 on 2026-04-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0022_workspace_shared_with"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tileonworkspace",
            name="tile",
        ),
        migrations.RemoveField(
            model_name="tileonworkspace",
            name="workspace",
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user", "module_id", "sub_module_id"),
                name="unique_default_workspace_per_user_module_context",
            ),
        ),
        migrations.DeleteModel(
            name="TileOnWorkspace",
        ),
    ]
