# Generated by Django 5.1.1 on 2026-06-11 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0023_remove_workflowrun_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlistviewpreference",
            name="calendar_end_field",
        ),
        migrations.RemoveField(
            model_name="userlistviewpreference",
            name="calendar_start_field",
        ),
        migrations.RemoveField(
            model_name="userlistviewpreference",
            name="calendar_view_mode",
        ),
        migrations.RemoveField(
            model_name="userlistviewpreference",
            name="kanban_group_by_field",
        ),
        migrations.RemoveField(
            model_name="userlistviewpreference",
            name="page_size",
        ),
        migrations.RemoveField(
            model_name="userlistviewpreference",
            name="page_type",
        ),
        migrations.AddField(
            model_name="userlistviewpreference",
            name="options",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="workflow",
            field=models.ForeignKey(
                editable=False,
                help_text="The workflow associated with this run.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="bloomerp.workflow",
            ),
        ),
    ]
