# Generated by Django 5.1.1 on 2026-06-12 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0023_remove_workflowrun_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflownode",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="The name of the workflow node.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="workflow",
            field=models.ForeignKey(
                editable=False,
                help_text="The workflow associated with this run.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="bloomerp.workflow",
            ),
        ),
    ]
