# Generated by Django 5.1.1 on 2026-06-12 18:23

import bloomerp.model_fields.user_field
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0025_apikey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apikey",
            name="avatar",
        ),
        migrations.AlterField(
            model_name="apikey",
            name="created_by",
            field=bloomerp.model_fields.user_field.UserField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="last_used_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="revoked_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="updated_by",
            field=bloomerp.model_fields.user_field.UserField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
