# Generated by Django 5.1.1 on 2026-06-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0024_remove_userlistviewpreference_calendar_end_field_and_more"),
        ("bloomerp", "0026_remove_apikey_avatar_alter_apikey_created_by_and_more"),
    ]

    operations = []
