# Generated by Django 5.1.1 on 2026-06-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0027_merge_20260618_1245"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlistviewpreference",
            name="default_filters",
            field=models.JSONField(default=dict),
        ),
    ]
