# Generated by Django 5.1.1 on 2026-06-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0028_userlistviewpreference_default_filters"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="public_embed_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether the form can be embedded in a public page.",
            ),
        ),
    ]
