# Generated by Django 5.1.1 on 2026-06-22 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0029_form_public_embed_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formsubmission",
            name="form",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="bloomerp.form",
            ),
        ),
    ]
