# Generated by Django 5.1.1 on 2026-06-23 17:45

import bloomerp.model_fields.code_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0030_alter_formsubmission_form"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documenttemplate",
            name="styling",
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="custom_styling",
            field=bloomerp.model_fields.code_field.CodeField(
                blank=True,
                default="",
                help_text="Custom CSS styling for the document template.",
                language="css",
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="style_sets",
            field=models.ManyToManyField(
                blank=True,
                help_text="Styling sets that can be applied to the document template.",
                related_name="document_templates",
                to="bloomerp.documenttemplatestyling",
            ),
        ),
    ]
