# Generated by Django 5.1.1 on 2026-06-24 20:03

import bloomerp.model_fields.code_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0031_remove_documenttemplate_styling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowedge',
            name='name',
            field=models.CharField(blank=True, help_text='A descriptive name for the edge.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicationfield',
            name='field_type',
            field=models.CharField(choices=[('Property', 'Property'), ('AutoField', 'Auto Field'), ('BigAutoField', 'Big Auto Field'), ('SmallAutoField', 'Small Auto Field'), ('CharField', 'Char Field'), ('CodeField', 'Code Field'), ('ChoiceField', 'Choice Field'), ('TextField', 'Text Field'), ('EmailField', 'Email Field'), ('URLField', 'URL Field'), ('AddressField', 'Address Field'), ('PhoneNumberField', 'Phone Number Field'), ('SlugField', 'Slug Field'), ('IntegerField', 'Integer Field'), ('FloatField', 'Float Field'), ('DecimalField', 'Decimal Field'), ('PositiveIntegerField', 'Positive Integer Field'), ('PositiveSmallIntegerField', 'Positive Small Integer Field'), ('BigIntegerField', 'Big Integer Field'), ('SmallIntegerField', 'Small Integer Field'), ('BooleanField', 'Boolean Field'), ('NullBooleanField', 'Null Boolean Field'), ('DateField', 'Date Field'), ('WeekField', 'Week Field'), ('DateTimeField', 'DateTime Field'), ('TimeField', 'Time Field'), ('DurationField', 'Duration Field'), ('FileField', 'File Field'), ('ImageField', 'Image Field'), ('ForeignKey', 'Foreign Key'), ('OneToOneField', 'One To One Field'), ('ManyToManyField', 'Many To Many Field'), ('OneToManyField', 'One To Many Field'), ('UserField', 'User Field'), ('UUIDField', 'UUID Field'), ('BinaryField', 'Binary Field'), ('IPAddressField', 'IP Address Field'), ('GenericIPAddressField', 'Generic IP Address Field'), ('JSONField', 'JSON Field'), ('ArrayField', 'Array Field'), ('HStoreField', 'HStore Field'), ('GenericRelation', 'Generic Relation'), ('GenericForeignKey', 'Generic Foreign Key'), ('StatusField', 'Status Field'), ('IconField', 'Icon Field'), ('BloomerpFileField', 'Bloomerp File Field'), ('FilesRelationField', 'Files')], help_text='The type of the field.', max_length=100),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='custom_styling',
            field=bloomerp.model_fields.code_field.CodeField(blank=True, default='\np {\n    font-size: 11pt;\n    line-height: 1.5;\n    margin: 0 0 8pt 0;\n}\np:last-child {\n    margin-bottom: 0;\n}\nh1 {\n    font-size: 24px;\n    font-weight: bold;\n}\nh2 {\n    font-size: 20px;\n    font-weight: bold;\n}\nh3 {\n    font-size: 18px;\n    font-weight: bold;\n}\nul {\n    list-style-type: disc;\n    margin-left: 20px;\n}\nol {\n    list-style-type: decimal;\n    margin-left: 20px;\n}\ntable {\n    border-collapse: collapse;\n    width: 100%;\n}\nth, td {\n    border: 1px solid black;\n    padding: 8px;\n    text-align: left;\n}\n\n', help_text='Custom CSS styling for the document template.', language='css'),
        ),
    ]
