# Generated by Django 5.1.1 on 2026-06-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0033_todolabel_avatar_todolabel_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolabel',
            name='avatar',
        ),
    ]
