# Generated by Django 5.1.1 on 2026-06-26 10:20

import bloomerp.model_fields.user_field
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0034_remove_todolabel_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='backlog', max_length=20)),
                ('name', models.CharField(help_text='The name of the initiative', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(blank=True, help_text='Labels assigned to the initiative', related_name='initiatives', to='bloomerp.todolabel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_initiatives', to=settings.AUTH_USER_MODEL)),
                ('updated_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bloomerp_initiative',
                'abstract': False,
                'managed': True,
                'default_permissions': ('add', 'change', 'delete', 'view', 'bulk_change', 'bulk_delete', 'bulk_add', 'export'),
            },
        ),
        migrations.AddField(
            model_name='todo',
            name='initiative',
            field=models.ForeignKey(blank=True, help_text='The initiative this todo belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='bloomerp.initiative'),
        ),
    ]
