# Generated by Django 5.1.1 on 2026-09-10 12:55

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F


def backfill_workflow_run_lifecycle(apps, schema_editor):
    WorkflowRun = apps.get_model("bloomerp", "WorkflowRun")
    WorkflowRun.objects.update(
        status="SUCCEEDED",
        started_at=F("datetime_created"),
        finished_at=F("datetime_updated"),
    )
    WorkflowRun.objects.filter(steps__status="CANCELLED").update(
        status="CANCELLED",
    )
    WorkflowRun.objects.filter(steps__status="FAILED").update(
        status="FAILED",
    )
    WorkflowRun.objects.filter(steps__status="PAUSED").update(
        status="PAUSED",
        finished_at=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0067_workflowedge_output_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Finished At'),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='start_node',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_workflow_runs', to='bloomerp.workflownode', verbose_name='Start Node'),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Started At'),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', editable=False, max_length=20, verbose_name='Status'),
        ),
        migrations.RunPython(
            backfill_workflow_run_lifecycle,
            migrations.RunPython.noop,
        ),
    ]
