# Generated by Django 5.1.1 on 2026-09-13 20:30

import bloomerp.model_fields.user_field
import bloomerp.models.filters.filter
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0068_workflowrun_finished_at_workflowrun_start_node_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime Updated')),
                ('name', models.CharField(max_length=255)),
                ('filters', models.JSONField(blank=True, default=list, validators=[bloomerp.models.filters.filter.validate_filter_groups])),
                ('scope', models.CharField(choices=[('model', 'Model'), ('workspace', 'Workspace')], max_length=16)),
                ('identifier', models.CharField(max_length=255)),
                ('created_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'bloomerp_filter',
                'ordering': ['name', 'pk'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_add', 'bulk_change', 'bulk_delete'),
                'constraints': [models.UniqueConstraint(fields=('scope', 'identifier', 'name'), name='unique_saved_filter_scope_name'), models.CheckConstraint(condition=models.Q(('scope__in', ['model', 'workspace'])), name='saved_filter_valid_scope')],
            },
        ),
    ]
