# Generated by Django 5.1.1 on 2026-09-18 13:29

from django.db import migrations, models


def _module_scope_key(content_type):
    from django.apps import apps as django_apps

    from bloomerp.modules.definition import module_registry

    try:
        model = django_apps.get_model(content_type.app_label, content_type.model)
    except LookupError:
        model = None

    if model is not None:
        module = module_registry.get_module_for_model(model)
        if module is not None:
            module_id = getattr(module, "full_id", None) or module.id
            root_module = module_registry.get_root(module_id)
            if root_module is not None:
                module_id = getattr(root_module, "full_id", None) or root_module.id
                return f"module:{module_id}"

    return f"module:app:{content_type.app_label}"


def _merge_folder_group(FileFolder, File, DocumentTemplate, folder_ids):
    folders = list(
        FileFolder.objects.filter(pk__in=folder_ids).order_by(
            "datetime_created", "pk"
        )
    )
    canonical = folders[0]
    for duplicate in folders[1:]:
        File.objects.filter(folder_id=duplicate.pk).update(folder_id=canonical.pk)
        DocumentTemplate.objects.filter(save_to_folder_id=duplicate.pk).update(
            save_to_folder_id=canonical.pk
        )
        FileFolder.objects.filter(parent_id=duplicate.pk).update(parent_id=canonical.pk)
        duplicate.delete()
    return canonical


def populate_file_folder_identities(apps, schema_editor):
    FileFolder = apps.get_model("bloomerp", "FileFolder")
    File = apps.get_model("bloomerp", "File")
    DocumentTemplate = apps.get_model("bloomerp", "DocumentTemplate")
    ContentType = apps.get_model("contenttypes", "ContentType")

    folders = {
        folder.pk: folder
        for folder in FileFolder.objects.all().order_by("datetime_created", "pk")
    }
    content_types = {
        content_type.pk: content_type
        for content_type in ContentType.objects.all()
    }

    model_folder_ids = set()
    for folder in folders.values():
        parent = folders.get(folder.parent_id)
        if (
            folder.protected
            and folder.content_type_id is not None
            and folder.object_id is None
            and parent is not None
            and parent.protected
            and parent.parent_id is None
            and parent.content_type_id is None
            and parent.object_id is None
        ):
            model_folder_ids.add(folder.pk)

    object_folder_ids = set()
    for folder in folders.values():
        parent = folders.get(folder.parent_id)
        if (
            folder.protected
            and folder.content_type_id is not None
            and folder.object_id is not None
            and parent is not None
            and parent.pk in model_folder_ids
            and parent.content_type_id == folder.content_type_id
        ):
            object_folder_ids.add(folder.pk)

    identities = {}
    for folder_id in model_folder_ids:
        folder = folders[folder_id]
        content_type = content_types.get(folder.content_type_id)
        if content_type is not None:
            identities[folder_id] = (
                "model",
                f"model:{content_type.app_label}.{content_type.model}",
            )

    for folder_id in object_folder_ids:
        folder = folders[folder_id]
        content_type = content_types.get(folder.content_type_id)
        if content_type is not None:
            identities[folder_id] = (
                "object",
                (
                    f"object:{content_type.app_label}.{content_type.model}:"
                    f"{folder.object_id}"
                ),
            )

    module_folder_ids = {
        folders[folder_id].parent_id for folder_id in model_folder_ids
    }
    for folder_id in module_folder_ids:
        child_content_types = {
            content_types[folders[child_id].content_type_id]
            for child_id in model_folder_ids
            if folders[child_id].parent_id == folder_id
            and folders[child_id].content_type_id in content_types
        }
        scope_keys = {
            _module_scope_key(content_type)
            for content_type in child_content_types
        }
        if len(scope_keys) == 1:
            identities[folder_id] = ("module", scope_keys.pop())

    groups = {}
    for folder_id, (kind, scope_key) in identities.items():
        groups.setdefault((kind, scope_key), []).append(folder_id)

    kind_order = {"object": 0, "model": 1, "module": 2}
    for (kind, scope_key), folder_ids in sorted(
        groups.items(), key=lambda item: kind_order[item[0][0]]
    ):
        canonical = _merge_folder_group(
            FileFolder,
            File,
            DocumentTemplate,
            folder_ids,
        )
        FileFolder.objects.filter(pk=canonical.pk).update(
            kind=kind,
            scope_key=scope_key,
            protected=True,
        )


def reset_file_folder_identities(apps, schema_editor):
    FileFolder = apps.get_model("bloomerp", "FileFolder")
    FileFolder.objects.update(kind="manual", scope_key=None)


class Migration(migrations.Migration):

    dependencies = [
        ("bloomerp", "0071_dataview_option_field_names"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="filefolder",
            name="kind",
            field=models.CharField(
                choices=[
                    ("module", "Module"),
                    ("model", "Model"),
                    ("object", "Object"),
                    ("manual", "Manual"),
                ],
                default="manual",
                editable=False,
                max_length=16,
                verbose_name="Kind",
            ),
        ),
        migrations.AddField(
            model_name="filefolder",
            name="scope_key",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=512,
                null=True,
                verbose_name="Scope key",
            ),
        ),
        migrations.RunPython(
            populate_file_folder_identities,
            reset_file_folder_identities,
        ),
        migrations.AddConstraint(
            model_name="filefolder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "manual"), ("scope_key__isnull", True)),
                    models.Q(
                        models.Q(("kind", "manual"), _negated=True),
                        ("scope_key__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="file_folder_kind_scope_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="filefolder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_key__isnull", False)),
                fields=("scope_key",),
                name="unique_file_folder_scope_key",
            ),
        ),
    ]
