# Generated by Django 5.1.1 on 2026-09-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0072_filefolder_system_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='success_text',
            field=models.TextField(blank=True, help_text='Text shown after a successful form submission.', null=True, verbose_name='Success Text'),
        ),
    ]
