# Generated by Django 5.1.1 on 2025-09-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0074_remove_sqlqueryfilter_column_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='content',
        ),
    ]
