# Generated by Django 5.1.1 on 2025-09-11 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0075_remove_workspace_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlquery',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='options',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='output_type',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='name',
        ),
        migrations.AddField(
            model_name='widget',
            name='schema',
            field=models.JSONField(default={'hey': 'dude'}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('chart', 'CHART'), ('table', 'TABLE'), ('kpi', 'KPI'), ('link', 'LINK')], default='kpi', help_text='Type of widget', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspace',
            name='module_id',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspace',
            name='sub_module_id',
            field=models.CharField(default='2', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='widget',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the widget', null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='name',
            field=models.CharField(help_text='Name of the widget', max_length=255),
        ),
        migrations.AlterField(
            model_name='widget',
            name='query',
            field=models.ForeignKey(help_text='SQL query that represents the entry point for the widget', on_delete=django.db.models.deletion.CASCADE, to='bloomerp.sqlquery'),
        ),
        migrations.CreateModel(
            name='WidgetOnWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloomerp.widget')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloomerp.workspace')),
            ],
        ),
        migrations.DeleteModel(
            name='SqlQueryFilter',
        ),
    ]
