# Generated by Django 5.1.1 on 2025-11-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0076_remove_sqlquery_filters_remove_widget_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserListViewPreference',
            new_name='UserListViewField',
        ),
    ]
