# Generated by Django 5.1.1 on 2026-10-02 14:14

from typing import Any, ClassVar

import django.db.models.deletion
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.operations.base import Operation
from django.db.migrations.state import StateApps


def migrate_metadata(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Move historical document and bulk-import provenance into nested metadata."""
    file_model = apps.get_model("bloomerp", "File")
    for file in file_model.objects.using(schema_editor.connection.alias).iterator():
        meta: dict[str, Any] = dict(file.meta or {})
        if "document_template_id" in meta:
            meta["document_template"] = {
                "id": meta.pop("document_template_id"),
                "name": meta.pop("document_template_name", ""),
            }
        if (
            "document_template" in meta
            and meta["document_template"] is not None
            and not isinstance(meta["document_template"], dict)
        ):
            template_id = str(meta["document_template"])
            template_model = apps.get_model("bloomerp", "DocumentTemplate")
            template_name = (
                template_model.objects.using(schema_editor.connection.alias)
                .filter(pk=template_id)
                .values_list("name", flat=True)
                .first()
                or ""
            )
            meta["document_template"] = {"id": template_id, "name": template_name}
        if any(key in meta for key in ("signed", "user", "signed_file_id")):
            signature = {"signed": meta.pop("signed", False)}
            if "user" in meta:
                signature["user_id"] = meta.pop("user")
            if "signed_file_id" in meta:
                signature["signed_file_id"] = meta.pop("signed_file_id")
            meta["signature"] = signature
        if meta.pop("bulk_upload_draft", False):
            meta["bulk_upload"] = {
                "content_type_id": meta.pop("content_type_id"),
                "model_label": meta.pop("model_label"),
                "original_filename": meta.pop("original_filename", ""),
            }
            meta.pop("upload_type", None)
        if meta != file.meta:
            file_model.objects.using(schema_editor.connection.alias).filter(
                pk=file.pk
            ).update(meta=meta)


def restore_metadata(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Restore legacy provenance keys when rolling back the metadata migration."""
    file_model = apps.get_model("bloomerp", "File")
    for file in file_model.objects.using(schema_editor.connection.alias).iterator():
        meta: dict[str, Any] = dict(file.meta or {})
        document = meta.pop("document_template", None)
        if document is not None:
            meta.update(
                document_template_id=document["id"],
                document_template_name=document["name"],
            )
        signature = meta.pop("signature", None)
        if signature is not None:
            meta["signed"] = signature["signed"]
            if "user_id" in signature:
                meta["user"] = signature["user_id"]
            if "signed_file_id" in signature:
                meta["signed_file_id"] = signature["signed_file_id"]
        bulk_upload = meta.pop("bulk_upload", None)
        if bulk_upload is not None:
            meta.update(bulk_upload, bulk_upload_draft=True, upload_type="bulk_upload")
        file_model.objects.using(schema_editor.connection.alias).filter(
            pk=file.pk
        ).update(meta=meta)


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("bloomerp", "0076_emailaccount_save_sent_emails"),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.CreateModel(
            name="FileFieldReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(max_length=36)),
                (
                    "application_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_field_references",
                        to="bloomerp.applicationfield",
                    ),
                ),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_reference",
                        to="bloomerp.file",
                    ),
                ),
            ],
            options={
                "db_table": "bloomerp_file_field_reference",
                "indexes": [
                    models.Index(
                        fields=["application_field", "object_id"],
                        name="file_ref_field_object_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(migrate_metadata, restore_metadata),
    ]
