# Generated by Django 5.1.1 on 2026-10-04 15:38

import bloomerp.agents.providers.registry
import bloomerp.model_fields.user_field
import bloomerp.models.agents.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Replace legacy conversations and create the final BloomAI schema in one step."""

    replaces = [
        ("bloomerp", "0078_delete_legacy_ai_conversation"),
        ("bloomerp", "0079_agent_persistence"),
        ("bloomerp", "0080_aimodel_aiconversation_selected_model"),
        ("bloomerp", "0081_aimodel_approval_rules_aimodel_capabilities"),
        ("bloomerp", "0082_remove_agent_monetary_configuration"),
        ("bloomerp", "0083_remove_aimodel_capabilities_and_more"),
        ("bloomerp", "0084_conversation_tool_approvals"),
        ("bloomerp", "0085_rename_ai_model_to_ai_agent"),
        ("bloomerp", "0086_remove_aiagent_avatar_aiagentaccess"),
        ("bloomerp", "0087_mcp_integration_connection"),
        ("bloomerp", "0088_mcp_integration_oauth_configuration"),
        ("bloomerp", "0089_aiagent_tool_configuration"),
        ("bloomerp", "0090_aitoolcall_tool_title"),
        ("bloomerp", "0091_aiagent_resource_configuration"),
    ]

    dependencies = [
        ("bloomerp", "0077_file_field_references"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AIConversation",
        ),
        migrations.CreateModel(
            name="AIAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datetime Created"
                    ),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Datetime Updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name shown in the chat agent selector.",
                        max_length=255,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=bloomerp.agents.providers.registry.provider_choices,
                        help_text="Registered provider used to validate settings and construct the runtime.",
                        max_length=100,
                        verbose_name="AI Provider",
                    ),
                ),
                (
                    "model_identifier",
                    models.CharField(
                        help_text="Model identifier accepted by the provider, separate from the display name.",
                        max_length=255,
                        verbose_name="Provider Model Identifier",
                    ),
                ),
                (
                    "default_instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Base instructions captured when a new run starts with this agent.",
                        verbose_name="System Instructions",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Allow permitted users to select this agent for new runs.",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "credentials_encrypted",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        editable=False,
                        help_text="Versioned encryption metadata and encrypted provider credentials. Configure or rotate values through set_credentials; plaintext is never stored here.",
                        verbose_name="Encrypted Credentials",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-validated model controls. A max_tokens parameter limits output per response, separate from the total run token budget.",
                        verbose_name="Provider Parameters",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional provider API endpoint. Leave blank to use the provider default; exclude credentials and query parameters.",
                        null=True,
                        verbose_name="Provider Endpoint",
                    ),
                ),
                (
                    "request_timeout_seconds",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Timeout for an individual provider request, separate from the total run duration.",
                        verbose_name="Request Timeout (Seconds)",
                    ),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(
                        blank=True,
                        default=20000,
                        help_text="Maximum total input and output tokens across all attempts of one run. Leave blank for no run token limit.",
                        null=True,
                        verbose_name="Maximum Tokens per Run",
                    ),
                ),
                (
                    "max_tool_calls",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum cumulative tool calls across all attempts of one run. Leave blank for no tool-call limit.",
                        null=True,
                        verbose_name="Maximum Tool Calls per Run",
                    ),
                ),
                (
                    "max_duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        default=300,
                        help_text="Maximum cumulative execution time across all attempts of one run. Leave blank for no duration limit.",
                        null=True,
                        verbose_name="Maximum Run Duration (Seconds)",
                    ),
                ),
                (
                    "internal_tool_mode",
                    models.CharField(
                        choices=[
                            ("all", "All built-in Bloomerp tools"),
                            ("selected", "Selected built-in Bloomerp tools only"),
                        ],
                        default="all",
                        help_text="All includes newly registered tools. Selected with no tools allows none. User permissions still apply.",
                        max_length=10,
                        verbose_name="Built-in Bloomerp tool access",
                    ),
                ),
                (
                    "internal_tools",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Stable MCP tool names. Unavailable tools cannot run. Used only when access is set to selected tools.",
                        verbose_name="Selected built-in Bloomerp tools",
                    ),
                ),
                (
                    "internal_resource_mode",
                    models.CharField(
                        choices=[
                            ("all", "All built-in Bloomerp resources"),
                            ("selected", "Selected built-in Bloomerp resources only"),
                        ],
                        default="all",
                        help_text="All includes newly registered resources. Selected with no resources allows none. User permissions still apply.",
                        max_length=10,
                        verbose_name="Built-in Bloomerp resource access",
                    ),
                ),
                (
                    "internal_resources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Stable MCP resource URIs or URI templates. Unavailable resources cannot be read. Used only for selected resource access.",
                        verbose_name="Selected built-in Bloomerp resources",
                    ),
                ),
                (
                    "created_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "db_table": "bloomerp_ai_agent",
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                    "bulk_add",
                    "bulk_change",
                    "bulk_delete",
                ),
                "verbose_name": "AI Agent",
                "verbose_name_plural": "AI Agents",
            },
        ),
        migrations.CreateModel(
            name="AIAgentAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datetime Created"
                    ),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Datetime Updated"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "created_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Members of these groups may use this agent.",
                        related_name="ai_agent_access_grants",
                        to="auth.group",
                        verbose_name="Groups",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Agent that these users and groups may use.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access",
                        to="bloomerp.aiagent",
                        verbose_name="AI Agent",
                    ),
                ),
                (
                    "updated_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who may use this agent.",
                        related_name="ai_agent_access_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Users",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Agent Access",
                "verbose_name_plural": "AI Agent Access",
                "db_table": "bloomerp_ai_agent_access",
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                    "bulk_add",
                    "bulk_change",
                    "bulk_delete",
                ),
            },
        ),
        migrations.CreateModel(
            name="AIConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datetime Created"
                    ),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Datetime Updated"
                    ),
                ),
                ("title", models.CharField(default="AI conversation", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("archived", "Archived")],
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "approval_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Conversation approval policy for new tool calls. Can be changed during a conversation; pending approvals still require a decision.",
                        verbose_name="Tool Approval Rules",
                    ),
                ),
                (
                    "created_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "selected_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="bloomerp.aiagent",
                    ),
                ),
                (
                    "updated_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "db_table": "bloomerp_ai_conversation",
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                    "bulk_add",
                    "bulk_change",
                    "bulk_delete",
                ),
            },
        ),
        migrations.CreateModel(
            name="AIMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datetime Created"
                    ),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Datetime Updated"
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "content_blocks",
                    bloomerp.models.agents.fields.AgentJSONField(
                        blank=True, default=list, schema="message.v1"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("streaming", "Streaming"),
                            ("completed", "Completed"),
                            ("interrupted", "Interrupted"),
                        ],
                        default="completed",
                        max_length=16,
                    ),
                ),
                (
                    "schema_version",
                    models.PositiveIntegerField(choices=[(1, "Version 1")], default=1),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="bloomerp.aiconversation",
                    ),
                ),
                (
                    "created_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "db_table": "bloomerp_ai_message",
                "ordering": ["sequence"],
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                    "bulk_add",
                    "bulk_change",
                    "bulk_delete",
                ),
            },
        ),
        migrations.CreateModel(
            name="AIArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datetime Created"
                    ),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Datetime Updated"
                    ),
                ),
                ("kind", models.CharField(max_length=100)),
                ("schema_version", models.PositiveIntegerField(default=1)),
                (
                    "payload",
                    bloomerp.models.agents.fields.AgentJSONField(schema="object.v1"),
                ),
                (
                    "created_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="ai_artifacts",
                        to="bloomerp.file",
                    ),
                ),
                (
                    "previous_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="revisions",
                        to="bloomerp.aiartifact",
                    ),
                ),
                (
                    "updated_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="bloomerp.aiconversation",
                    ),
                ),
                (
                    "created_by_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="created_artifacts",
                        to="bloomerp.aimessage",
                    ),
                ),
            ],
            options={
                "db_table": "bloomerp_ai_artifact",
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                    "bulk_add",
                    "bulk_change",
                    "bulk_delete",
                ),
            },
        ),
        migrations.CreateModel(
            name="AIMessageArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datetime Created"
                    ),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Datetime Updated"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="message_links",
                        to="bloomerp.aiartifact",
                    ),
                ),
                (
                    "created_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact_links",
                        to="bloomerp.aimessage",
                    ),
                ),
                (
                    "updated_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "db_table": "bloomerp_ai_message_artifact",
                "ordering": ["position"],
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                    "bulk_add",
                    "bulk_change",
                    "bulk_delete",
                ),
            },
        ),
        migrations.CreateModel(
            name="AIRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datetime Created"
                    ),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Datetime Updated"
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("message", "Message"),
                            ("schedule", "Schedule"),
                            ("event", "External event"),
                        ],
                        default="message",
                        max_length=16,
                    ),
                ),
                (
                    "trigger_context",
                    bloomerp.models.agents.fields.AgentJSONField(
                        blank=True, default=dict, schema="object.v1"
                    ),
                ),
                ("agent_key", models.CharField(max_length=100)),
                ("agent_version", models.CharField(max_length=100)),
                (
                    "config_snapshot",
                    bloomerp.models.agents.fields.AgentJSONField(schema="config.v1"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("waiting", "Waiting"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "origin_browser_context",
                    bloomerp.models.agents.fields.AgentJSONField(
                        blank=True, null=True, schema="browser.v1"
                    ),
                ),
                (
                    "checkpoint",
                    bloomerp.models.agents.fields.AgentJSONField(
                        blank=True, null=True, schema="object.v1"
                    ),
                ),
                ("checkpoint_runtime", models.CharField(blank=True, max_length=100)),
                ("checkpoint_version", models.PositiveIntegerField(default=1)),
                (
                    "consumed_message_sequence",
                    models.PositiveBigIntegerField(default=0),
                ),
                (
                    "wait_condition",
                    bloomerp.models.agents.fields.AgentJSONField(
                        blank=True, null=True, schema="wait.v1"
                    ),
                ),
                ("resume_after", models.DateTimeField(blank=True, null=True)),
                ("cancel_requested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "budgets",
                    bloomerp.models.agents.fields.AgentJSONField(
                        blank=True, default=dict, schema="budgets.v1"
                    ),
                ),
                (
                    "usage",
                    bloomerp.models.agents.fields.AgentJSONField(
                        blank=True, default=dict, schema="usage.v1"
                    ),
                ),
                (
                    "error",
                    bloomerp.models.agents.fields.AgentJSONField(
                        blank=True, null=True, schema="error.v1"
                    ),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="bloomerp.aiconversation",
                    ),
                ),
                (
                    "created_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="initiated_ai_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trigger_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="triggered_runs",
                        to="bloomerp.aimessage",
                    ),
                ),
                (
                    "updated_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "db_table": "bloomerp_ai_run",
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                    "bulk_add",
                    "bulk_change",
                    "bulk_delete",
                ),
            },
        ),
        migrations.AddField(
            model_name="aimessage",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="messages",
                to="bloomerp.airun",
            ),
        ),
        migrations.CreateModel(
            name="AIRunAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datetime Created"
                    ),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Datetime Updated"
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[("inline", "Inline"), ("worker", "Worker")],
                        max_length=16,
                    ),
                ),
                ("executor_id", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("lease_token", models.UUIDField(unique=True)),
                ("lease_expires_at", models.DateTimeField()),
                ("heartbeat_at", models.DateTimeField()),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "usage",
                    bloomerp.models.agents.fields.AgentJSONField(
                        blank=True, default=dict, schema="usage.v1"
                    ),
                ),
                (
                    "error",
                    bloomerp.models.agents.fields.AgentJSONField(
                        blank=True, null=True, schema="error.v1"
                    ),
                ),
                (
                    "created_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="bloomerp.airun",
                    ),
                ),
                (
                    "updated_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "db_table": "bloomerp_ai_run_attempt",
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                    "bulk_add",
                    "bulk_change",
                    "bulk_delete",
                ),
            },
        ),
        migrations.CreateModel(
            name="AIRunEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datetime Created"
                    ),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Datetime Updated"
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField()),
                ("event_type", models.CharField(max_length=100)),
                (
                    "schema_version",
                    models.PositiveIntegerField(choices=[(1, "Version 1")], default=1),
                ),
                (
                    "payload",
                    bloomerp.models.agents.fields.AgentJSONField(
                        blank=True, default=dict, schema="event.v1"
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="events",
                        to="bloomerp.airunattempt",
                    ),
                ),
                (
                    "created_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="bloomerp.airun",
                    ),
                ),
                (
                    "updated_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "db_table": "bloomerp_ai_run_event",
                "ordering": ["sequence"],
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                    "bulk_add",
                    "bulk_change",
                    "bulk_delete",
                ),
            },
        ),
        migrations.CreateModel(
            name="AIToolCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datetime Created"
                    ),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Datetime Updated"
                    ),
                ),
                ("tool_identifier", models.CharField(max_length=255)),
                ("tool_version", models.CharField(max_length=100)),
                ("provider_call_id", models.CharField(max_length=255)),
                (
                    "idempotency_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("waiting", "Waiting for approval"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("unknown", "Outcome requires reconciliation"),
                        ],
                        default="proposed",
                        max_length=16,
                    ),
                ),
                (
                    "arguments",
                    bloomerp.models.agents.fields.AgentJSONField(
                        blank=True, default=dict, schema="object.v1"
                    ),
                ),
                (
                    "proposal_hash",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "result",
                    bloomerp.models.agents.fields.AgentJSONField(
                        blank=True, null=True, schema="object.v1"
                    ),
                ),
                (
                    "error",
                    bloomerp.models.agents.fields.AgentJSONField(
                        blank=True, null=True, schema="error.v1"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tool_title",
                    models.CharField(blank=True, default="", max_length=511),
                ),
                (
                    "created_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "first_dispatch_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="first_dispatched_tool_calls",
                        to="bloomerp.airunattempt",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_calls",
                        to="bloomerp.airun",
                    ),
                ),
                (
                    "updated_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "db_table": "bloomerp_ai_tool_call",
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                    "bulk_add",
                    "bulk_change",
                    "bulk_delete",
                ),
            },
        ),
        migrations.AddField(
            model_name="aiartifact",
            name="created_by_tool_call",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="created_artifacts",
                to="bloomerp.aitoolcall",
            ),
        ),
        migrations.CreateModel(
            name="AIApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datetime Created"
                    ),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Datetime Updated"
                    ),
                ),
                (
                    "requirement_snapshot",
                    bloomerp.models.agents.fields.AgentJSONField(
                        schema="approval_requirement.v1"
                    ),
                ),
                (
                    "proposal_snapshot",
                    bloomerp.models.agents.fields.AgentJSONField(schema="proposal.v1"),
                ),
                (
                    "proposal_hash",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="decided_ai_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "required_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="assigned_ai_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "tool_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="bloomerp.aitoolcall",
                    ),
                ),
            ],
            options={
                "db_table": "bloomerp_ai_approval",
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                    "bulk_add",
                    "bulk_change",
                    "bulk_delete",
                ),
            },
        ),
        migrations.CreateModel(
            name="MCPIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datetime Created"
                    ),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Datetime Updated"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "endpoint_url",
                    models.URLField(max_length=2048, verbose_name="Endpoint URL"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Enabled")),
                (
                    "connection_mode",
                    models.CharField(
                        choices=[("shared", "Shared"), ("personal", "Personal")],
                        default="shared",
                        max_length=10,
                    ),
                ),
                (
                    "authentication_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("api_key", "API key"),
                            ("oauth", "OAuth"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "oauth_client_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional pre-registered OAuth client ID. Leave blank for automatic client registration.",
                        max_length=2048,
                    ),
                ),
                (
                    "oauth_scopes",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional space-separated OAuth scopes; a server challenge takes precedence.",
                        max_length=1000,
                    ),
                ),
                (
                    "created_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP Integration",
                "verbose_name_plural": "MCP Integrations",
                "db_table": "bloomerp_mcp_integration",
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                    "bulk_add",
                    "bulk_change",
                    "bulk_delete",
                ),
            },
        ),
        migrations.CreateModel(
            name="MCPConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datetime Created"
                    ),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Datetime Updated"
                    ),
                ),
                (
                    "credentials_encrypted",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("expired", "Expired"),
                            ("error", "Error"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    bloomerp.model_fields.user_field.UserField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="bloomerp.mcpintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP Connection",
                "verbose_name_plural": "MCP Connections",
                "db_table": "bloomerp_mcp_connection",
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                    "bulk_add",
                    "bulk_change",
                    "bulk_delete",
                ),
            },
        ),
        migrations.AddField(
            model_name="aiagent",
            name="mcp_integrations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tools from enabled external integrations are available to this agent. Shared integrations use their shared connection; personal integrations require the acting user's existing connection. Missing or expired connections require reconnecting.",
                related_name="ai_agents",
                to="bloomerp.mcpintegration",
                verbose_name="External MCP integrations",
            ),
        ),
        migrations.AddIndex(
            model_name="aiconversation",
            index=models.Index(
                fields=["owner", "-datetime_updated"], name="ai_conv_owner_updated"
            ),
        ),
        migrations.AddConstraint(
            model_name="aimessageartifact",
            constraint=models.UniqueConstraint(
                fields=("message", "position"), name="ai_message_artifact_position"
            ),
        ),
        migrations.AddIndex(
            model_name="airun",
            index=models.Index(fields=["status", "resume_after"], name="ai_run_wakeup"),
        ),
        migrations.AddConstraint(
            model_name="airun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["queued", "running", "waiting"])),
                fields=("conversation",),
                name="ai_one_unfinished_run",
            ),
        ),
        migrations.AddConstraint(
            model_name="airun",
            constraint=models.CheckConstraint(
                condition=models.Q(("checkpoint_version__gte", 1)),
                name="ai_checkpoint_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="aimessage",
            constraint=models.UniqueConstraint(
                fields=("conversation", "sequence"), name="ai_message_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="aimessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gte", 1)),
                name="ai_message_sequence_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="airunattempt",
            index=models.Index(
                fields=["status", "lease_expires_at"], name="ai_attempt_expiry"
            ),
        ),
        migrations.AddConstraint(
            model_name="airunattempt",
            constraint=models.UniqueConstraint(
                fields=("run", "number"), name="ai_attempt_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="airunattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "running")),
                fields=("run",),
                name="ai_one_active_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="airunattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("number__gte", 1)),
                name="ai_attempt_number_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="airunevent",
            constraint=models.UniqueConstraint(
                fields=("run", "sequence"), name="ai_run_event_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="airunevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gte", 1)),
                name="ai_event_sequence_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="aitoolcall",
            constraint=models.UniqueConstraint(
                fields=("run", "provider_call_id"), name="ai_tool_provider_call"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("previous_revision", models.F("id")), _negated=True
                ),
                name="ai_artifact_not_own_revision",
            ),
        ),
        migrations.AddIndex(
            model_name="aiapproval",
            index=models.Index(
                fields=["status", "expires_at"], name="ai_approval_expiry"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiapproval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("decided_at__isnull", False),
                        ("decided_by__isnull", False),
                        ("status__in", ["approved", "rejected"]),
                    ),
                    models.Q(
                        ("decided_at__isnull", True),
                        ("decided_by__isnull", True),
                        ("status__in", ["pending", "expired", "cancelled"]),
                    ),
                    _connector="OR",
                ),
                name="ai_approval_decision_actor",
            ),
        ),
        migrations.AddConstraint(
            model_name="mcpconnection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("integration",),
                name="mcp_connection_unique_shared",
            ),
        ),
        migrations.AddConstraint(
            model_name="mcpconnection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("integration", "user"),
                name="mcp_connection_unique_personal",
            ),
        ),
    ]
