# Generated by Django 5.1.1 on 2026-10-04 17:18

import bloomerp.models.files.file_extraction
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloomerp', '0078_bloomai_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('unavailable', 'Unavailable'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('start_deadline', models.DateTimeField(default=bloomerp.models.files.file_extraction.extraction_start_deadline)),
                ('expires_at', models.DateTimeField(default=bloomerp.models.files.file_extraction.extraction_expiry)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('result', models.FileField(blank=True, max_length=255, upload_to='bloomerp/extractions/%Y/%m/%d')),
                ('manifest', models.JSONField(default=dict)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloomerp.file')),
            ],
            options={
                'db_table': 'bloomerp_file_extraction',
                'default_permissions': (),
                'indexes': [models.Index(fields=['status', 'expires_at'], name='file_extract_status_exp_idx')],
            },
        ),
    ]
