# Generated by Django 5.1.1 on 2026-10-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bloomerp", "0078_bloomai_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiagentaccess",
            name="all_authenticated_users",
            field=models.BooleanField(
                default=False,
                help_text="Allow all active authenticated users to use this agent.",
                verbose_name="All Authenticated Users",
            ),
        ),
        migrations.AddField(
            model_name="aiagentaccess",
            name="all_staff_users",
            field=models.BooleanField(
                default=False,
                help_text="Allow all active staff users to use this agent.",
                verbose_name="All Staff Users",
            ),
        ),
    ]
