# Generated by Django 5.1.1 on 2026-10-04 22:18

import bloomerp.model_fields.user_field
import bloomerp.models.files.file_extraction
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0078_bloomai_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime Updated')),
                ('created_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('source_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloomerp.file', verbose_name='Source File')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('unavailable', 'Unavailable'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='queued', max_length=16, verbose_name='Status')),
                ('started_at', models.DateTimeField(null=True, verbose_name='Started At')),
                ('finished_at', models.DateTimeField(null=True, verbose_name='Finished At')),
                ('start_deadline', models.DateTimeField(default=bloomerp.models.files.file_extraction.extraction_start_deadline, verbose_name='Start Deadline')),
                ('expires_at', models.DateTimeField(default=bloomerp.models.files.file_extraction.extraction_expiry, verbose_name='Expires At')),
                ('error_code', models.CharField(blank=True, max_length=40, verbose_name='Error Code')),
                ('result', models.FileField(blank=True, max_length=255, upload_to='bloomerp/extractions/%Y/%m/%d', verbose_name='Result')),
                ('manifest', bloomerp.models.files.file_extraction.ManifestJSONField(blank=True, default=dict, verbose_name='Manifest')),
            ],
            options={
                'verbose_name': 'File Extraction',
                'verbose_name_plural': 'File Extractions',
                'db_table': 'bloomerp_file_extraction',
                'default_permissions': (),
                'indexes': [models.Index(fields=['status', 'expires_at'], name='file_extract_status_exp_idx')],
                'constraints': [],
            },
        ),
    ]
