# Generated by Django 5.1.1 on 2025-11-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0078_userlistviewpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistviewpreference',
            name='page_type',
            field=models.CharField(choices=[('pagination', 'Pagination'), ('infinite_scroll', 'Infinite Scroll')], default='pagination', max_length=20),
        ),
    ]
