# Generated by Django 5.1.1 on 2026-09-29 13:35

import bloomerp.models.agents.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bloomerp", "0078_agent_persistence"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("streaming", "Streaming"),
                    ("completed", "Completed"),
                    ("interrupted", "Interrupted"),
                ],
                default="completed",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="airunattempt",
            name="usage",
            field=bloomerp.models.agents.fields.AgentJSONField(
                blank=True, default=dict, schema="usage.v1"
            ),
        ),
    ]
