# Generated by Django 5.1.1 on 2025-11-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0079_userlistviewpreference_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistviewpreference',
            name='split_view_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userlistviewpreference',
            name='page_size',
            field=models.PositiveIntegerField(choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100')], default=25),
        ),
        migrations.AlterField(
            model_name='userlistviewpreference',
            name='view_type',
            field=models.CharField(choices=[('table', 'Table'), ('kanban', 'Kanban'), ('calendar', 'Calendar')], default='table', max_length=50),
        ),
    ]
