# Generated by Django 5.1.1 on 2026-10-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0079_ai_agent_access_audiences'),
        ('bloomerp', '0079_file_extraction'),
    ]

    operations = [
    ]
