# Generated by Django 5.1.1 on 2026-10-05 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0080_merge_20261005_1008'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_email_account',
            field=models.ForeignKey(blank=True, help_text='Preferred sender when composing outside an inbox.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='bloomerp.emailaccount', verbose_name='Default Email Account'),
        ),
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('document_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloomerp.documenttemplate')),
                ('email_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloomerp.emailaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Draft',
                'verbose_name_plural': 'Email Drafts',
                'db_table': 'bloomerp_email_draft',
            },
        ),
    ]
