# Generated by Django 5.1.1 on 2025-11-27 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0080_userlistviewpreference_split_view_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistviewpreference',
            name='kanban_group_by_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloomerp.applicationfield'),
        ),
    ]
