# Generated by Django 5.1.1 on 2026-10-05 21:20

import bloomerp.model_fields.user_field
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def preserve_template_references(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Keep legacy single-template references in the draft's multi-template payload."""
    draft_model = apps.get_model("bloomerp", "EmailDraft")
    drafts = draft_model.objects.using(schema_editor.connection.alias).exclude(document_template_id=None)
    for draft in drafts.iterator():
        if "document_template_ids" not in draft.payload:
            draft.payload["document_template_ids"] = [str(draft.document_template_id)]
            draft.save(using=schema_editor.connection.alias, update_fields=["payload"])


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0081_email_composer_drafts_and_default_sender'),
    ]

    operations = [
        migrations.RunPython(preserve_template_references, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='emaildraft',
            name='document_template',
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='created_by',
            field=bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Datetime Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='updated_by',
            field=bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='emaildraft',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Datetime Updated'),
        ),
        migrations.AlterField(
            model_name='emaildraft',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
