# Generated by Django 5.1.1 on 2025-11-27 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0081_userlistviewpreference_kanban_group_by_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistviewpreference',
            name='calendar_date_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_date_preferences', to='bloomerp.applicationfield'),
        ),
        migrations.AddField(
            model_name='userlistviewpreference',
            name='calendar_end_date_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_end_date_preferences', to='bloomerp.applicationfield'),
        ),
        migrations.AddField(
            model_name='userlistviewpreference',
            name='calendar_title_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_title_preferences', to='bloomerp.applicationfield'),
        ),
        migrations.AlterField(
            model_name='userlistviewpreference',
            name='kanban_group_by_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_preferences', to='bloomerp.applicationfield'),
        ),
    ]
