# Generated by Django 5.1.1 on 2025-11-28 14:23

import bloomerp.models.user_list_view_preference
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0082_userlistviewpreference_calendar_date_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlistviewpreference',
            name='calendar_date_field',
        ),
        migrations.RemoveField(
            model_name='userlistviewpreference',
            name='calendar_end_date_field',
        ),
        migrations.RemoveField(
            model_name='userlistviewpreference',
            name='calendar_title_field',
        ),
        migrations.AddField(
            model_name='userlistviewpreference',
            name='display_fields',
            field=models.JSONField(default=bloomerp.models.user_list_view_preference.get_default_display_fields),
        ),
        migrations.AlterField(
            model_name='userlistviewpreference',
            name='kanban_group_by_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloomerp.applicationfield'),
        ),
    ]
