# Generated by Django 5.1.1 on 2026-10-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0082_email_draft_bloomerp_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileextraction',
            options={'verbose_name': 'File Extraction', 'verbose_name_plural': 'File Extractions'},
        ),
    ]
