# Generated by Django 5.1.1 on 2025-11-28 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0083_remove_userlistviewpreference_calendar_date_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlistviewpreference',
            name='kanban_group_by_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_preferences', to='bloomerp.applicationfield'),
        ),
        migrations.AlterModelTable(
            name='userlistviewpreference',
            table='bloomerp_user_list_view_pref',
        ),
    ]
