# Generated by Django 5.1.1 on 2025-11-28 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0084_alter_userlistviewpreference_kanban_group_by_field_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='todo',
            name='effort',
            field=models.IntegerField(blank=True, choices=[(1, 'XS'), (2, 'S'), (4, 'M'), (8, 'L'), (16, 'XL')], default=4, help_text='The effort required for the todo', null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('duplicate', 'Duplicate')], default='backlog', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationfield',
            name='content_type',
            field=models.ForeignKey(help_text='The content type (model) this field belongs to.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='applicationfield',
            name='db_table',
            field=models.CharField(blank=True, help_text='The database table this field belongs to.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicationfield',
            name='field',
            field=models.CharField(help_text='The name of the field.', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicationfield',
            name='field_type',
            field=models.CharField(choices=[('Property', 'Property'), ('AutoField', 'Auto Field'), ('BigAutoField', 'Big Auto Field'), ('SmallAutoField', 'Small Auto Field'), ('CharField', 'Char Field'), ('TextField', 'Text Field'), ('EmailField', 'Email Field'), ('URLField', 'URL Field'), ('SlugField', 'Slug Field'), ('IntegerField', 'Integer Field'), ('FloatField', 'Float Field'), ('DecimalField', 'Decimal Field'), ('PositiveIntegerField', 'Positive Integer Field'), ('PositiveSmallIntegerField', 'Positive Small Integer Field'), ('BigIntegerField', 'Big Integer Field'), ('SmallIntegerField', 'Small Integer Field'), ('BooleanField', 'Boolean Field'), ('NullBooleanField', 'Null Boolean Field'), ('DateField', 'Date Field'), ('DateTimeField', 'DateTime Field'), ('TimeField', 'Time Field'), ('DurationField', 'Duration Field'), ('FileField', 'File Field'), ('ImageField', 'Image Field'), ('ForeignKey', 'Foreign Key'), ('OneToOneField', 'One To One Field'), ('ManyToManyField', 'Many To Many Field'), ('OneToManyField', 'One To Many Field'), ('UUIDField', 'UUID Field'), ('BinaryField', 'Binary Field'), ('IPAddressField', 'IP Address Field'), ('GenericIPAddressField', 'Generic IP Address Field'), ('JSONField', 'JSON Field'), ('ArrayField', 'Array Field'), ('HStoreField', 'HStore Field'), ('GenericRelation', 'Generic Relation'), ('GenericForeignKey', 'Generic Foreign Key'), ('StatusField', 'Status Field'), ('BloomerpFileField', 'Bloomerp File Field')], help_text='The type of the field.', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicationfield',
            name='meta',
            field=models.JSONField(blank=True, help_text='Additional metadata about the field.', null=True),
        ),
        migrations.AlterField(
            model_name='applicationfield',
            name='related_model',
            field=models.ForeignKey(blank=True, help_text='Related model for ForeignKey, OneToOneField, ManyToManyField', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_models', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='The priority of the todo'),
        ),
    ]
