# Generated by Django 5.1.1 on 2025-11-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0085_remove_todo_is_completed_todo_effort_todo_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='The priority of the todo', max_length=20),
        ),
    ]
