# Generated by Django 5.1.1 on 2025-11-28 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0086_alter_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistviewpreference',
            name='calendar_end_field',
            field=models.ForeignKey(blank=True, help_text='Optional end date field for calendar events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_end_preferences', to='bloomerp.applicationfield'),
        ),
        migrations.AddField(
            model_name='userlistviewpreference',
            name='calendar_start_field',
            field=models.ForeignKey(blank=True, help_text='Start date field for calendar events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_start_preferences', to='bloomerp.applicationfield'),
        ),
    ]
