# Generated by Django 5.1.1 on 2025-11-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0087_userlistviewpreference_calendar_end_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistviewpreference',
            name='calendar_view_mode',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], default='week', max_length=20),
        ),
    ]
