# Generated by Django 5.1.1 on 2025-12-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0088_userlistviewpreference_calendar_view_mode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdetailviewpreference',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userdetailviewpreference',
            name='field_layout',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userlistviewpreference',
            name='view_type',
            field=models.CharField(choices=[('table', 'Table'), ('kanban', 'Kanban'), ('calendar', 'Calendar'), ('gant', 'Gant'), ('pivot_table', 'Pivot')], default='table', max_length=50),
        ),
        migrations.RemoveField(
            model_name='userdetailviewpreference',
            name='application_field',
        ),
        migrations.RemoveField(
            model_name='userdetailviewpreference',
            name='position',
        ),
    ]
