# Generated by Django 5.1.1 on 2026-01-09 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bloomerp', '0090_userdetailviewpreference_content_type'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('add', 'Add'), ('change', 'Change'), ('delete', 'Delete'), ('bulk_add', 'Bulk Add'), ('bulk_change', 'Bulk Change'), ('bulk_delete', 'Bulk Delete'), ('export', 'Export')], max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('rule', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('groups', models.ManyToManyField(blank=True, help_text='Groups this policy applies to.', related_name='row_policies', to='auth.group')),
                ('users', models.ManyToManyField(blank=True, help_text='Users this policy applies to.', related_name='row_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bloomerp_row_policy',
                'indexes': [models.Index(fields=['content_type', 'action'], name='bloomerp_ro_content_8fc5c5_idx')],
            },
        ),
    ]
