# Generated by Django 5.1.1 on 2026-01-23 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bloomerp', '0091_rowpolicy'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the field-level access control policy.', max_length=255)),
                ('rule', models.JSONField(help_text='A JSON representation of the field-level access control rules.')),
            ],
            options={
                'verbose_name': 'Access Control Field Policy',
                'verbose_name_plural': 'Access Control Field Policies',
                'db_table': 'bloomerp_access_control_field_policy',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The name of the access control policy.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A description of the access control policy.')),
            ],
            options={
                'verbose_name': 'Access Control Policy',
                'verbose_name_plural': 'Access Control Policies',
                'db_table': 'bloomerp_access_control_policy',
            },
        ),
        migrations.CreateModel(
            name='RowPolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.JSONField(help_text='A JSON representation of the row-level access control rule.')),
            ],
            options={
                'verbose_name': 'Access Control Row Policy Rule',
                'verbose_name_plural': 'Access Control Row Policy Rules',
                'db_table': 'bloomerp_access_control_row_policy_rule',
            },
        ),
        migrations.CreateModel(
            name='TodoLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'bloomerp_todo_label',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='rowpolicy',
            options={'verbose_name': 'Access Control Row Policy', 'verbose_name_plural': 'Access Control Row Policies'},
        ),
        migrations.RemoveIndex(
            model_name='rowpolicy',
            name='bloomerp_ro_content_8fc5c5_idx',
        ),
        migrations.RemoveField(
            model_name='rowpolicy',
            name='action',
        ),
        migrations.RemoveField(
            model_name='rowpolicy',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='rowpolicy',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='rowpolicy',
            name='users',
        ),
        migrations.AlterField(
            model_name='rowpolicy',
            name='name',
            field=models.CharField(blank=True, default='', help_text='The name of the row-level access control policy.', max_length=255),
        ),
        migrations.AlterModelTable(
            name='rowpolicy',
            table='bloomerp_access_control_row_policy',
        ),
        migrations.AddField(
            model_name='fieldpolicy',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='policy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='field_policy',
            field=models.ForeignKey(help_text='The field-level policy associated with this access control policy.', on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='bloomerp.fieldpolicy'),
        ),
        migrations.AddField(
            model_name='policy',
            name='row_policy',
            field=models.ForeignKey(help_text='The row-level policy associated with this access control policy.', on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='bloomerp.rowpolicy'),
        ),
        migrations.AddField(
            model_name='policy',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rowpolicyrule',
            name='permissions',
            field=models.ManyToManyField(related_name='row_policy_rules', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='rowpolicyrule',
            name='row_policy',
            field=models.ForeignKey(help_text='The row-level access control policy this rule belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='bloomerp.rowpolicy'),
        ),
        migrations.AddField(
            model_name='todo',
            name='labels',
            field=models.ManyToManyField(blank=True, help_text='Labels assigned to the todo', to='bloomerp.todolabel'),
        ),
    ]
