# Generated by Django 5.1.1 on 2026-01-23 17:23

import bloomerp.model_fields.user_field
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0092_fieldpolicy_policy_rowpolicyrule_todolabel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconversation',
            name='created_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='updated_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationfield',
            name='field_type',
            field=models.CharField(choices=[('Property', 'Property'), ('AutoField', 'Auto Field'), ('BigAutoField', 'Big Auto Field'), ('SmallAutoField', 'Small Auto Field'), ('CharField', 'Char Field'), ('TextField', 'Text Field'), ('EmailField', 'Email Field'), ('URLField', 'URL Field'), ('SlugField', 'Slug Field'), ('IntegerField', 'Integer Field'), ('FloatField', 'Float Field'), ('DecimalField', 'Decimal Field'), ('PositiveIntegerField', 'Positive Integer Field'), ('PositiveSmallIntegerField', 'Positive Small Integer Field'), ('BigIntegerField', 'Big Integer Field'), ('SmallIntegerField', 'Small Integer Field'), ('BooleanField', 'Boolean Field'), ('NullBooleanField', 'Null Boolean Field'), ('DateField', 'Date Field'), ('DateTimeField', 'DateTime Field'), ('TimeField', 'Time Field'), ('DurationField', 'Duration Field'), ('FileField', 'File Field'), ('ImageField', 'Image Field'), ('ForeignKey', 'Foreign Key'), ('OneToOneField', 'One To One Field'), ('ManyToManyField', 'Many To Many Field'), ('OneToManyField', 'One To Many Field'), ('UserField', 'User Field'), ('UUIDField', 'UUID Field'), ('BinaryField', 'Binary Field'), ('IPAddressField', 'IP Address Field'), ('GenericIPAddressField', 'Generic IP Address Field'), ('JSONField', 'JSON Field'), ('ArrayField', 'Array Field'), ('HStoreField', 'HStore Field'), ('GenericRelation', 'Generic Relation'), ('GenericForeignKey', 'Generic Foreign Key'), ('StatusField', 'Status Field'), ('BloomerpFileField', 'Bloomerp File Field')], help_text='The type of the field.', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='created_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='updated_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documenttemplatefreevariable',
            name='created_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documenttemplatefreevariable',
            name='updated_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documenttemplateheader',
            name='created_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documenttemplateheader',
            name='updated_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documenttemplatestyling',
            name='created_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documenttemplatestyling',
            name='updated_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filefolder',
            name='created_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filefolder',
            name='updated_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policy',
            name='created_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policy',
            name='updated_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sqlquery',
            name='created_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sqlquery',
            name='updated_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='updated_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='widget',
            name='created_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='widget',
            name='updated_by',
            field=bloomerp.model_fields.user_field.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
