# Generated by Django 5.1.1 on 2026-01-25 01:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bloomerp', '0093_alter_aiconversation_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='global_permissions',
            field=models.ManyToManyField(blank=True, help_text='Global permissions applied by this policy.', related_name='access_control_policies', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='policy',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups assigned to this access control policy.', related_name='access_control_policies', to='auth.group'),
        ),
        migrations.AddField(
            model_name='policy',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users assigned to this access control policy.', related_name='access_control_policies', to=settings.AUTH_USER_MODEL),
        ),
    ]
