# Generated by manage.py generate_test_cases.
from datetime import timedelta

from django.contrib.auth import get_user_model
from django.db import IntegrityError
from django.utils import timezone

from bloomerp.models.auth.oauth import OAuthAuthorizationCode
from bloomerp.oauth import hash_oauth_secret
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
    ExpectedModelException,
)


class TestOAuthAuthorizationCodeModel(BloomerpModelTestCase):
    """Exercise OAuth authorization-code persistence and constraints."""

    model = OAuthAuthorizationCode

    def setUp(self) -> None:
        """Create the account associated with authorization-code scenarios."""
        self.user = get_user_model().objects.create_user(
            username="oauth-code-owner", password="test-password"
        )
        self.raw_code = "single-use-authorization-code"

    def _code_fields(self) -> dict[str, object]:
        """Build a complete authorization code using a digest, not the raw code."""
        return {
            "code_hash": hash_oauth_secret(self.raw_code),
            "user": self.user,
            "client_id": "registered-client",
            "redirect_uri": "https://chatgpt.com/connector/oauth/demo",
            "resource": "https://bloomerp.example/mcp",
            "scope": "mcp:tools",
            "code_challenge": "a" * 43,
            "expires_at": timezone.now() + timedelta(minutes=5),
        }

    def _create_existing_code(self) -> None:
        """Seed a code to exercise the unique digest constraint."""
        OAuthAuthorizationCode.objects.create(**self._code_fields())

    def _created_code_is_bound(self, code: OAuthAuthorizationCode) -> bool:
        """Check the code retains its user, client, redirect, audience, and PKCE data."""
        return (
            code.user_id == self.user.pk
            and code.client_id == "registered-client"
            and code.redirect_uri == "https://chatgpt.com/connector/oauth/demo"
            and code.resource == "https://bloomerp.example/mcp"
            and code.scope == "mcp:tools"
            and code.code_challenge == "a" * 43
            and code.expires_at > timezone.now()
            and code.code_hash == hash_oauth_secret(self.raw_code)
            and self.raw_code not in code.code_hash
        )

    def _updated_expiry_is_persisted(self, code: OAuthAuthorizationCode) -> bool:
        """Confirm an expiry update persists on the same code record."""
        return code.expires_at < timezone.now() and OAuthAuthorizationCode.objects.count() == 1

    def _deleted_code_is_gone(self, code: OAuthAuthorizationCode) -> bool:
        """Confirm deleting a consumed code removes its database row."""
        return not OAuthAuthorizationCode.objects.filter(pk=code.pk).exists()

    def get_test_scenarios(self) -> list[ModelScenario[OAuthAuthorizationCode]]:
        """Cover code binding, expiry updates, deletion, and uniqueness."""
        return [
            ModelScenario(
                name="Bound code is stored, updated, and deleted",
                create_args=self._code_fields,
                create_validators=self._created_code_is_bound,
                update_args={"expires_at": timezone.now() - timedelta(seconds=1)},
                update_validators=self._updated_expiry_is_persisted,
                delete_validators=self._deleted_code_is_gone,
            ),
            ModelScenario(
                name="Duplicate code digest is rejected",
                preparation=self._create_existing_code,
                create_args=self._code_fields,
                expected_exceptions=[
                    ExpectedModelException(phase="create", exception=IntegrityError)
                ],
            ),
        ]

    def test_deleting_owner_removes_code(self) -> None:
        """Ensure deleting an account also removes pending authorization codes."""
        code = OAuthAuthorizationCode.objects.create(**self._code_fields())
        code_pk = code.pk
        self.user.delete()
        self.assertFalse(OAuthAuthorizationCode.objects.filter(pk=code_pk).exists())
