# Generated by manage.py generate_test_cases.
from bloomerp.models.audit.activity_log import ActivityLog
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
)


class TestActivityLogModel(BloomerpModelTestCase):
    model = ActivityLog

    def get_test_scenarios(self) -> list[ModelScenario[ActivityLog]]:
        # Add only the scenarios this class needs.
        return []
