# Generated by manage.py generate_test_cases.
from django.contrib.contenttypes.models import ContentType

from bloomerp.models.communication.comment import Comment
from bloomerp.models.project_management.todo import Todo
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestCommentsComponent(BloomerpComponentTestCase):
    """Tests function `comments` from `bloomerp/components/objects/details/comments.py`."""

    view_name = 'components_comments'

    def extendedSetup(self) -> None:
        """Create a target and comment for fragment requests."""
        self.todo = Todo.objects.create(title="Discuss launch")
        self.content_type = ContentType.objects.get_for_model(Todo)
        self.comment = Comment.objects.create(
            content="Please review",
            content_type=self.content_type,
            object_id=str(self.todo.pk),
            created_by=self.admin_user,
        )

    def get_test_scenarios(self) -> list[RequestScenario]:
        """Verify highlighting and existing object permission enforcement."""
        kwargs = {"content_type_id": self.content_type.pk, "object_id": str(self.todo.pk)}
        return [
            RequestScenario(
                name="Linked comment receives a highlight ring",
                user=self.admin_user,
                view_kwargs=kwargs,
                query_params={"highlight": str(self.comment.pk)},
                expected=ExpectedResult(response_validators=[
                    self.contains_text(f'id="comment-{self.comment.pk}"'),
                    self.contains_text("ring-primary-500"),
                ]),
            ),
            RequestScenario(
                name="User without object view access cannot read comments",
                user=self.normal_user,
                view_kwargs=kwargs,
                expected=ExpectedResult(status_code=403),
            ),
        ]
