# Generated by manage.py generate_test_cases.
from bloomerp.models.project_management.todo_label import TodoLabel
from bloomerp.tests.base import (
    BloomerpAPIViewTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestAssistantMutationView(BloomerpAPIViewTestCase):
    """Tests class `AssistantMutationView` from `bloomerp/views/api/mutations.py`."""

    view_name = 'api_assistant_mutations'

    def extendedSetup(self):
        self.resource = TodoLabel._meta.verbose_name_plural.replace(" ", "_").lower()

    def get_test_scenarios(self) -> list[RequestScenario]:
        return [
            RequestScenario(
                name="Assistant mutation creates an object",
                description=(
                    "UC: An administrator asks the assistant to create a generated API resource.\n"
                    "Expected Result: The object is created and returned with the create operation."
                ),
                method="POST",
                user=self.admin_user,
                content_type="application/json",
                data={
                    "resource": self.resource,
                    "operation": "create",
                    "data": {"name": "Backend", "color": "#000000"},
                },
                expected=ExpectedResult(
                    status_code=201,
                    response_validators=self.object_was_created,
                ),
            ),
            RequestScenario(
                name="Assistant mutation updates an object",
                description=(
                    "UC: An administrator updates an existing generated API resource.\n"
                    "Expected Result: The requested field is persisted and returned."
                ),
                method="POST",
                user=self.admin_user,
                content_type="application/json",
                prepare=self.prepare_update,
                expected=ExpectedResult(response_validators=self.object_was_updated),
            ),
            RequestScenario(
                name="Assistant mutation deletes an object",
                description=(
                    "UC: An administrator deletes an existing generated API resource.\n"
                    "Expected Result: The response identifies it and the row no longer exists."
                ),
                method="POST",
                user=self.admin_user,
                content_type="application/json",
                prepare=self.prepare_delete,
                expected=ExpectedResult(response_validators=self.object_was_deleted),
            ),
            RequestScenario(
                name="Assistant mutation rejects unknown resource",
                description=(
                    "UC: The assistant supplies a resource that has no generated API.\n"
                    "Expected Result: The endpoint returns a resource validation error."
                ),
                method="POST",
                user=self.admin_user,
                content_type="application/json",
                data={"resource": "not-a-resource", "operation": "create", "data": {}},
                expected=ExpectedResult(
                    status_code=400,
                    response_validators=self.json_exact(
                        {"resource": "Unknown generated API resource."}
                    ),
                ),
            ),
            RequestScenario(
                name="Assistant mutation preserves generated API write permissions",
                description=(
                    "UC: A user without generated-model write access requests a mutation.\n"
                    "Expected Result: The request is forbidden and no object is created."
                ),
                method="POST",
                user=self.normal_user,
                content_type="application/json",
                data={
                    "resource": self.resource,
                    "operation": "create",
                    "data": {"name": "Unauthorized", "color": "#000000"},
                },
                expected=ExpectedResult(
                    status_code=403,
                    response_validators=lambda _response: not TodoLabel.objects.filter(
                        name="Unauthorized"
                    ).exists(),
                ),
            ),
            RequestScenario(
                name="OpenAPI schema documents assistant mutation routes",
                description=(
                    "UC: A client discovers assistant mutation APIs from OpenAPI.\n"
                    "Expected Result: Both mutation paths and catalog query parameters are documented."
                ),
                view_name="schema",
                query_params={"format": "json"},
                expected=ExpectedResult(response_validators=self.schema_documents_mutations),
            ),
        ]

    def create_label(self, **overrides):
        values = {"name": "Backend", "color": "#000000"}
        values.update(overrides)
        return TodoLabel.objects.create(**values)

    def prepare_update(self, scenario):
        self.label = self.create_label(name="Before")
        scenario.data = {
            "resource": self.resource,
            "operation": "update",
            "object_id": str(self.label.pk),
            "data": {"name": "Updated"},
        }

    def prepare_delete(self, scenario):
        self.label = self.create_label()
        scenario.data = {
            "resource": self.resource,
            "operation": "delete",
            "object_id": str(self.label.pk),
        }

    def object_was_created(self, response):
        payload = response.json()
        return (
            payload.get("operation") == "create"
            and TodoLabel.objects.filter(pk=payload["object"]["id"]).exists()
        )

    def object_was_updated(self, response):
        self.label.refresh_from_db()
        return (
            response.json()["object"]["name"] == "Updated"
            and self.label.name == "Updated"
        )

    def object_was_deleted(self, response):
        return (
            response.json().get("object_id") == str(self.label.pk)
            and not TodoLabel.objects.filter(pk=self.label.pk).exists()
        )

    @staticmethod
    def schema_documents_mutations(response):
        paths = response.json()["paths"]
        parameter_names = {
            parameter["name"]
            for parameter in paths["/api/mutations/catalog/"]["get"]["parameters"]
        }
        return (
            "/api/mutations/" in paths
            and "/api/mutations/catalog/" in paths
            and parameter_names == {"page", "page_size", "search", "resource"}
        )
