# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestGenerateDocumentTemplateComponent(BloomerpComponentTestCase):
    """Tests function `generate_document_template` from `bloomerp/components/document_templates/generate_document_template.py`."""

    view_name = 'components_generate_document_template'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
