# Generated by manage.py generate_test_cases.
from bloomerp.models.workspaces.sidebar_item import SidebarItem
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
    ExpectedModelException,
)


class TestSidebarItemModel(BloomerpModelTestCase):
    model = SidebarItem

    def get_test_scenarios(self) -> list[ModelScenario[SidebarItem]]:
        # Add only the scenarios this class needs.
        return []
