# Generated by manage.py generate_test_cases.
from bloomerp.models.workspaces.workspace import Workspace
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
)


class TestWorkspaceModel(BloomerpModelTestCase):
    model = Workspace

    def get_test_scenarios(self) -> list[ModelScenario[Workspace]]:
        # Add only the scenarios this class needs.
        return []
