# Generated by manage.py generate_test_cases.
from bloomerp.models.workspaces.sql_query import SqlQuery
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
)


class TestSqlQueryModel(BloomerpModelTestCase):
    model = SqlQuery

    def get_test_scenarios(self) -> list[ModelScenario[SqlQuery]]:
        # Add only the scenarios this class needs.
        return []
