# Generated by manage.py generate_test_cases.
"""Verify drag moves use physical nodes and reject folder cycles."""

from bloomerp.models import FileNode
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestMoveFileBrowserItemComponent(BloomerpComponentTestCase):
    """Exercise physical tree integrity at the drag/drop endpoint."""

    view_name = "components_files_move_browser_item"

    def get_test_scenarios(self) -> list[RequestScenario]:
        """Reject self/descendant moves and unauthorized tree writes."""
        parent = FileNode.objects.create(name="Parent", kind="FOLDER")
        child = FileNode.objects.create(name="Child", kind="FOLDER", parent=parent)
        return [
            RequestScenario(
                name="Reject moving into descendant",
                method="POST",
                user=self.admin_user,
                data={
                    "item_type": "folder",
                    "folder_id": parent.pk,
                    "target_folder_id": child.pk,
                },
                expected=ExpectedResult(
                    status_code=400,
                    response_validators=lambda response: FileNode.objects.filter(
                        pk=parent.pk, parent=None
                    ).exists(),
                ),
            ),
            RequestScenario(
                name="Move folder to root",
                method="POST",
                user=self.admin_user,
                data={"item_type": "folder", "folder_id": child.pk},
                expected=ExpectedResult(
                    status_code=204,
                    response_validators=lambda response: FileNode.objects.filter(
                        pk=child.pk, parent=None
                    ).exists(),
                ),
            ),
            RequestScenario(
                name="Deny unauthorized move",
                method="POST",
                user=self.normal_user,
                data={"item_type": "folder", "folder_id": child.pk},
                expected=ExpectedResult(
                    status_code=403,
                    response_validators=lambda response: FileNode.objects.filter(
                        pk=child.pk, parent=parent
                    ).exists(),
                ),
            ),
        ]
