# Generated by manage.py generate_test_cases.
"""Verify unused-node deletion and protection of referenced content."""

from django.core.files.uploadedfile import SimpleUploadedFile

from bloomerp.models import FileNode, FileReference
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestDeleteFileComponent(BloomerpComponentTestCase):
    """Exercise file deletion through its confirmation endpoint."""

    view_name = "components_files_delete"

    def get_test_scenarios(self) -> list[RequestScenario]:
        """Keep shared nodes intact and authorize unused-node deletion."""
        file = FileNode.objects.create(
            name="unused.txt",
            kind="FILE",
            content=SimpleUploadedFile("unused.txt", b"bytes"),
        )
        linked = FileNode.objects.create(
            name="shared.txt",
            kind="FILE",
            content=SimpleUploadedFile("shared.txt", b"bytes"),
        )
        FileReference.objects.create(
            file=linked, content_object=self.CustomerModel.objects.first()
        )
        return [
            RequestScenario(
                name="Render confirmation",
                user=self.admin_user,
                view_kwargs={"file_id": file.pk},
                expected=ExpectedResult(
                    response_validators=lambda response: (
                        "unused.txt" in response.content.decode()
                    )
                ),
            ),
            RequestScenario(
                name="Delete an unused node",
                method="POST",
                user=self.admin_user,
                view_kwargs={"file_id": file.pk},
                expected=ExpectedResult(
                    response_validators=lambda response: (
                        not FileNode.objects.filter(pk=file.pk).exists()
                    )
                ),
            ),
            RequestScenario(
                name="Protect a referenced node even from administrator deletion",
                method="POST",
                user=self.admin_user,
                view_kwargs={"file_id": linked.pk},
                expected=ExpectedResult(
                    status_code=409,
                    response_validators=lambda response: (
                        FileReference.objects.filter(file=linked).exists()
                        and FileNode.objects.filter(pk=linked.pk).exists()
                    ),
                ),
            ),
            RequestScenario(
                name="Deny unauthorized deletion",
                method="POST",
                user=self.normal_user,
                view_kwargs={"file_id": file.pk},
                expected=ExpectedResult(
                    status_code=403,
                    response_validators=lambda response: FileNode.objects.filter(
                        pk=file.pk
                    ).exists(),
                ),
            ),
        ]
