# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestDeleteFileComponent(BloomerpComponentTestCase):
    """Tests function `delete_file` from `bloomerp/components/files/actions/delete.py`."""

    view_name = 'components_files_delete'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
