# Generated by manage.py generate_test_cases.
"""Verify one asynchronous admission API and its corresponding MCP transport."""

from __future__ import annotations

from datetime import timedelta
from typing import Any
from unittest.mock import patch
from uuid import uuid4

from django.http import HttpResponse
from django.test import override_settings
from django.utils import timezone
from rest_framework.response import Response
from rest_framework.test import APIRequestFactory, force_authenticate

from bloomerp.models.files.file_extraction import FileExtraction
from bloomerp.tests.base import (
    BloomerpAPIViewTestCase,
    BloomerpMcpViewTestCase,
    ExpectedResult,
    McpRequestScenario,
    RequestScenario,
)
from bloomerp.tests.models.files.test_file_extraction_model import (
    create_source,
    install_extraction_storage,
)
from bloomerp.views.api.files import start_file_extraction as api


class TestStartFileExtractionView(BloomerpAPIViewTestCase):
    """Exercise the generated API target with declarative request scenarios."""

    view_name = "api_file_extraction_start"
    auto_create_customers = False

    def extendedSetup(self) -> None:
        """Provide real uploaded bytes and a configured but noncontacted broker."""
        self.storage = install_extraction_storage(self)
        self.source = create_source()
        self.broker = self.enterContext(patch.object(api, "current_app"))
        self.broker.conf.broker_url = "redis://broker.invalid/0"
        self.broker.conf.task_always_eager = False
        self.real_publish = api.publish_extraction
        self.publisher = self.enterContext(patch.object(api, "publish_extraction"))
        self.parser = self.enterContext(patch.object(api, "run_parser"))
        self.enterContext(
            override_settings(
                BLOOMERP_FILE_EXTRACTION_ENABLED=True, CELERY_TASK_ALWAYS_EAGER=False
            )
        )

    def get_test_scenarios(self) -> list[RequestScenario]:
        """Cover authenticated admission, malformed inputs and unsupported formats."""
        scenarios = [
            RequestScenario(
                name="Creates a pending owner-scoped job without parsing",
                method="POST",
                user=self.admin_user,
                data={"file_id": str(self.source.pk)},
                content_type="application/json",
                expected=ExpectedResult(
                    status_code=202, response_validators=self.pending_job
                ),
            ),
            RequestScenario(
                name="Anonymous start is denied",
                method="POST",
                data={"file_id": str(self.source.pk)},
                content_type="application/json",
                expected=ExpectedResult(status_code=401),
            ),
            RequestScenario(
                name="Current file permission is mandatory",
                method="POST",
                user=self.normal_user,
                data={"file_id": str(self.source.pk)},
                content_type="application/json",
                expected=ExpectedResult(status_code=404),
            ),
            RequestScenario(
                name="Missing uploaded file is not disclosed",
                method="POST",
                user=self.admin_user,
                data={"file_id": str(uuid4())},
                content_type="application/json",
                expected=ExpectedResult(status_code=404),
            ),
            RequestScenario(
                name="GET does not start work",
                user=self.admin_user,
                expected=ExpectedResult(status_code=405),
            ),
            RequestScenario(
                name="Unsupported format is rejected before publication",
                method="POST",
                user=self.admin_user,
                prepare=self.unsupported_source,
                content_type="application/json",
                expected=ExpectedResult(
                    status_code=400, response_validators=self.no_job_created
                ),
            ),
            RequestScenario(
                name="Folder nodes cannot start jobs",
                method="POST",
                user=self.admin_user,
                prepare=self.folder_source,
                content_type="application/json",
                expected=ExpectedResult(
                    status_code=404, response_validators=self.no_job_created
                ),
            ),
        ]
        for arguments in (
            {},
            {"file_id": "not-a-uuid"},
            {"file_id": str(self.source.pk), "url": "https://example.invalid/private"},
            {"file_id": str(self.source.pk), "path": "/etc/passwd"},
        ):
            scenarios.append(
                RequestScenario(
                    name=f"Rejects unsupported or malformed input {arguments}",
                    method="POST",
                    user=self.admin_user,
                    data=arguments,
                    content_type="application/json",
                    expected=ExpectedResult(
                        status_code=400, response_validators=self.no_job_created
                    ),
                )
            )
        return scenarios

    def pending_job(self, response: HttpResponse) -> bool:
        """Require durable ownership and compact status rather than inline parsing."""
        payload = response.json()
        job = FileExtraction.objects.get(pk=payload["job_id"])
        self.parser.assert_not_called()
        return (
            job.requested_by == self.admin_user
            and job.source_file == self.source
            and payload["status"] == "queued"
            and payload["content_is_untrusted"]
            and "records" not in payload
            and "url" not in payload
        )

    def no_job_created(self, response: HttpResponse) -> bool:
        """Malformed requests leave no durable jobs or parser executions."""
        self.parser.assert_not_called()
        return not FileExtraction.objects.exists()

    def unsupported_source(self, scenario: RequestScenario) -> None:
        """Select bytes stored with an explicitly unsupported file format."""
        scenario.data = {"file_id": str(create_source(b"zip", "source.zip").pk)}

    def folder_source(self, scenario: RequestScenario) -> None:
        """Reject a physical folder identity before creating an extraction job."""
        from bloomerp.models.files.file_node import FileNode

        folder = FileNode.objects.create(name="Folder", kind="FOLDER")
        scenario.data = {"file_id": str(folder.pk)}

    def call_start(self, source_id: str | None = None, user: Any = None) -> Response:
        """Invoke the real DRF view for patch-heavy admission boundary assertions."""
        request = APIRequestFactory().post(
            "/", {"file_id": source_id or str(self.source.pk)}, format="json"
        )
        force_authenticate(request, user=user or self.admin_user)
        return api.StartFileExtractionView.as_view()(request)

    def test_repeat_start_reuses_active_job_and_publishes_after_commit(self) -> None:
        """Publish once after durable commit and return the same active job on retry."""
        first = self.call_start()
        second = self.call_start()
        self.assertEqual(first.status_code, 202)
        self.assertEqual(second.data["job_id"], first.data["job_id"])
        self.assertEqual(FileExtraction.objects.count(), 1)
        self.publisher.assert_called_once_with(
            first.data["job_id"], str(self.admin_user.pk)
        )
        self.parser.assert_not_called()

    def test_disabled_eager_memory_and_missing_broker_are_explicitly_unavailable(
        self,
    ) -> None:
        """Never execute extraction synchronously when a durable worker is unavailable."""
        for configuration in (
            {"BLOOMERP_FILE_EXTRACTION_ENABLED": False},
            {"CELERY_TASK_ALWAYS_EAGER": True},
        ):
            with (
                self.subTest(configuration=configuration),
                override_settings(**configuration),
            ):
                self.assertEqual(self.call_start().status_code, 503)
        for broker, eager in (
            ("", False),
            ("memory://", False),
            ("redis://broker.invalid; memory://", False),
            ("redis://broker.invalid", True),
        ):
            with (
                self.subTest(broker=broker, eager=eager),
                override_settings(CELERY_BROKER_URL=""),
            ):
                self.broker.conf.broker_url, self.broker.conf.task_always_eager = (
                    broker,
                    eager,
                )
                self.assertEqual(self.call_start().status_code, 503)
        self.assertFalse(FileExtraction.objects.exists())
        self.publisher.assert_not_called()
        self.parser.assert_not_called()

    def test_missing_docling_provider_is_explicit_without_inline_fallback(self) -> None:
        """Missing offline artifacts return unavailable even if the broker is configured."""
        source = create_source(b"%PDF-1.7", "source.pdf")
        with override_settings(BLOOMERP_FILE_EXTRACTION_DOCLING_ARTIFACTS=""):
            response = self.call_start(str(source.pk))
        self.assertEqual(response.status_code, 503)
        self.assertIn("provider_unavailable", str(response.data))
        self.assertFalse(FileExtraction.objects.exists())
        self.parser.assert_not_called()

    def test_admission_capacity_and_expired_claims_are_bounded(self) -> None:
        """Reject excess work while ignoring expired queue leases for admission."""
        other_source = create_source(b"other", "other.txt")
        FileExtraction.objects.create(
            source_file=other_source, requested_by=self.admin_user
        )
        self.assertEqual(self.call_start().status_code, 503)
        FileExtraction.objects.update(
            start_deadline=timezone.now() - timedelta(seconds=1)
        )
        self.assertEqual(self.call_start().status_code, 202)
        FileExtraction.objects.all().delete()
        FileExtraction.objects.create(
            source_file=self.source, requested_by=self.normal_user
        )
        FileExtraction.objects.create(
            source_file=other_source, requested_by=self.normal_user
        )
        self.assertEqual(self.call_start().status_code, 503)

    def test_empty_oversized_missing_and_inactive_sources_cannot_publish(self) -> None:
        """Enforce size and storage availability before broker contact or job creation."""
        for size in (0, api.MAX_FILE_BYTES + 1, None):
            with self.subTest(size=size):
                self.source.meta["size"] = size
                type(self.source).objects.filter(pk=self.source.pk).update(meta=self.source.meta)
                with patch.object(self.storage, "size", side_effect=AssertionError("Storage size queried")):
                    response = self.call_start()
                self.assertEqual(response.status_code, 400)
                self.assertIn("file_size_limit", str(response.data))
        self.admin_user.is_active = False
        self.assertEqual(self.call_start().status_code, 404)
        self.assertFalse(FileExtraction.objects.exists())
        self.publisher.assert_not_called()

    def test_publish_failure_is_terminal_and_does_not_execute_task_inline(self) -> None:
        """A broker exception produces a safe retryable terminal state for the durable job."""
        self.publisher.side_effect = self.real_publish
        with patch.object(
            api.execute_file_extraction,
            "apply_async",
            side_effect=RuntimeError("broker password"),
        ) as task:
            response = self.call_start()
        self.assertEqual(response.status_code, 503)
        job = FileExtraction.objects.get(pk=response.data["job_id"])
        self.assertEqual(
            (job.status, job.error_code),
            (FileExtraction.Status.UNAVAILABLE, "worker_unavailable"),
        )
        self.assertFalse(task.call_args.kwargs["retry"])
        self.assertEqual(task.call_args.kwargs["soft_time_limit"], 135)
        self.parser.assert_not_called()


class TestStartFileExtractionMcp(BloomerpMcpViewTestCase):
    """Verify the same API is registered and callable through the real MCP transport."""

    view_name = "api_file_extraction_start"

    def setUp(self) -> None:
        """Provide uploaded content without a live broker or parser dependency."""
        super().setUp()
        install_extraction_storage(self)
        self.source = create_source()
        self.enterContext(patch.object(api, "require_background_provider"))
        self.enterContext(patch.object(api, "publish_extraction"))

    def get_test_scenarios(self) -> list[McpRequestScenario]:
        """Exercise tool admission plus strict schema and file-permission rejection."""
        return [
            McpRequestScenario(
                name="MCP starts a durable pending extraction",
                user=self.admin_user,
                arguments={"file_id": str(self.source.pk)},
                expected=ExpectedResult(
                    response_validators=[self.mcp_is_error(False), self.pending_content]
                ),
            ),
            McpRequestScenario(
                name="MCP denies unauthorized source access",
                user=self.normal_user,
                arguments={"file_id": str(self.source.pk)},
                expected=ExpectedResult(response_validators=self.mcp_is_error()),
            ),
            McpRequestScenario(
                name="MCP rejects arbitrary URL input",
                user=self.admin_user,
                arguments={
                    "file_id": str(self.source.pk),
                    "url": "https://invalid.example",
                },
                expected=ExpectedResult(response_validators=self.mcp_is_error()),
            ),
        ]

    def pending_content(self, response: HttpResponse) -> bool:
        """Require job metadata in the structured MCP result without extracted bytes."""
        payload = response.json()["result"]["structuredContent"]
        return (
            payload["status"] == "queued"
            and bool(payload["job_id"])
            and payload["content_is_untrusted"]
            and "records" not in payload
        )
