# Generated by manage.py generate_test_cases.
from bs4 import BeautifulSoup
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponse
from django.urls import reverse

from bloomerp.models import ApplicationField, Todo
from bloomerp.models.users.user_list_view_preference import UserListViewPreference
from bloomerp.services.preference_services import PreferenceManager
from bloomerp.tests.base import BloomerpComponentTestCase, ExpectedResult, RequestScenario


class TestDataviewActionComponent(BloomerpComponentTestCase):
    """Verify that incremental Kanban responses preserve per-card actions."""

    view_name = "components_dataview_renderer_operation"

    def prepare_kanban(self, scenario: RequestScenario) -> None:
        """Create thirty local todos and configure a ten-card status lane."""
        content_type = ContentType.objects.get_for_model(Todo)
        preference = PreferenceManager(self.admin_user).get_or_create_selected(
            UserListViewPreference, {"content_type_id": content_type.pk},
        )
        preference.view_type = "kanban"
        preference.options = {
            "kanban": {"page_size": 10, "group_by_field": "status", "sort_field": "title"},
        }
        preference.display_fields = {
            "kanban": [ApplicationField.get_by_field(Todo, "title").pk],
        }
        preference.save()
        status = scenario.query_params["kanban_column"]
        self.todo_ids = [
            str(Todo.objects.create(title=f"Kanban regression {index:02d}", status=status).pk)
            for index in range(30)
        ]
        scenario.view_kwargs = {
            "content_type_id": content_type.pk,
            "preference_id": preference.pk,
            "action": "column",
        }
        self.expected_complete_action = status != "completed"
        self.expected_next_page = int(scenario.query_params["kanban_page"]) < 3
        self.client.force_login(self.admin_user)
        initial = self.client.get(
            reverse("components_dataview", kwargs={"content_type_id": content_type.pk}),
            HTTP_HX_REQUEST="true",
        )
        self.assertEqual(initial.status_code, 200)
        self.expected_card_ids = self.todo_ids[:10]
        self.assert_card_actions(initial)
        page = int(scenario.query_params["kanban_page"])
        self.expected_card_ids = self.todo_ids[(page - 1) * 10:page * 10]

    def assert_card_actions(self, response: HttpResponse) -> bool:
        """Check each card retains HTML actions and conditional executable actions."""
        document = BeautifulSoup(response.content, "html.parser")
        cards = document.select('[bloomerp-component="kanban-card"]')
        self.assertEqual(len(cards), 10)
        self.assertEqual([card["data-object-id"] for card in cards], self.expected_card_ids)
        for card in cards:
            self.assertIn("Copy branch name", card.get_text())
            complete = card.find("button", attrs={"hx-post": True})
            self.assertEqual(complete is not None, self.expected_complete_action)
            if complete is not None:
                self.assertIn(str(card["data-object-id"]), complete["hx-post"])
                self.assertIn("mark_as_completed", complete["hx-post"])
        return True

    def validate_column(self, response: HttpResponse) -> bool:
        """Validate card actions and whether another incremental page is available."""
        self.assert_card_actions(response)
        document = BeautifulSoup(response.content, "html.parser")
        loader = document.select_one("[data-kanban-column-loader]")
        self.assertEqual(loader is not None, self.expected_next_page)
        return True

    def get_test_scenarios(self) -> list[RequestScenario]:
        """Cover intermediate, final, and conditionally hidden action responses."""
        return [
            RequestScenario(
                name=name,
                user=self.admin_user,
                query_params={"kanban_column": status, "kanban_page": page},
                headers={"HX-Request": "true"},
                prepare=self.prepare_kanban,
                expected=ExpectedResult(response_validators=self.validate_column),
            )
            for name, status, page in [
                ("Second page retains every card action", "scoped", 2),
                ("Final page retains actions without another loader", "scoped", 3),
                ("Completed cards still hide the completion action", "completed", 2),
            ]
        ]
