# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpE2ETestCase,
    E2EAction,
    E2ERequestScenario,
)


class TestInboxViewE2E(BloomerpE2ETestCase):
    """Tests class `InboxView` from `bloomerp/views/communication/inbox.py`."""

    view_name = 'inbox'

    def get_test_scenarios(self) -> list[E2ERequestScenario]:
        # Add only the browser scenarios this view needs.
        return []
