# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpViewTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestBloomerpHomeView(BloomerpViewTestCase):
    """Tests class `BloomerpHomeView` from `bloomerp/views/workspaces/home.py`."""

    view_name = 'bloomerp_home_view'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
