# Generated by manage.py generate_test_cases.
from types import SimpleNamespace
from unittest.mock import patch

from django.urls import reverse

from bloomerp.models import User, Workspace
from bloomerp.tests.base import (
    BloomerpViewTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestBloomerpHomeView(BloomerpViewTestCase):
    """Tests class `BloomerpHomeView` from `bloomerp/views/workspaces/home.py`."""

    view_name = 'bloomerp_home_view'

    def extendedSetup(self):
        self.staff_module = SimpleNamespace(
            id="staff",
            name="Staff",
            description="Staff module",
            icon="fa-users",
        )

    def get_test_scenarios(self) -> list[RequestScenario]:
        request_headers = {"hx-request": "true", "hx-target": "main-content"}
        return [
            RequestScenario(
                name="Home without general workspace shows modules",
                description=(
                    "UC: A user without a general workspace opens home.\n"
                    "Expected Result: The accessible module selector remains available."
                ),
                user=self.admin_user,
                headers=request_headers,
                prepare=self.show_staff_module,
                cleanup=self.stop_module_patches,
                expected=ExpectedResult(
                    response_validators=[
                        self.contains_text("Staff module"),
                        self.does_not_contain_text("Select module"),
                    ]
                ),
            ),
            RequestScenario(
                name="Module workspace does not replace home selection",
                description=(
                    "UC: A user has a selected workspace scoped to one module.\n"
                    "Expected Result: General home still shows modules rather than that workspace."
                ),
                user=self.admin_user,
                headers=request_headers,
                prepare=[self.show_staff_module, self.create_module_workspace],
                cleanup=self.stop_module_patches,
                expected=ExpectedResult(
                    response_validators=[
                        self.contains_text("Staff module"),
                        self.does_not_contain_text("Staff workspace"),
                    ]
                ),
            ),
            RequestScenario(
                name="Selected general workspace replaces module selector",
                description=(
                    "UC: A user selected a general workspace as home.\n"
                    "Expected Result: Home renders it with an option to return to modules."
                ),
                user=self.admin_user,
                headers=request_headers,
                prepare=[self.show_staff_module, self.create_general_workspace],
                cleanup=self.stop_module_patches,
                expected=ExpectedResult(
                    response_validators=[
                        self.contains_text("My home workspace"),
                        self.contains_text("Select module"),
                        self.does_not_contain_text("Staff module"),
                    ]
                ),
            ),
            RequestScenario(
                name="Shared initial default becomes user's home workspace",
                description=(
                    "UC: An administrator receives a shared general workspace marked initial default.\n"
                    "Expected Result: Home renders it and creates a selected live reference."
                ),
                user=self.admin_user,
                headers=request_headers,
                prepare=self.create_shared_initial_workspace,
                expected=ExpectedResult(
                    response_validators=[
                        self.contains_text("Timesheet home"),
                        self.shared_reference_is_selected,
                    ]
                ),
            ),
            RequestScenario(
                name="Modules query temporarily shows module selector",
                description=(
                    "UC: A user with a home workspace chooses Select module.\n"
                    "Expected Result: Modules render without changing the saved home selection."
                ),
                user=self.admin_user,
                headers=request_headers,
                query_params={"modules": 1},
                prepare=[self.show_staff_module, self.create_general_workspace],
                cleanup=self.stop_module_patches,
                expected=ExpectedResult(
                    response_validators=[
                        self.contains_text("Staff module"),
                        self.does_not_contain_text("My home workspace"),
                        self.general_workspace_remains_selected,
                    ]
                ),
            ),
            RequestScenario(
                name="Revoked shared home workspace falls back to modules",
                description=(
                    "UC: Access to a selected shared home workspace is revoked.\n"
                    "Expected Result: Home stops rendering it and safely falls back to modules."
                ),
                user=self.admin_user,
                headers=request_headers,
                prepare=[self.show_staff_module, self.prepare_revoked_workspace],
                cleanup=self.stop_module_patches,
                expected=ExpectedResult(
                    response_validators=[
                        self.contains_text("Staff module"),
                        self.does_not_contain_text("Revoked home"),
                    ]
                ),
            ),
        ]

    def create_workspace(self, **kwargs):
        return Workspace.objects.create(
            layout={"rows": [{"title": "Home", "columns": 4, "items": []}]},
            **kwargs,
        )

    def show_staff_module(self, _scenario):
        self.root_modules_patcher = patch(
            "bloomerp.views.workspaces.home.module_registry.get_root_modules",
            return_value=[self.staff_module],
        )
        self.module_models_patcher = patch(
            "bloomerp.views.workspaces.home.module_registry.get_models_for_module",
            return_value=[User],
        )
        self.root_modules_patcher.start()
        self.module_models_patcher.start()

    def stop_module_patches(self, _scenario):
        self.module_models_patcher.stop()
        self.root_modules_patcher.stop()

    def create_module_workspace(self, _scenario):
        self.create_workspace(
            user=self.admin_user,
            name="Staff workspace",
            module_id="staff",
            selected=True,
        )

    def create_general_workspace(self, _scenario):
        self.general_workspace = self.create_workspace(
            user=self.admin_user,
            name="My home workspace",
            module_id=None,
            selected=True,
        )

    def create_shared_initial_workspace(self, _scenario):
        self.shared_workspace = self.create_workspace(
            user=self.normal_user,
            name="Timesheet home",
            module_id=None,
            initial_default=True,
        )
        self.shared_workspace.shared_with_users.add(self.admin_user)

    def shared_reference_is_selected(self, _response):
        return Workspace.objects.get(
            user=self.admin_user,
            source_object=self.shared_workspace,
        ).selected

    def general_workspace_remains_selected(self, _response):
        self.general_workspace.refresh_from_db()
        return self.general_workspace.selected

    def prepare_revoked_workspace(self, _scenario):
        shared = self.create_workspace(
            user=self.normal_user,
            name="Revoked home",
            module_id=None,
            initial_default=True,
        )
        shared.shared_with_users.add(self.admin_user)
        self.client.force_login(self.admin_user)
        self.client.get(
            reverse("bloomerp_home_view"),
            HTTP_HX_REQUEST="true",
            HTTP_HX_TARGET="main-content",
        )
        shared.shared_with_users.remove(self.admin_user)
