# Generated by manage.py generate_test_cases.
from bloomerp.models.automation.workflow import Workflow
from bloomerp.tests.base import (
    BloomerpDetailViewTestCase,
    ExpectedResult,
    RequestScenario,
    ModelRequestScenario,
)


class TestCreateWorkflowView(BloomerpDetailViewTestCase):
    """Tests class `CreateWorkflowView` from `bloomerp/views/workflows/builder.py`."""

    view_name = 'builder'
    model = Workflow

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
