# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestSidebarMoveItemComponent(BloomerpComponentTestCase):
    """Tests function `sidebar_move_item` from `bloomerp/components/ui/sidebar.py`."""

    view_name = 'components_workspaces_sidebar_move_item'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
