# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpAPIViewTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestLogoutView(BloomerpAPIViewTestCase):
    """Tests class `LogoutView` from `bloomerp/views/api/auth/logout.py`."""

    view_name = 'api_logout'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
