# Generated by manage.py generate_test_cases.
from django.test import override_settings

from bloomerp.config.definition import BloomerpAuthSettings, BloomerpConfig, SessionAuthSettings
from bloomerp.tests.base import (
    BloomerpAPIViewTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestSessionView(BloomerpAPIViewTestCase):
    """Tests class `SessionView` from `bloomerp/views/api/auth/session.py`."""

    view_name = 'session'

    def get_test_scenarios(self) -> list[RequestScenario]:
        return [
            RequestScenario(
                name="Anonymous session reports unauthenticated",
                description=(
                    "UC: An anonymous client checks its session.\n"
                    "Expected Result: The API reports that no user is authenticated."
                ),
                expected=ExpectedResult(
                    response_validators=self.json_exact({"authenticated": False})
                ),
            ),
            RequestScenario(
                name="Authenticated session returns configured user fields",
                description=(
                    "UC: A signed-in client checks its session.\n"
                    "Expected Result: The response identifies the current username and email."
                ),
                user=self.normal_user,
                expected=ExpectedResult(response_validators=self.session_identifies_user),
            ),
            RequestScenario(
                name="Session serializes file fields as media URLs",
                description=(
                    "UC: Session configuration exposes the user's avatar.\n"
                    "Expected Result: The file value is serialized as a public media URL."
                ),
                user=self.normal_user,
                prepare=[self.enable_avatar_session, self.assign_avatar],
                cleanup=self.disable_settings_override,
                expected=ExpectedResult(response_validators=self.session_has_avatar_url),
            ),
            RequestScenario(
                name="Disabled session authentication hides endpoint",
                description=(
                    "UC: Session authentication endpoints are disabled in configuration.\n"
                    "Expected Result: The session endpoint returns 404 with an explanatory detail."
                ),
                prepare=self.disable_session_auth,
                cleanup=self.disable_settings_override,
                expected=ExpectedResult(
                    status_code=404,
                    response_validators=self.json_key_equals(
                        "detail", "Session auth endpoints are disabled."
                    ),
                ),
            ),
        ]

    def enable_override(self, **settings):
        self.settings_override = override_settings(**settings)
        self.settings_override.enable()

    def disable_settings_override(self, _scenario):
        self.settings_override.disable()

    def enable_avatar_session(self, _scenario):
        self.enable_override(
            MEDIA_URL="/media/",
            BLOOMERP_CONFIG=BloomerpConfig(
                auto_generate_api_endpoints=True,
                auth=BloomerpAuthSettings(
                    session=SessionAuthSettings(user_fields=["id", "avatar"])
                ),
            ),
        )

    def assign_avatar(self, _scenario):
        self.normal_user.avatar = "avatars/profile.png"
        self.normal_user.save(update_fields=["avatar"])

    def disable_session_auth(self, _scenario):
        self.enable_override(
            BLOOMERP_CONFIG=BloomerpConfig(
                auto_generate_api_endpoints=True,
                auth=BloomerpAuthSettings(session=SessionAuthSettings(enabled=False)),
            )
        )

    @staticmethod
    def session_identifies_user(response):
        payload = response.json()
        return (
            payload["authenticated"]
            and payload["user"]["username"] == "johndoe"
            and payload["user"]["email"] == "johndoe@example.com"
        )

    @staticmethod
    def session_has_avatar_url(response):
        payload = response.json()
        return payload["authenticated"] and payload["user"]["avatar"] == "/media/avatars/profile.png"
