# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpAPIViewTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestCsrfView(BloomerpAPIViewTestCase):
    """Tests class `CsrfView` from `bloomerp/views/api/auth/csrf.py`."""

    view_name = 'csrf'

    def get_test_scenarios(self) -> list[RequestScenario]:
        return [
            RequestScenario(
                name="CSRF endpoint returns token and cookie",
                description=(
                    "UC: A browser client initializes CSRF protection.\n"
                    "Expected Result: The response includes a token and sets the CSRF cookie."
                ),
                expected=ExpectedResult(response_validators=self.csrf_token_and_cookie_exist),
            )
        ]

    @staticmethod
    def csrf_token_and_cookie_exist(response):
        return "csrfToken" in response.json() and "csrftoken" in response.cookies
