# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpAPIViewTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestSessionView(BloomerpAPIViewTestCase):
    """Tests class `SessionView` from `bloomerp/views/api/auth/session.py`."""

    view_name = 'session'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
