# Generated by manage.py generate_test_cases.
from bloomerp.widgets.file_field_widget import BloomerpFileFieldWidget
from bloomerp.tests.base import (
    BloomerpWidgetTestCase,
    WidgetScenario,
    WidgetOperation,
    ExpectedWidgetException,
)


class TestBloomerpFileFieldWidget(BloomerpWidgetTestCase):
    widget_class = BloomerpFileFieldWidget

    def get_test_scenarios(self) -> list[WidgetScenario[BloomerpFileFieldWidget]]:
        # Add only the scenarios this class needs.
        return []
