# Generated by manage.py generate_test_cases.
from bloomerp.widgets.code_editor_widget import CodeEditorWidget
from bloomerp.tests.base import (
    BloomerpWidgetTestCase,
    WidgetScenario,
    WidgetOperation,
    ExpectedWidgetException,
)


class TestCodeEditorWidget(BloomerpWidgetTestCase):
    widget_class = CodeEditorWidget

    def get_test_scenarios(self) -> list[WidgetScenario[CodeEditorWidget]]:
        # Add only the scenarios this class needs.
        return []
