# Generated by manage.py generate_test_cases.
from bloomerp.widgets.week_widget import WeekWidget
from bloomerp.tests.base import (
    BloomerpWidgetTestCase,
    WidgetScenario,
    WidgetOperation,
    ExpectedWidgetException,
)


class TestWeekWidget(BloomerpWidgetTestCase):
    widget_class = WeekWidget

    def get_test_scenarios(self) -> list[WidgetScenario[WeekWidget]]:
        # Add only the scenarios this class needs.
        return []
