# Generated by manage.py generate_test_cases.
from bloomerp.widgets.list_filter_widget import ListFilterWidget
from bloomerp.tests.base import (
    BloomerpWidgetTestCase,
    WidgetScenario,
    WidgetOperation,
    ExpectedWidgetException,
)


class TestListFilterWidget(BloomerpWidgetTestCase):
    widget_class = ListFilterWidget

    def get_test_scenarios(self) -> list[WidgetScenario[ListFilterWidget]]:
        # Add only the scenarios this class needs.
        return []
