# Generated by manage.py generate_test_cases.
from bloomerp.widgets.filter_widget import FilterWidget
from bloomerp.tests.base import (
    BloomerpWidgetTestCase,
    WidgetScenario,
    WidgetOperation,
    ExpectedWidgetException,
)


class TestFilterWidget(BloomerpWidgetTestCase):
    widget_class = FilterWidget

    def get_test_scenarios(self) -> list[WidgetScenario[FilterWidget]]:
        # Add only the scenarios this class needs.
        return []
