# Generated by manage.py generate_test_cases.
from bloomerp.widgets.text_editor import BloomerpTextEditorWidget
from bloomerp.tests.base import (
    BloomerpWidgetTestCase,
    WidgetScenario,
    WidgetOperation,
    ExpectedWidgetException,
)


class TestBloomerpTextEditorWidget(BloomerpWidgetTestCase):
    widget_class = BloomerpTextEditorWidget

    def get_test_scenarios(self) -> list[WidgetScenario[BloomerpTextEditorWidget]]:
        # Add only the scenarios this class needs.
        return []
