# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestDetailTabsPreferenceComponent(BloomerpComponentTestCase):
    """Tests function `detail_tabs_preference` from `bloomerp/components/ui/detail/tabs_preference.py`."""

    view_name = 'components_detail_tabs_preference'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
