# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestScenario,
)


class TestDetailSidebarPreferenceComponent(BloomerpComponentTestCase):
    """Tests function `detail_sidebar_preference` from `bloomerp/components/ui/detail/sidebar_preference.py`."""

    view_name = 'components_detail_sidebar_preference'

    def get_test_scenarios(self) -> list[RequestScenario]:
        # Add only the route scenarios this callable needs.
        return []
