# Generated by manage.py generate_test_cases.
"""Focused scenarios for safe top-level Decimal formulas."""

from decimal import Decimal

from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import PermissionDenied, ValidationError
from django.db import models

from bloomerp.field_types.registry import FIELD_TYPE_REGISTRY
from bloomerp.form_behaviors.builtins.calculate_field import CALCULATE_FIELD
from bloomerp.form_behaviors.definition import (
    BehaviorAction,
    BehaviorConfig,
    BehaviorContext,
    BehaviorResult,
    FieldValueUpdate,
    FormBehavior,
)
from bloomerp.form_behaviors.execution import BehaviorExecutor
from bloomerp.form_behaviors.shared.write_policy import WritePolicyField
from bloomerp.models.application_field import ApplicationField
from bloomerp.models.definition import FieldLayout, LayoutItem, LayoutRow
from bloomerp.models.users.user_object_layout_preference import (
    UserObjectLayoutPreference,
)
from bloomerp.tests.base import (
    BehaviorActionScenario,
    BloomerpBehaviorActionTestCase,
    ExpectedBehaviorActionException,
)
from bloomerp.tests.utils.dynamic_models import create_test_models


class TestCalculateFieldAction(BloomerpBehaviorActionTestCase):
    """Verify arithmetic, eligibility, policies, validation, and authorization."""

    action = CALCULATE_FIELD
    auto_create_customers = False
    calculation_model: type[models.Model]

    @classmethod
    def setUpClass(cls) -> None:
        """Create a model with numeric, text, and non-calculable field contracts."""
        super().setUpClass()
        cls.calculation_model = create_test_models(
            "bloomerp",
            {
                "FieldCalculation": {
                    "note": models.CharField(max_length=40),
                    "short_code": models.CharField(max_length=5, blank=True),
                    "quantity": models.IntegerField(null=True, blank=True),
                    "unit_price": models.DecimalField(
                        max_digits=10, decimal_places=2, null=True, blank=True
                    ),
                    "discount": models.DecimalField(
                        max_digits=10, decimal_places=2, null=True, blank=True
                    ),
                    "total": models.DecimalField(
                        max_digits=10, decimal_places=2, null=True, blank=True
                    ),
                    "active": models.BooleanField(default=True),
                    "starts_on": models.DateField(null=True, blank=True),
                }
            },
            use_bloomerp_base=True,
        )["FieldCalculation"]

    def _field(self, name: str) -> ApplicationField:
        """Resolve an ApplicationField on the calculation fixture model."""
        return self.get_application_field(name, self.calculation_model)

    def _scenario(
        self,
        name: str,
        expression: str,
        expected: Decimal,
        *,
        target_value: object = None,
        policy: str | None = None,
        should_update: bool = True,
    ) -> BehaviorActionScenario:
        """Build one formula scenario with a deliberately nonnumeric listener."""
        values = {
            "note": "trigger",
            "quantity": 3,
            "unit_price": Decimal("10.25"),
            "discount": Decimal("0.50"),
            "total": target_value,
        }
        config = {"expression": expression}
        if policy is not None:
            config["write_policy"] = policy
        return BehaviorActionScenario(
            name=name,
            context=BehaviorContext(
                values=values, listener_field="note", target_field="total"
            ),
            listener=self._field("note"),
            target=self._field("total"),
            config=config,
            expected_result=(
                BehaviorResult(
                    values=(FieldValueUpdate(field="total", value=expected),)
                )
                if should_update
                else BehaviorResult()
            ),
        )

    def get_test_scenarios(self) -> list[BehaviorActionScenario]:
        """Cover arithmetic, policies, errors, and syntax without draft mutation."""
        scenarios = [
            self._scenario(
                "Precedence and nested parentheses use multiple top-level fields",
                "(unit_price + discount) * (quantity - 1)",
                Decimal("21.50"),
            ),
            self._scenario(
                "Unary signs and decimal literals remain exact",
                "-(unit_price) + +0.1 + 0.2",
                Decimal("-9.95"),
            ),
            self._scenario(
                "Explicit always overwrites a nonzero target",
                "quantity + 1",
                Decimal(4),
                target_value=Decimal(9),
                policy="always",
            ),
            self._scenario(
                "Omitted legacy policy defaults to always",
                "quantity + 2",
                Decimal(5),
                target_value=Decimal(9),
            ),
            self._scenario(
                "Empty-only writes a blank target",
                "quantity + 3",
                Decimal(6),
                target_value="",
                policy="if_empty",
            ),
            self._scenario(
                "Empty-only preserves numeric zero",
                "quantity + 4",
                Decimal(7),
                target_value=Decimal(0),
                policy="if_empty",
                should_update=False,
            ),
            self._scenario(
                "Empty-or-zero writes normalized string zero",
                "quantity + 5",
                Decimal(8),
                target_value="0.00",
                policy="if_empty_or_zero",
            ),
            self._scenario(
                "Empty-or-zero preserves nonzero targets",
                "quantity + 6",
                Decimal(9),
                target_value="1.00",
                policy="if_empty_or_zero",
                should_update=False,
            ),
            self._scenario(
                "An unchanged numeric result produces no update",
                "quantity",
                Decimal(3),
                target_value=3,
                policy="always",
                should_update=False,
            ),
        ]
        invalid_cases = [
            ("Unknown fields are rejected", "missing + 1", "Unknown or non-numeric"),
            ("Nonnumeric fields are rejected", "note + 1", "Unknown or non-numeric"),
            (
                "Target self-reference is rejected",
                "total + 1",
                "cannot reference itself",
            ),
            ("Function calls are rejected", "abs(quantity)", "Unsupported expression"),
            ("Power syntax is rejected", "quantity ** 2", "only \\+"),
            ("Division by zero is rejected", "quantity / 0", "divides by zero"),
        ]
        for name, expression, message in invalid_cases:
            scenarios.append(
                BehaviorActionScenario(
                    name=name,
                    context=BehaviorContext(
                        values={
                            "note": "trigger",
                            "quantity": 3,
                            "total": None,
                        },
                        listener_field="note",
                        target_field="total",
                    ),
                    listener=self._field("note"),
                    target=self._field("total"),
                    config={"expression": expression},
                    expected_exception=ExpectedBehaviorActionException(
                        ValidationError, message
                    ),
                )
            )
        return scenarios

    def test_listener_and_target_eligibility_follow_registered_contracts(self) -> None:
        """Any listener is valid while targets are text, numeric, or property only."""
        content_type = ContentType.objects.get_for_model(self.calculation_model)
        property_field, _created = ApplicationField.objects.get_or_create(
            content_type=content_type,
            field="computed_property",
            defaults={"field_type": FIELD_TYPE_REGISTRY.PROPERTY.id},
        )
        fields = ApplicationField.get_for_model(self.calculation_model)
        listeners = set(
            CALCULATE_FIELD.get_listener_fields(fields).values_list("field", flat=True)
        )
        targets = set(
            CALCULATE_FIELD.get_target_fields(fields, self._field("note")).values_list(
                "field", flat=True
            )
        )
        self.assertIn("active", listeners)
        self.assertIn("starts_on", listeners)
        for name in ("note", "short_code", "quantity", "unit_price", "total"):
            self.assertIn(name, targets)
        self.assertIn(property_field.field, targets)
        self.assertNotIn("active", targets)
        self.assertNotIn("starts_on", targets)

    def test_config_uses_shared_write_policy_field_and_legacy_default(self) -> None:
        """The formula form shares strict policy choices and defaults omissions."""
        form_class = CALCULATE_FIELD.config_form_factory(
            self._field("total"), self._field("note")
        )
        self.assertIsInstance(form_class.base_fields["write_policy"], WritePolicyField)
        form = form_class(data={"expression": "quantity + 1"})
        self.assertTrue(form.is_valid(), form.errors)
        self.assertEqual(form.cleaned_data["write_policy"], "always")
        self.assertNotIn("target", form.cleaned_data)
        self.assertEqual(set(form.cleaned_data["source_fields"]), {"quantity"})

    def _owner(
        self,
        *,
        target: str = "total",
        expression: str = "quantity * unit_price",
    ) -> UserObjectLayoutPreference:
        """Create an executable layout containing all formula sources and target."""
        item_names = ["note", "quantity", "unit_price", "discount", target]
        items = [LayoutItem(id=name) for name in dict.fromkeys(item_names)]
        items[0] = LayoutItem(
            id="note",
            config={
                "behaviors": BehaviorConfig(
                    behaviors=[
                        FormBehavior(
                            id="calculate",
                            actions=[
                                BehaviorAction(
                                    action="calculate_field",
                                    target_field=target,
                                    config={"expression": expression},
                                )
                            ],
                        )
                    ]
                ).to_storage()
            },
        )
        return UserObjectLayoutPreference.objects.create(
            user=self.admin_user,
            name="Calculate field fixture",
            content_type=ContentType.objects.get_for_model(self.calculation_model),
            layout=FieldLayout(
                rows=[LayoutRow(columns=len(items), items=items)]
            ).model_dump(mode="json"),
        )

    def _instance(self) -> models.Model:
        """Create one persisted object used to prove calculations remain draft-only."""
        return self.calculation_model.objects.create(
            note="Stored",
            short_code="old",
            quantity=2,
            unit_price=Decimal("4.25"),
            discount=Decimal("0.50"),
            total=Decimal("1.00"),
        )

    def test_executor_enforces_sources_and_never_persists(self) -> None:
        """Authorized source reads produce a typed draft update without saving it."""
        instance = self._instance()
        executor = BehaviorExecutor(self._owner(), self.admin_user, instance=instance)
        values = {
            "note": "trigger",
            "quantity": "3",
            "unit_price": "2.50",
            "discount": "0.50",
            "total": "1.00",
        }
        before = values.copy()
        result = executor.evaluate("note", values)
        self.assertEqual(
            result.values,
            (FieldValueUpdate(field="total", value="7.50"),),
        )
        self.assertEqual(values, before)
        instance.refresh_from_db()
        self.assertEqual(instance.total, Decimal("1.00"))

        executor.read_fields.pop("quantity")
        with self.assertRaises(PermissionDenied):
            executor.evaluate("note", values)

    def test_executor_enforces_target_authorization_and_validation(self) -> None:
        """Declared target access and native max length remain executor-owned."""
        instance = self._instance()
        executor = BehaviorExecutor(self._owner(), self.admin_user, instance=instance)
        values = {
            "note": "trigger",
            "quantity": "3",
            "unit_price": "2.50",
            "discount": "0.50",
            "total": "1.00",
        }
        executor.write_fields.pop("total")
        with self.assertRaises(PermissionDenied):
            executor.evaluate("note", values)

        short_executor = BehaviorExecutor(
            self._owner(target="short_code", expression="quantity * 100000"),
            self.admin_user,
            instance=instance,
        )
        with self.assertRaises(ValidationError):
            short_executor.evaluate(
                "note",
                {
                    "note": "trigger",
                    "quantity": "3",
                    "unit_price": "2.50",
                    "discount": "0.50",
                    "short_code": "old",
                },
            )
