# Generated by manage.py generate_test_cases.
"""Focused scenarios for safe one-to-many row arithmetic."""

from copy import deepcopy
from decimal import Decimal
from typing import Any
from unittest.mock import patch

from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from django.db import models

from bloomerp.form_behaviors.builtins.calculate_o2m_row import CALCULATE_O2M_ROW
from bloomerp.form_behaviors.definition import (
    BehaviorAction,
    BehaviorConfig,
    BehaviorContext,
    BehaviorResult,
    FieldValueUpdate,
    FormBehavior,
)
from bloomerp.form_behaviors.execution import BehaviorExecutor
from bloomerp.form_behaviors.shared.write_policy import WritePolicyField
from bloomerp.models.application_field import ApplicationField
from bloomerp.models.definition import FieldLayout, LayoutItem, LayoutRow
from bloomerp.models.users.user_object_layout_preference import (
    UserObjectLayoutPreference,
)
from bloomerp.tests.base import (
    BehaviorActionScenario,
    BloomerpBehaviorActionTestCase,
    ExpectedBehaviorActionException,
)
from bloomerp.tests.utils.dynamic_models import create_test_models


class TestCalculateO2mRowAction(BloomerpBehaviorActionTestCase):
    """Exercise expression validation, Decimal evaluation, and row preservation."""

    action = CALCULATE_O2M_ROW
    auto_create_customers = False
    invoice_model: type[models.Model]
    line_model: type[models.Model]

    @classmethod
    def setUpClass(cls) -> None:
        """Create invoice-line fields used by action and executor scenarios."""
        super().setUpClass()
        fixtures = create_test_models(
            "bloomerp",
            {
                "CalculatedInvoice": {"name": models.CharField(max_length=40)},
                "CalculatedInvoiceLine": {
                    "invoice": models.ForeignKey(
                        "bloomerp.CalculatedInvoice",
                        on_delete=models.CASCADE,
                        related_name="lines",
                    ),
                    "unit_price": models.DecimalField(
                        max_digits=10, decimal_places=2, null=True, blank=True
                    ),
                    "quantity": models.IntegerField(null=True, blank=True),
                    "discount": models.DecimalField(
                        max_digits=10, decimal_places=2, null=True, blank=True
                    ),
                    "line_total": models.DecimalField(
                        max_digits=10, decimal_places=2, null=True, blank=True
                    ),
                    "note": models.CharField(max_length=40, blank=True),
                },
            },
            use_bloomerp_base=True,
        )
        cls.invoice_model = fixtures["CalculatedInvoice"]
        cls.line_model = fixtures["CalculatedInvoiceLine"]

    def _listener(self) -> ApplicationField:
        """Resolve the invoice's reverse collection ApplicationField."""
        return self.get_application_field("lines", self.invoice_model)

    def _context(self, rows: list[dict[str, Any]]) -> BehaviorContext:
        """Build a listener-only draft context for collection rows."""
        return BehaviorContext(values={"lines": rows}, listener_field="lines")

    def get_test_scenarios(self) -> list[BehaviorActionScenario]:
        """Cover calculations, preservation, no-ops, errors, and invalid syntax."""
        rows = [
            {
                "id": "line-1",
                "unit_price": Decimal("10.25"),
                "quantity": 2,
                "discount": Decimal("0.50"),
                "line_total": Decimal("0.00"),
                "note": "Keep me",
            },
            {
                "id": "line-2",
                "unit_price": None,
                "quantity": 3,
                "discount": Decimal("0.00"),
                "line_total": None,
            },
            {
                "id": "line-3",
                "unit_price": Decimal("99.00"),
                "quantity": 4,
                "line_total": Decimal("7.00"),
                "DELETE": True,
            },
        ]
        expected_rows = deepcopy(rows)
        expected_rows[0]["line_total"] = Decimal("20.00")
        expected_rows[1]["line_total"] = Decimal("0.00")
        listener = self._listener()
        valid_scenarios = [
            BehaviorActionScenario(
                name="Precedence, Decimal values, blanks, and active rows are handled",
                context=self._context(rows),
                listener=listener,
                config={
                    "destination": "line_total",
                    "expression": "unit_price * quantity - discount",
                },
                expected_result=BehaviorResult(
                    values=(FieldValueUpdate(field="lines", value=expected_rows),)
                ),
            ),
            BehaviorActionScenario(
                name="Parentheses, unary signs, constants, and rounding are supported",
                context=self._context(
                    [
                        {
                            "unit_price": Decimal("0.10"),
                            "quantity": 2,
                            "discount": Decimal("0.10"),
                        },
                        {
                            "unit_price": Decimal("10.00"),
                            "quantity": 3,
                            "discount": Decimal("0.00"),
                        },
                    ]
                ),
                listener=listener,
                config={
                    "destination": "line_total",
                    "expression": "+(unit_price + 0.2 - discount) / quantity",
                },
                expected_result=BehaviorResult(
                    values=(
                        FieldValueUpdate(
                            field="lines",
                            value=[
                                {
                                    "unit_price": Decimal("0.10"),
                                    "quantity": 2,
                                    "discount": Decimal("0.10"),
                                    "line_total": Decimal("0.10"),
                                },
                                {
                                    "unit_price": Decimal("10.00"),
                                    "quantity": 3,
                                    "discount": Decimal("0.00"),
                                    "line_total": Decimal("3.40"),
                                },
                            ],
                        ),
                    )
                ),
            ),
            BehaviorActionScenario(
                name="An already-current destination produces no update",
                context=self._context(
                    [
                        {
                            "unit_price": Decimal("4.00"),
                            "quantity": 2,
                            "line_total": Decimal("8.00"),
                        }
                    ]
                ),
                listener=listener,
                config={
                    "destination": "line_total",
                    "expression": "unit_price * quantity",
                },
                expected_result=BehaviorResult(),
            ),
            BehaviorActionScenario(
                name="Empty-only writes blanks while preserving zero and nonzero cells",
                context=self._context(
                    [
                        {"unit_price": Decimal("5.00"), "line_total": None},
                        {"unit_price": Decimal("6.00"), "line_total": Decimal("0.00")},
                        {"unit_price": Decimal("7.00"), "line_total": Decimal("9.00")},
                    ]
                ),
                listener=listener,
                config={
                    "destination": "line_total",
                    "expression": "unit_price",
                    "write_policy": "if_empty",
                },
                expected_result=BehaviorResult(
                    values=(
                        FieldValueUpdate(
                            field="lines",
                            value=[
                                {
                                    "unit_price": Decimal("5.00"),
                                    "line_total": Decimal("5.00"),
                                },
                                {
                                    "unit_price": Decimal("6.00"),
                                    "line_total": Decimal("0.00"),
                                },
                                {
                                    "unit_price": Decimal("7.00"),
                                    "line_total": Decimal("9.00"),
                                },
                            ],
                        ),
                    )
                ),
            ),
            BehaviorActionScenario(
                name="Empty-or-zero normalizes string and Decimal zero but preserves nonzero",
                context=self._context(
                    [
                        {"unit_price": Decimal("4.00"), "line_total": ""},
                        {"unit_price": Decimal("5.00"), "line_total": "0.00"},
                        {"unit_price": Decimal("6.00"), "line_total": Decimal(0)},
                        {"unit_price": Decimal("7.00"), "line_total": Decimal("1.00")},
                    ]
                ),
                listener=listener,
                config={
                    "destination": "line_total",
                    "expression": "unit_price",
                    "write_policy": "if_empty_or_zero",
                },
                expected_result=BehaviorResult(
                    values=(
                        FieldValueUpdate(
                            field="lines",
                            value=[
                                {
                                    "unit_price": Decimal("4.00"),
                                    "line_total": Decimal("4.00"),
                                },
                                {
                                    "unit_price": Decimal("5.00"),
                                    "line_total": Decimal("5.00"),
                                },
                                {
                                    "unit_price": Decimal("6.00"),
                                    "line_total": Decimal("6.00"),
                                },
                                {
                                    "unit_price": Decimal("7.00"),
                                    "line_total": Decimal("1.00"),
                                },
                            ],
                        ),
                    )
                ),
            ),
            BehaviorActionScenario(
                name="A restrictive policy with no eligible cells returns no update",
                context=self._context(
                    [
                        {"unit_price": Decimal("5.00"), "line_total": Decimal("8.00")},
                    ]
                ),
                listener=listener,
                config={
                    "destination": "line_total",
                    "expression": "unit_price",
                    "write_policy": "if_empty_or_zero",
                },
                expected_result=BehaviorResult(),
            ),
            BehaviorActionScenario(
                name="Division by zero reports a useful validation error",
                context=self._context([{"unit_price": Decimal("4.00"), "quantity": 0}]),
                listener=listener,
                config={
                    "destination": "line_total",
                    "expression": "unit_price / quantity",
                },
                expected_exception=ExpectedBehaviorActionException(
                    ValidationError, "divides by zero"
                ),
            ),
            BehaviorActionScenario(
                name="Destination validation rejects fractional integer results",
                context=self._context([{"unit_price": Decimal("1.00")}]),
                listener=listener,
                config={
                    "destination": "quantity",
                    "expression": "unit_price / 2",
                },
                expected_exception=ExpectedBehaviorActionException(
                    ValidationError, "invalid for destination"
                ),
            ),
        ]
        invalid_scenarios = [
            BehaviorActionScenario(
                name=name,
                context=self._context([{}]),
                listener=listener,
                config={"destination": "line_total", "expression": expression},
                expected_exception=ExpectedBehaviorActionException(
                    ValidationError, message
                ),
            )
            for name, expression, message in (
                (
                    "Malformed expressions are rejected",
                    "unit_price *",
                    "valid arithmetic",
                ),
                ("Calls are rejected", "abs(unit_price)", "Unsupported expression"),
                (
                    "Unsupported operators are rejected",
                    "unit_price ** 2",
                    "support only",
                ),
                (
                    "Unknown columns are rejected",
                    "missing + 1",
                    "Unknown or non-numeric",
                ),
                (
                    "Non-numeric columns are rejected",
                    "note + 1",
                    "Unknown or non-numeric",
                ),
                (
                    "Destination self-reference is rejected",
                    "line_total + 1",
                    "cannot reference itself",
                ),
            )
        ]
        return [*valid_scenarios, *invalid_scenarios]

    def _execution_owner(self) -> UserObjectLayoutPreference:
        """Store the calculation on a real listener layout for boundary tests."""
        listener_config = {
            "inline_fields": [
                "unit_price",
                "quantity",
                "discount",
                "line_total",
                "note",
            ],
            "behaviors": BehaviorConfig(
                behaviors=[
                    FormBehavior(
                        id="calculate-line-total",
                        actions=[
                            BehaviorAction(
                                action="calculate_o2m_row",
                                config={
                                    "destination": "line_total",
                                    "expression": "unit_price * quantity",
                                },
                            )
                        ],
                    )
                ]
            ).to_storage(),
        }
        return UserObjectLayoutPreference.objects.create(
            user=self.admin_user,
            name="Calculated invoice",
            content_type=ContentType.objects.get_for_model(self.invoice_model),
            layout=FieldLayout(
                rows=[
                    LayoutRow(
                        columns=2,
                        items=[
                            LayoutItem(id="name"),
                            LayoutItem(id="lines", config=listener_config),
                        ],
                    )
                ]
            ).model_dump(mode="json"),
        )

    def _evaluate_with_denied_field_permission(
        self,
        denied_field: str,
        denied_permission: str,
    ) -> BehaviorResult:
        """Evaluate supplied draft rows while a child-field policy would deny access."""
        invoice = self.invoice_model.objects.create(name="Draft invoice")
        executor = BehaviorExecutor(
            self._execution_owner(), self.admin_user, instance=invoice
        )

        def has_field_permission(
            field: ApplicationField,
            permission: str,
        ) -> bool:
            """Deny exactly the child-field capability selected by the scenario."""
            return not (field.field == denied_field and permission == denied_permission)

        with patch.object(
            executor.manager,
            "has_field_permission",
            side_effect=has_field_permission,
        ) as permission_check:
            result = executor.evaluate(
                "lines",
                {
                    "name": invoice.name,
                    "lines": [
                        {
                            "unit_price": "5.00",
                            "quantity": "2",
                            "line_total": "0.00",
                        }
                    ],
                },
            )
        permission_check.assert_not_called()
        return result

    def test_execution_does_not_require_view_access_to_supplied_row_values(self) -> None:
        """Arithmetic over client-supplied row values performs no server-side read."""
        result = self._evaluate_with_denied_field_permission("unit_price", "view")
        self.assertEqual(result.values[0].value[0]["line_total"], "10.00")

    def test_execution_defers_destination_change_access_to_submission(self) -> None:
        """A draft suggestion is calculated before submission authorizes its write."""
        result = self._evaluate_with_denied_field_permission("line_total", "change")
        self.assertEqual(result.values[0].value[0]["line_total"], "10.00")

    def test_write_policy_uses_shared_subset_and_legacy_default(self) -> None:
        """Row calculation uses all scalar policies and defaults omissions."""
        form_class = self.action.config_form_factory(None, self._listener())
        field = form_class.base_fields["write_policy"]
        self.assertIsInstance(field, WritePolicyField)
        self.assertEqual(
            [choice[0] for choice in field.choices],
            ["always", "if_empty", "if_empty_or_zero"],
        )
        self.assertEqual(field.clean(""), "always")
