# Generated by manage.py generate_test_cases.
from bloomerp.form_behaviors.builtins.show_field import SHOW_FIELD
from bloomerp.tests.base import (
    BehaviorActionScenario,
    BloomerpBehaviorActionTestCase,
)


class TestShowFieldAction(BloomerpBehaviorActionTestCase):
    """Scenarios for the SHOW_FIELD behavior action."""

    action = SHOW_FIELD

    def get_test_scenarios(self) -> list[BehaviorActionScenario]:
        """Return the execution scenarios for this action."""
        # Add only the scenarios this action needs.
        return []
