# Generated by manage.py generate_test_cases.
from bloomerp.form_behaviors.builtins.copy_value import COPY_VALUE
from bloomerp.tests.base import (
    BehaviorActionScenario,
    BloomerpBehaviorActionTestCase,
)


class TestCopyValueAction(BloomerpBehaviorActionTestCase):
    """Scenarios for the COPY_VALUE behavior action."""

    action = COPY_VALUE

    def get_test_scenarios(self) -> list[BehaviorActionScenario]:
        """Return the execution scenarios for this action."""
        # Add only the scenarios this action needs.
        return []
