# Generated by manage.py generate_test_cases.
from django.core.exceptions import ValidationError

from bloomerp.form_behaviors.builtins.copy_related_value import COPY_RELATED_VALUE
from bloomerp.form_behaviors.definition import (
    BehaviorContext,
    BehaviorResult,
    FieldValueUpdate,
)
from bloomerp.tests.base import (
    BehaviorActionScenario,
    BloomerpBehaviorActionTestCase,
    ExpectedBehaviorActionException,
)


class TestCopyRelatedValueAction(BloomerpBehaviorActionTestCase):
    """Verify compatible related values copy into a target draft field."""

    action = COPY_RELATED_VALUE
    create_foreign_models = True

    def get_test_scenarios(self) -> list[BehaviorActionScenario]:
        """Describe copying, no-op, write-policy, and validation outcomes."""
        related_type = self.CustomerTypeModel.objects.get(name="Retail")
        listener = self.get_application_field("customer_type")
        target = self.get_application_field("first_name")
        related_name = self.get_application_field("name", self.CustomerTypeModel)
        return [
            BehaviorActionScenario(
                name="Copy the related name and replace an existing target by default",
                context=BehaviorContext(
                    values={
                        "customer_type": str(related_type.pk),
                        "first_name": "Draft name",
                    },
                    listener_field="customer_type",
                    target_field="first_name",
                    model=self.CustomerModel,
                ),
                config={"related_field": related_name.pk},
                listener=listener,
                target=target,
                expected_result=BehaviorResult(
                    values=(FieldValueUpdate(field="first_name", value="Retail"),)
                ),
            ),
            BehaviorActionScenario(
                name="Keep an existing target when copying only if empty",
                context=BehaviorContext(
                    values={
                        "customer_type": str(related_type.pk),
                        "first_name": "Keep this draft",
                    },
                    listener_field="customer_type",
                    target_field="first_name",
                    model=self.CustomerModel,
                ),
                config={
                    "related_field": related_name.pk,
                    "write_policy": "if_empty",
                },
                listener=listener,
                target=target,
                expected_result=BehaviorResult(),
            ),
            BehaviorActionScenario(
                name="Copy into a missing target when copying only if empty",
                context=BehaviorContext(
                    values={
                        "customer_type": str(related_type.pk),
                        "first_name": None,
                    },
                    listener_field="customer_type",
                    target_field="first_name",
                    model=self.CustomerModel,
                ),
                config={
                    "related_field": related_name.pk,
                    "write_policy": "if_empty",
                },
                listener=listener,
                target=target,
                expected_result=BehaviorResult(
                    values=(FieldValueUpdate(field="first_name", value="Retail"),)
                ),
            ),
            BehaviorActionScenario(
                name="Do nothing when the related object is not selected",
                context=BehaviorContext(
                    values={"customer_type": None, "first_name": "Draft name"},
                    listener_field="customer_type",
                    target_field="first_name",
                    model=self.CustomerModel,
                ),
                config={"related_field": related_name.pk},
                listener=listener,
                target=target,
                expected_result=BehaviorResult(),
            ),
            BehaviorActionScenario(
                name="Reject a related field whose type differs from the target",
                context=BehaviorContext(
                    values={
                        "customer_type": str(related_type.pk),
                        "first_name": None,
                    },
                    listener_field="customer_type",
                    target_field="first_name",
                    model=self.CustomerModel,
                ),
                config={"related_field": self.get_application_field("planet", self.CountryModel).pk},
                listener=listener,
                target=target,
                expected_exception=ExpectedBehaviorActionException(ValidationError),
            ),
            BehaviorActionScenario(
                name="Require a target field before validating related-value configuration",
                context=BehaviorContext(
                    values={"customer_type": str(related_type.pk)},
                    listener_field="customer_type",
                    model=self.CustomerModel,
                ),
                listener=listener,
                expected_exception=ExpectedBehaviorActionException(
                    ValidationError,
                    "Select a target field",
                ),
            ),
        ]
