# Generated by manage.py generate_test_cases.
"""Focused scenarios for target-specific empty value semantics."""

from typing import Any

from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import PermissionDenied
from django.db import models

from bloomerp.form_behaviors.builtins.clear_value import CLEAR_VALUE
from bloomerp.form_behaviors.definition import (
    BehaviorAction,
    BehaviorConfig,
    BehaviorContext,
    BehaviorResult,
    FieldValueUpdate,
    FormBehavior,
)
from bloomerp.form_behaviors.execution import BehaviorExecutor
from bloomerp.models.definition import FieldLayout, LayoutItem, LayoutRow
from bloomerp.models.users.user_object_layout_preference import (
    UserObjectLayoutPreference,
)
from bloomerp.tests.base import (
    BehaviorActionScenario,
    BloomerpBehaviorActionTestCase,
)
from bloomerp.tests.utils.dynamic_models import create_test_models


class TestClearValueAction(BloomerpBehaviorActionTestCase):
    """Verify clearing across scalar, relation, multi-value, and collection fields."""

    action = CLEAR_VALUE
    auto_create_customers = False
    category_model: type[models.Model]
    document_model: type[models.Model]

    @classmethod
    def setUpClass(cls) -> None:
        """Create representative field shapes for empty-value contract checks."""
        super().setUpClass()
        fixtures = create_test_models(
            "bloomerp",
            {
                "ClearCategory": {"name": models.CharField(max_length=40)},
                "ClearTag": {"name": models.CharField(max_length=40)},
                "ClearDocument": {
                    "name": models.CharField(max_length=40),
                    "text": models.CharField(max_length=40, blank=True),
                    "active": models.BooleanField(default=True),
                    "amount": models.IntegerField(null=True, blank=True),
                    "category": models.ForeignKey(
                        "bloomerp.ClearCategory",
                        null=True,
                        blank=True,
                        on_delete=models.SET_NULL,
                    ),
                    "tags": models.ManyToManyField("bloomerp.ClearTag", blank=True),
                },
                "ClearLine": {
                    "document": models.ForeignKey(
                        "bloomerp.ClearDocument",
                        on_delete=models.CASCADE,
                        related_name="lines",
                    ),
                    "description": models.CharField(max_length=40),
                },
            },
            use_bloomerp_base=True,
        )
        cls.category_model = fixtures["ClearCategory"]
        cls.document_model = fixtures["ClearDocument"]

    def _scenario(
        self, field_name: str, current: Any, expected: Any,
    ) -> BehaviorActionScenario:
        """Build one exact clear-result scenario for a target field shape."""
        target = self.get_application_field(field_name, self.document_model)
        return BehaviorActionScenario(
            name=f"Clear {field_name} using its public empty representation",
            context=BehaviorContext(
                values={"name": "Listener", field_name: current},
                listener_field="name",
                target_field=field_name,
            ),
            listener=self.get_application_field("name", self.document_model),
            target=target,
            expected_result=BehaviorResult(
                values=(FieldValueUpdate(field=field_name, value=expected),)
            ),
        )

    def get_test_scenarios(self) -> list[BehaviorActionScenario]:
        """Cover each materially different empty-value shape."""
        return [
            self._scenario("text", "Populated", ""),
            self._scenario("active", True, False),
            self._scenario("amount", 42, None),
            self._scenario("category", "category-id", None),
            self._scenario("tags", ["tag-1", "tag-2"], []),
            self._scenario(
                "lines",
                [{"id": "line-1", "description": "Keep?"}],
                [],
            ),
        ]

    def _execution_owner(self) -> UserObjectLayoutPreference:
        """Store a clear action on a real document layout."""
        return UserObjectLayoutPreference.objects.create(
            user=self.admin_user,
            name="Clear value document",
            content_type=ContentType.objects.get_for_model(self.document_model),
            layout=FieldLayout(
                rows=[LayoutRow(columns=2, items=[
                    LayoutItem(
                        id="name",
                        config={
                            "behaviors": BehaviorConfig(
                                behaviors=[FormBehavior(
                                    id="clear-active",
                                    actions=[BehaviorAction(
                                        action="clear_value",
                                        target_field="active",
                                    )],
                                )]
                            ).to_storage()
                        },
                    ),
                    LayoutItem(id="active"),
                ])]
            ).model_dump(mode="json"),
        )

    def _executor(self) -> tuple[BehaviorExecutor, models.Model]:
        """Create an authorized executor and unchanged persisted document."""
        document = self.document_model.objects.create(name="Stored", active=True)
        return (
            BehaviorExecutor(
                self._execution_owner(), self.admin_user, instance=document
            ),
            document,
        )

    def test_execution_normalizes_empty_value_without_persisting(self) -> None:
        """The executor returns a public boolean empty and leaves storage untouched."""
        executor, document = self._executor()
        result = executor.evaluate(
            "name", {"name": "Draft", "active": True}
        )
        self.assertEqual(
            result.values,
            (FieldValueUpdate(field="active", value=False),),
        )
        document.refresh_from_db()
        self.assertTrue(document.active)

    def test_execution_rejects_an_unauthorized_target(self) -> None:
        """Clear value cannot bypass the executor's target write boundary."""
        executor, _document = self._executor()
        executor.write_fields.pop("active")
        with self.assertRaises(PermissionDenied):
            executor.evaluate("name", {"name": "Draft", "active": True})
