# Generated by manage.py generate_test_cases.
from bloomerp.form_behaviors.builtins.disable_field import DISABLE_FIELD
from bloomerp.form_behaviors.definition import (
    BehaviorContext,
    BehaviorResult,
    FieldStateUpdate,
)
from bloomerp.tests.base import (
    BehaviorActionScenario,
    BloomerpBehaviorActionTestCase,
)


class TestDisableFieldAction(BloomerpBehaviorActionTestCase):
    """Verify disabling preserves both target value and visibility."""

    action = DISABLE_FIELD

    def get_test_scenarios(self) -> list[BehaviorActionScenario]:
        """Return an interaction-only state update for the declared target."""
        return [BehaviorActionScenario(
            name="Disable last name without changing its value or visibility",
            context=BehaviorContext(
                values={"first_name": "Ada", "last_name": "Lovelace"},
                listener_field="first_name",
                target_field="last_name",
            ),
            listener=self.get_application_field("first_name"),
            target=self.get_application_field("last_name"),
            expected_result=BehaviorResult(states=(FieldStateUpdate(
                field="last_name",
                visible=None,
                disabled=True,
            ),)),
        )]
