# Generated by manage.py generate_test_cases.
from bloomerp.models.automation.workflow_edge import WorkflowEdge
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
    ExpectedModelException,
)


class TestWorkflowEdgeModel(BloomerpModelTestCase):
    model = WorkflowEdge

    def get_test_scenarios(self) -> list[ModelScenario[WorkflowEdge]]:
        # Add only the scenarios this class needs.
        return []
