# Generated by manage.py generate_test_cases.
from bloomerp.models.automation.workflow_run_step import WorkflowRunStep
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
)


class TestWorkflowRunStepModel(BloomerpModelTestCase):
    model = WorkflowRunStep

    def get_test_scenarios(self) -> list[ModelScenario[WorkflowRunStep]]:
        # Add only the scenarios this class needs.
        return []
