# Generated by manage.py generate_test_cases.
from bloomerp.models.automation.workflow import Workflow
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
)


class TestWorkflowModel(BloomerpModelTestCase):
    model = Workflow

    def get_test_scenarios(self) -> list[ModelScenario[Workflow]]:
        # Add only the scenarios this class needs.
        return []
