# Generated by manage.py generate_test_cases.
from bloomerp.models.automation.workflow_run import WorkflowRun
from bloomerp.tests.base import (
    BloomerpModelTestCase,
    ModelScenario,
    ExpectedModelException,
)


class TestWorkflowRunModel(BloomerpModelTestCase):
    model = WorkflowRun

    def get_test_scenarios(self) -> list[ModelScenario[WorkflowRun]]:
        # Add only the scenarios this class needs.
        return []
